// Code generated by generate-terraform-provider. DO NOT EDIT.

package userrole_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceUserRolesBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_role" "source" {
  role_name = %q
  permissions = ["api.groups.read"]
  description = "Managed by Terraform acceptance tests"
}

resource "openai_user_role" "source" {
  user_id = %q
  role_id = openai_role.source.role_id
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-user-roles-{suffix}"),
		acctest.FixtureValue(t, "user_id"),
	)
}

func testAccDataSourceUserRolesBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_role" "source" {
  role_name = %q
  permissions = ["api.groups.read"]
  description = "Managed by Terraform acceptance tests"
}

resource "openai_user_role" "source" {
  user_id = %q
  role_id = openai_role.source.role_id
}

data "openai_user_roles" "lookup" {
  user_id = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-user-roles-{suffix}"),
		acctest.FixtureValue(t, "user_id"),
		acctest.FixtureValue(t, "user_id"),
	)
}

func TestAccDataSourceUserRoles_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceUserRolesBasicConfig1(t),
			},
			{
				Config: testAccDataSourceUserRolesBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("data.openai_user_roles.lookup", "user_id", acctest.FixtureValue(t, "user_id")),
				),
			},
		},
	})
}
