// Code generated by generate-terraform-provider. DO NOT EDIT.

package userrole

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ resource.Resource = &UserRoleResource{}
var _ resource.ResourceWithConfigure = &UserRoleResource{}
var _ resource.ResourceWithImportState = &UserRoleResource{}

type UserRoleResource struct {
	client *openaiapi.APIClient
}

type UserRoleResourceModel struct {
	UserID types.String `tfsdk:"user_id"`
	RoleID types.String `tfsdk:"role_id"`
}

func NewUserRoleResource() resource.Resource {
	return &UserRoleResource{}
}

func (r *UserRoleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "openai_user_role"
}

func (r *UserRoleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manage an organization-level role assignment for a user.",
		Attributes: map[string]schema.Attribute{
			"user_id": schema.StringAttribute{
				MarkdownDescription: "user id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"role_id": schema.StringAttribute{
				MarkdownDescription: "role id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

func (r *UserRoleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *UserRoleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data UserRoleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"user_id": data.UserID.ValueString(),
	}
	queryParams := map[string]string{}
	body := map[string]any{}
	openaiapi.AddStringBodyField(body, "role_id", data.RoleID)
	responseData, err := r.client.Request(ctx, "POST", "/organization/users/{user_id}/roles", pathParams, queryParams, body)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"role.id", "id"}, &data.RoleID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *UserRoleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data UserRoleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"user_id": data.UserID.ValueString(),
		"role_id": data.RoleID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.Request(ctx, "GET", "/organization/users/{user_id}/roles/{role_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"role.id", "id"}, &data.RoleID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *UserRoleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data UserRoleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	resp.Diagnostics.AddError("Unsupported update", "The provider config does not define an update operation for openai_user_role. Change replace-only attributes by recreating the resource.")
}

func (r *UserRoleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data UserRoleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"user_id": data.UserID.ValueString(),
		"role_id": data.RoleID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.Request(ctx, "DELETE", "/organization/users/{user_id}/roles/{role_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	_ = responseData
	resp.State.RemoveResource(ctx)
}

func (r *UserRoleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("Expected import ID format %q.", "{user_id}/{role_id}"))
		return
	}
	if err := openaiapi.ValidatePathParameter("user_id", parts[0]); err != nil {
		resp.Diagnostics.AddError("Invalid import ID", err.Error())
		return
	}
	if err := openaiapi.ValidatePathParameter("role_id", parts[1]); err != nil {
		resp.Diagnostics.AddError("Invalid import ID", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("user_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("role_id"), parts[1])...)
}
