// Code generated by generate-terraform-provider. DO NOT EDIT.

package userrole_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccUserRoleBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_role" "test" {
  role_name = %q
  permissions = ["api.groups.read"]
  description = "Managed by Terraform acceptance tests"
}

resource "openai_user_role" "test" {
  user_id = %q
  role_id = openai_role.test.role_id
}
`,
		acctest.TemplateValue(t, "tf-acc-openai-user-role-{suffix}"),
		acctest.FixtureValue(t, "user_id"),
	)
}

func TestAccUserRole_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccUserRoleBasicConfig1(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("openai_user_role.test", "user_id", acctest.FixtureValue(t, "user_id")),
				),
			},
		},
	})
}
