// Code generated by generate-terraform-provider. DO NOT EDIT.

package organizationspendalert

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ datasource.DataSource = &OrganizationSpendAlertsDataSource{}
var _ datasource.DataSourceWithConfigure = &OrganizationSpendAlertsDataSource{}

type OrganizationSpendAlertsDataSource struct {
	client *openaiapi.APIClient
}

type OrganizationSpendAlertsDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	ResponseJSON types.String `tfsdk:"response_json"`
	SpendAlerts  types.List   `tfsdk:"spend_alerts"`
}

type OrganizationSpendAlertsDataSourceItemModel struct {
	ID              types.String `tfsdk:"id"`
	ThresholdAmount types.Int64  `tfsdk:"threshold_amount"`
	Currency        types.String `tfsdk:"currency"`
	Interval        types.String `tfsdk:"interval"`
}

func NewOrganizationSpendAlertsDataSource() datasource.DataSource {
	return &OrganizationSpendAlertsDataSource{}
}

func (d *OrganizationSpendAlertsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_organization_spend_alerts"
}

func (d *OrganizationSpendAlertsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "List organization spend alerts.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Synthetic data source identifier.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},

			"spend_alerts": schema.ListNestedAttribute{
				MarkdownDescription: "Organization spend alerts returned by the API.",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "id",
							Computed:            true,
						},
						"threshold_amount": schema.Int64Attribute{
							MarkdownDescription: "threshold amount",
							Computed:            true,
						},
						"currency": schema.StringAttribute{
							MarkdownDescription: "currency",
							Computed:            true,
						},
						"interval": schema.StringAttribute{
							MarkdownDescription: "interval",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *OrganizationSpendAlertsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *OrganizationSpendAlertsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data OrganizationSpendAlertsDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{}
	queryParams := map[string]string{
		"limit": "100",
	}
	responseData, err := d.client.PaginatedRequest(ctx, "GET", "/organization/spend_alerts", pathParams, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	data.ID = types.StringValue("openai_organization_spend_alerts")

	resultItems, err := openaiapi.ResponseObjectList(responseData, "data", true)
	if err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	items := []OrganizationSpendAlertsDataSourceItemModel{}
	for _, itemData := range resultItems {
		item := OrganizationSpendAlertsDataSourceItemModel{}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"id"}, &item.ID, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"threshold_amount"}, &item.ThresholdAmount, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"currency"}, &item.Currency, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"interval"}, &item.Interval, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		items = append(items, item)
	}
	itemsValue, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: map[string]attr.Type{
		"id":               types.StringType,
		"threshold_amount": types.Int64Type,
		"currency":         types.StringType,
		"interval":         types.StringType,
	}}, items)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	data.SpendAlerts = itemsValue
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
