// Code generated by generate-terraform-provider. DO NOT EDIT.

package certificate_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceCertificatesBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_certificate" "source" {
  name = %q
  certificate = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-certificates-{suffix}"),
		acctest.FixtureValue(t, "certificate_pem"),
	)
}

func testAccDataSourceCertificatesBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_certificate" "source" {
  name = %q
  certificate = %q
}

data "openai_certificates" "lookup" {
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-certificates-{suffix}"),
		acctest.FixtureValue(t, "certificate_pem"),
	)
}

func TestAccDataSourceCertificates_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceCertificatesBasicConfig1(t),
			},
			{
				Config: testAccDataSourceCertificatesBasicConfig2(t),
			},
		},
	})
}
