// Code generated by generate-terraform-provider. DO NOT EDIT.

package certificate_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccCertificateBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_certificate" "test" {
  name = %q
  certificate = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-openai-certificate-{suffix}"),
		acctest.FixtureValue(t, "certificate_pem"),
	)
}

func TestAccCertificate_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccCertificateBasicConfig1(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("openai_certificate.test", "name", acctest.TemplateValue(t, "tf-acc-openai-certificate-{suffix}")),
				),
			},
		},
	})
}
