// Code generated by generate-terraform-provider. DO NOT EDIT.

package grouprole_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceGroupRolesBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_group" "source" {
  name = %q
}

resource "openai_role" "source" {
  role_name = %q
  permissions = ["api.groups.read"]
  description = "Managed by Terraform acceptance tests"
}

resource "openai_group_role" "source" {
  group_id = openai_group.source.group_id
  role_id = openai_role.source.role_id
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-group-roles-{suffix}"),
		acctest.TemplateValue(t, "tf-acc-ds-openai-group-roles-{suffix}"),
	)
}

func testAccDataSourceGroupRolesBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_group" "source" {
  name = %q
}

resource "openai_role" "source" {
  role_name = %q
  permissions = ["api.groups.read"]
  description = "Managed by Terraform acceptance tests"
}

resource "openai_group_role" "source" {
  group_id = openai_group.source.group_id
  role_id = openai_role.source.role_id
}

data "openai_group_roles" "lookup" {
  group_id = openai_group.source.group_id
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-group-roles-{suffix}"),
		acctest.TemplateValue(t, "tf-acc-ds-openai-group-roles-{suffix}"),
	)
}

func TestAccDataSourceGroupRoles_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceGroupRolesBasicConfig1(t),
			},
			{
				Config: testAccDataSourceGroupRolesBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("data.openai_group_roles.lookup", "group_id", "openai_group.source", "group_id"),
				),
			},
		},
	})
}
