// Code generated by generate-terraform-provider. DO NOT EDIT.

package grouprole_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccGroupRoleBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_group" "test" {
  name = %q
}

resource "openai_role" "test" {
  role_name = %q
  permissions = ["api.groups.read"]
  description = "Managed by Terraform acceptance tests"
}

resource "openai_group_role" "test" {
  group_id = openai_group.test.group_id
  role_id = openai_role.test.role_id
}
`,
		acctest.TemplateValue(t, "tf-acc-openai-group-role-{suffix}"),
		acctest.TemplateValue(t, "tf-acc-openai-group-role-{suffix}"),
	)
}

func TestAccGroupRole_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccGroupRoleBasicConfig1(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("openai_group_role.test", "group_id", "openai_group.test", "group_id"),
				),
			},
		},
	})
}
