// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectratelimit_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceProjectRateLimitsBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-rate-limits-{suffix}"),
	)
}

func testAccDataSourceProjectRateLimitsBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

data "openai_project_rate_limits" "lookup" {
  project_id = openai_project.source.project_id
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-rate-limits-{suffix}"),
	)
}

func TestAccDataSourceProjectRateLimits_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceProjectRateLimitsBasicConfig1(t),
			},
			{
				Config: testAccDataSourceProjectRateLimitsBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("data.openai_project_rate_limits.lookup", "project_id", "openai_project.source", "project_id"),
				),
			},
		},
	})
}
