// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectratelimit

import (
	"context"
	"fmt"

	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &ProjectRateLimitDataSource{}
var _ datasource.DataSourceWithConfigure = &ProjectRateLimitDataSource{}

type ProjectRateLimitDataSource struct {
	client *openaiapi.APIClient
}

type ProjectRateLimitDataSourceModel struct {
	ProjectID                   types.String `tfsdk:"project_id"`
	RateLimitID                 types.String `tfsdk:"rate_limit_id"`
	ID                          types.String `tfsdk:"id"`
	Model                       types.String `tfsdk:"model"`
	MaxRequestsPer1Minute       types.Int64  `tfsdk:"max_requests_per_1_minute"`
	MaxTokensPer1Minute         types.Int64  `tfsdk:"max_tokens_per_1_minute"`
	MaxImagesPer1Minute         types.Int64  `tfsdk:"max_images_per_1_minute"`
	MaxAudioMegabytesPer1Minute types.Int64  `tfsdk:"max_audio_megabytes_per_1_minute"`
	MaxRequestsPer1Day          types.Int64  `tfsdk:"max_requests_per_1_day"`
	Batch1DayMaxInputTokens     types.Int64  `tfsdk:"batch_1_day_max_input_tokens"`
	ResponseJSON                types.String `tfsdk:"response_json"`
}

func NewProjectRateLimitDataSource() datasource.DataSource {
	return &ProjectRateLimitDataSource{}
}

func (d *ProjectRateLimitDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_project_rate_limit"
}

func (d *ProjectRateLimitDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Look up a project rate limit by ID.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "project id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"rate_limit_id": schema.StringAttribute{
				MarkdownDescription: "rate limit id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "id",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"model": schema.StringAttribute{
				MarkdownDescription: "model",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"max_requests_per_1_minute": schema.Int64Attribute{
				MarkdownDescription: "max requests per 1 minute",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"max_tokens_per_1_minute": schema.Int64Attribute{
				MarkdownDescription: "max tokens per 1 minute",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"max_images_per_1_minute": schema.Int64Attribute{
				MarkdownDescription: "max images per 1 minute",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"max_audio_megabytes_per_1_minute": schema.Int64Attribute{
				MarkdownDescription: "max audio megabytes per 1 minute",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"max_requests_per_1_day": schema.Int64Attribute{
				MarkdownDescription: "max requests per 1 day",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"batch_1_day_max_input_tokens": schema.Int64Attribute{
				MarkdownDescription: "batch 1 day max input tokens",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
		},
	}
}

func (d *ProjectRateLimitDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *ProjectRateLimitDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectRateLimitDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"project_id": data.ProjectID.ValueString(),
	}
	queryParams := map[string]string{
		"limit": "1000",
	}
	responseData, err := d.client.CachedPaginatedRequest(ctx, "project_rate_limits", []string{"project_id"}, "GET", "/organization/projects/{project_id}/rate_limits", pathParams, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	selectedResponseData, found, err := openaiapi.ResponseObjectByField(responseData, "data", "id", data.RateLimitID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("OpenAI API response did not contain the requested item", "The list response did not include an item matching the configured identifier.")
		return
	}
	responseData = selectedResponseData
	data.ID = types.StringValue(fmt.Sprintf("openai_project_rate_limit/%s/%s", data.ProjectID.ValueString(), data.RateLimitID.ValueString()))
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"model"}, &data.Model, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"max_requests_per_1_minute"}, &data.MaxRequestsPer1Minute, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"max_tokens_per_1_minute"}, &data.MaxTokensPer1Minute, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"max_images_per_1_minute"}, &data.MaxImagesPer1Minute, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"max_audio_megabytes_per_1_minute"}, &data.MaxAudioMegabytesPer1Minute, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"max_requests_per_1_day"}, &data.MaxRequestsPer1Day, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"batch_1_day_max_input_tokens"}, &data.Batch1DayMaxInputTokens, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
