// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectratelimit_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceProjectRateLimitBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

resource "openai_project_rate_limit" "source" {
  project_id = openai_project.source.project_id
  rate_limit_id = %q
  max_requests_per_1_minute = 1
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-rate-limit-{suffix}"),
		acctest.FixtureValue(t, "rate_limit_id"),
	)
}

func testAccDataSourceProjectRateLimitBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

resource "openai_project_rate_limit" "source" {
  project_id = openai_project.source.project_id
  rate_limit_id = %q
  max_requests_per_1_minute = 1
}

data "openai_project_rate_limit" "lookup" {
  project_id = openai_project.source.project_id
  rate_limit_id = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-rate-limit-{suffix}"),
		acctest.FixtureValue(t, "rate_limit_id"),
		acctest.FixtureValue(t, "rate_limit_id"),
	)
}

func TestAccDataSourceProjectRateLimit_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceProjectRateLimitBasicConfig1(t),
			},
			{
				Config: testAccDataSourceProjectRateLimitBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("data.openai_project_rate_limit.lookup", "project_id", "openai_project.source", "project_id"),
					resource.TestCheckResourceAttr("data.openai_project_rate_limit.lookup", "rate_limit_id", acctest.FixtureValue(t, "rate_limit_id")),
				),
			},
		},
	})
}
