// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectgroup_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceProjectGroupBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

resource "openai_group" "source" {
  name = %q
}

resource "openai_project_group" "source" {
  project_id = openai_project.source.project_id
  group_id = openai_group.source.group_id
  role = "role-api-project-member"
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-project-group-{suffix}"),
		acctest.TemplateValue(t, "tf-acc-ds-openai-project-group-{suffix}"),
	)
}

func testAccDataSourceProjectGroupBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

resource "openai_group" "source" {
  name = %q
}

resource "openai_project_group" "source" {
  project_id = openai_project.source.project_id
  group_id = openai_group.source.group_id
  role = "role-api-project-member"
}

data "openai_project_group" "lookup" {
  project_id = openai_project.source.project_id
  group_id = openai_group.source.group_id
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-project-group-{suffix}"),
		acctest.TemplateValue(t, "tf-acc-ds-openai-project-group-{suffix}"),
	)
}

func TestAccDataSourceProjectGroup_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceProjectGroupBasicConfig1(t),
			},
			{
				Config: testAccDataSourceProjectGroupBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("data.openai_project_group.lookup", "project_id", "openai_project.source", "project_id"),
					resource.TestCheckResourceAttrPair("data.openai_project_group.lookup", "group_id", "openai_group.source", "group_id"),
				),
			},
		},
	})
}
