// Code generated by generate-terraform-provider. DO NOT EDIT.

package invite

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ datasource.DataSource = &InvitesDataSource{}
var _ datasource.DataSourceWithConfigure = &InvitesDataSource{}

type InvitesDataSource struct {
	client *openaiapi.APIClient
}

type InvitesDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	ResponseJSON types.String `tfsdk:"response_json"`
	Invites      types.List   `tfsdk:"invites"`
}

type InvitesDataSourceItemModel struct {
	ID         types.String `tfsdk:"id"`
	Email      types.String `tfsdk:"email"`
	Role       types.String `tfsdk:"role"`
	Status     types.String `tfsdk:"status"`
	CreatedAt  types.Int64  `tfsdk:"created_at"`
	ExpiresAt  types.Int64  `tfsdk:"expires_at"`
	AcceptedAt types.Int64  `tfsdk:"accepted_at"`
}

func NewInvitesDataSource() datasource.DataSource {
	return &InvitesDataSource{}
}

func (d *InvitesDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_invites"
}

func (d *InvitesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "List organization invites.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Synthetic data source identifier.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},

			"invites": schema.ListNestedAttribute{
				MarkdownDescription: "Invites returned by the API.",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "id",
							Computed:            true,
						},
						"email": schema.StringAttribute{
							MarkdownDescription: "email",
							Computed:            true,
						},
						"role": schema.StringAttribute{
							MarkdownDescription: "role",
							Computed:            true,
						},
						"status": schema.StringAttribute{
							MarkdownDescription: "status",
							Computed:            true,
						},
						"created_at": schema.Int64Attribute{
							MarkdownDescription: "created at",
							Computed:            true,
						},
						"expires_at": schema.Int64Attribute{
							MarkdownDescription: "expires at",
							Computed:            true,
						},
						"accepted_at": schema.Int64Attribute{
							MarkdownDescription: "accepted at",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *InvitesDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *InvitesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data InvitesDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{}
	queryParams := map[string]string{
		"limit": "100",
	}
	responseData, err := d.client.PaginatedRequest(ctx, "GET", "/organization/invites", pathParams, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	data.ID = types.StringValue("openai_invites")

	resultItems, err := openaiapi.ResponseObjectList(responseData, "data", true)
	if err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	items := []InvitesDataSourceItemModel{}
	for _, itemData := range resultItems {
		item := InvitesDataSourceItemModel{}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"id"}, &item.ID, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"email"}, &item.Email, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"role"}, &item.Role, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"status"}, &item.Status, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"created_at"}, &item.CreatedAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"expires_at"}, &item.ExpiresAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"accepted_at"}, &item.AcceptedAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		items = append(items, item)
	}
	itemsValue, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: map[string]attr.Type{
		"id":          types.StringType,
		"email":       types.StringType,
		"role":        types.StringType,
		"status":      types.StringType,
		"created_at":  types.Int64Type,
		"expires_at":  types.Int64Type,
		"accepted_at": types.Int64Type,
	}}, items)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	data.Invites = itemsValue
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
