// Code generated by generate-terraform-provider. DO NOT EDIT.

package invite_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceInvitesBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_invite" "source" {
  email = %q
  role = "reader"
}
`,
		acctest.FixtureValue(t, "invite_email"),
	)
}

func testAccDataSourceInvitesBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_invite" "source" {
  email = %q
  role = "reader"
}

data "openai_invites" "lookup" {
}
`,
		acctest.FixtureValue(t, "invite_email"),
	)
}

func TestAccDataSourceInvites_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceInvitesBasicConfig1(t),
			},
			{
				Config: testAccDataSourceInvitesBasicConfig2(t),
			},
		},
	})
}
