// Code generated by generate-terraform-provider. DO NOT EDIT.

package webhookendpoint

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ datasource.DataSource = &WebhookEndpointsDataSource{}
var _ datasource.DataSourceWithConfigure = &WebhookEndpointsDataSource{}

type WebhookEndpointsDataSource struct {
	client *openaiapi.APIClient
}

type WebhookEndpointsDataSourceModel struct {
	ID               types.String `tfsdk:"id"`
	ResponseJSON     types.String `tfsdk:"response_json"`
	WebhookEndpoints types.List   `tfsdk:"webhook_endpoints"`
}

type WebhookEndpointsDataSourceItemModel struct {
	ID                types.String `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	URL               types.String `tfsdk:"url"`
	EventTypes        types.Set    `tfsdk:"event_types"`
	Object            types.String `tfsdk:"object"`
	CreatedAt         types.Int64  `tfsdk:"created_at"`
	UpdatedAt         types.Int64  `tfsdk:"updated_at"`
	SigningSecretHint types.String `tfsdk:"signing_secret_hint"`
}

func NewWebhookEndpointsDataSource() datasource.DataSource {
	return &WebhookEndpointsDataSource{}
}

func (d *WebhookEndpointsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_webhook_endpoints"
}

func (d *WebhookEndpointsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "List webhook endpoints in the project associated with the configured project API key.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Synthetic data source identifier.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},

			"webhook_endpoints": schema.ListNestedAttribute{
				MarkdownDescription: "Webhook endpoints returned by the API.",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "id",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "name",
							Computed:            true,
						},
						"url": schema.StringAttribute{
							MarkdownDescription: "url",
							Computed:            true,
						},
						"event_types": schema.SetAttribute{
							MarkdownDescription: "event types",
							ElementType:         types.StringType,
							Computed:            true,
						},
						"object": schema.StringAttribute{
							MarkdownDescription: "object",
							Computed:            true,
						},
						"created_at": schema.Int64Attribute{
							MarkdownDescription: "created at",
							Computed:            true,
						},
						"updated_at": schema.Int64Attribute{
							MarkdownDescription: "updated at",
							Computed:            true,
						},
						"signing_secret_hint": schema.StringAttribute{
							MarkdownDescription: "signing secret hint",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *WebhookEndpointsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	providerData, ok := req.ProviderData.(*openaiapi.ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.ProviderData, got: %T", req.ProviderData))
		return
	}
	client, ok := providerData.Client("project")
	if !ok {
		resp.Diagnostics.AddError(
			"Missing OpenAI credential for project API",
			"Configure the provider with a credential for the project API audience before using openai_webhook_endpoints.",
		)
		return
	}
	d.client = client
}

func (d *WebhookEndpointsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data WebhookEndpointsDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{}
	queryParams := map[string]string{
		"limit": "100",
	}
	responseData, err := d.client.PaginatedRequest(ctx, "GET", "/webhook_endpoints", pathParams, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	data.ID = types.StringValue("openai_webhook_endpoints")

	resultItems, err := openaiapi.ResponseObjectList(responseData, "data", true)
	if err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	items := []WebhookEndpointsDataSourceItemModel{}
	for _, itemData := range resultItems {
		item := WebhookEndpointsDataSourceItemModel{}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"id"}, &item.ID, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"name"}, &item.Name, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"url"}, &item.URL, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringSetResponseField(itemData, []string{"event_types"}, &item.EventTypes, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"object"}, &item.Object, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"created_at"}, &item.CreatedAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"updated_at"}, &item.UpdatedAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"signing_secret_hint"}, &item.SigningSecretHint, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		items = append(items, item)
	}
	itemsValue, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: map[string]attr.Type{
		"id":                  types.StringType,
		"name":                types.StringType,
		"url":                 types.StringType,
		"event_types":         types.SetType{ElemType: types.StringType},
		"object":              types.StringType,
		"created_at":          types.Int64Type,
		"updated_at":          types.Int64Type,
		"signing_secret_hint": types.StringType,
	}}, items)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	data.WebhookEndpoints = itemsValue
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
