// Code generated by generate-terraform-provider. DO NOT EDIT.

package webhookendpoint

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ resource.Resource = &WebhookEndpointResource{}
var _ resource.ResourceWithConfigure = &WebhookEndpointResource{}
var _ resource.ResourceWithImportState = &WebhookEndpointResource{}

type WebhookEndpointResource struct {
	client *openaiapi.APIClient
}

type WebhookEndpointResourceModel struct {
	ID                types.String `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	URL               types.String `tfsdk:"url"`
	EventTypes        types.Set    `tfsdk:"event_types"`
	Object            types.String `tfsdk:"object"`
	CreatedAt         types.Int64  `tfsdk:"created_at"`
	UpdatedAt         types.Int64  `tfsdk:"updated_at"`
	SigningSecretHint types.String `tfsdk:"signing_secret_hint"`
	SigningSecret     types.String `tfsdk:"signing_secret"`
}

func NewWebhookEndpointResource() resource.Resource {
	return &WebhookEndpointResource{}
}

func (r *WebhookEndpointResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "openai_webhook_endpoint"
}

func (r *WebhookEndpointResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Beta. Manage a webhook endpoint in the authenticated project using the `api_key` provider attribute or `OPENAI_API_KEY`. Reads require `api.webhooks.read`; create, update, and delete require `api.webhooks.write` and a project-owner credential. Organization Admin API keys are not accepted for this project-scoped API. The signing secret is returned only when the endpoint is created, is stored in Terraform state as a sensitive value, is unavailable after import, and can become stale if the secret is rotated outside Terraform. Testing an endpoint and rotating its signing secret are imperative API operations and are not managed by this Terraform resource.\n\nAuthentication: Set the api_key provider attribute or OPENAI_API_KEY environment variable for the project API audience.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Webhook endpoint identifier.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Human-readable webhook endpoint name.",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"url": schema.StringAttribute{
				MarkdownDescription: "HTTPS URL that receives webhook events.",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           true,
				Validators: []validator.String{
					openaiapi.StringLengthAtLeast(1),
					openaiapi.StringIsHTTPSURL(),
				},
			},
			"event_types": schema.SetAttribute{
				MarkdownDescription: "Event types delivered to this endpoint.",
				ElementType:         types.StringType,
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.Set{
					openaiapi.SetSizeAtLeast(1),
				},
			},
			"object": schema.StringAttribute{
				MarkdownDescription: "API object type.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created_at": schema.Int64Attribute{
				MarkdownDescription: "Unix timestamp when the endpoint was created.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"updated_at": schema.Int64Attribute{
				MarkdownDescription: "Unix timestamp when the endpoint was last updated.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"signing_secret_hint": schema.StringAttribute{
				MarkdownDescription: "Redacted hint for the endpoint signing secret.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"signing_secret": schema.StringAttribute{
				MarkdownDescription: "Signing secret returned only at creation. This value is stored in Terraform state, is unavailable after import, and is not refreshed after out-of-band rotation.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *WebhookEndpointResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	providerData, ok := req.ProviderData.(*openaiapi.ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *openaiapi.ProviderData, got: %T", req.ProviderData))
		return
	}
	client, ok := providerData.Client("project")
	if !ok {
		resp.Diagnostics.AddError(
			"Missing OpenAI credential for project API",
			"Set the api_key provider attribute or OPENAI_API_KEY environment variable for the project API audience before using openai_webhook_endpoint. Credentials are not reused across API audiences.",
		)
		return
	}
	r.client = client
}

func (r *WebhookEndpointResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data WebhookEndpointResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{}
	queryParams := map[string]string{}
	body := map[string]any{}
	openaiapi.AddStringBodyField(body, "name", data.Name)
	openaiapi.AddStringBodyField(body, "url", data.URL)
	if !data.EventTypes.IsNull() && !data.EventTypes.IsUnknown() {
		var eventTypesValue []string
		resp.Diagnostics.Append(data.EventTypes.ElementsAs(ctx, &eventTypesValue, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		openaiapi.SetBodyField(body, []string{"event_types"}, eventTypesValue)
	}
	responseData, err := r.client.RequestWithoutRetries(ctx, "POST", "/webhook_endpoints", pathParams, queryParams, body)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"url"}, &data.URL, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringSetResponseField(responseData, []string{"event_types"}, &data.EventTypes, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"object"}, &data.Object, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"created_at"}, &data.CreatedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"updated_at"}, &data.UpdatedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"signing_secret_hint"}, &data.SigningSecretHint, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"signing_secret"}, &data.SigningSecret, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WebhookEndpointResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data WebhookEndpointResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"webhook_endpoint_id": data.ID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.Request(ctx, "GET", "/webhook_endpoints/{webhook_endpoint_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"url"}, &data.URL, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringSetResponseField(responseData, []string{"event_types"}, &data.EventTypes, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"object"}, &data.Object, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"created_at"}, &data.CreatedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"updated_at"}, &data.UpdatedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"signing_secret_hint"}, &data.SigningSecretHint, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WebhookEndpointResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data WebhookEndpointResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"webhook_endpoint_id": data.ID.ValueString(),
	}
	queryParams := map[string]string{}
	body := map[string]any{}
	openaiapi.AddStringBodyField(body, "name", data.Name)
	openaiapi.AddStringBodyField(body, "url", data.URL)
	if !data.EventTypes.IsNull() && !data.EventTypes.IsUnknown() {
		var eventTypesValue []string
		resp.Diagnostics.Append(data.EventTypes.ElementsAs(ctx, &eventTypesValue, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		openaiapi.SetBodyField(body, []string{"event_types"}, eventTypesValue)
	}
	responseData, err := r.client.RequestWithoutRetries(ctx, "POST", "/webhook_endpoints/{webhook_endpoint_id}", pathParams, queryParams, body)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"url"}, &data.URL, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringSetResponseField(responseData, []string{"event_types"}, &data.EventTypes, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"object"}, &data.Object, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"created_at"}, &data.CreatedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"updated_at"}, &data.UpdatedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"signing_secret_hint"}, &data.SigningSecretHint, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WebhookEndpointResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data WebhookEndpointResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"webhook_endpoint_id": data.ID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.RequestWithoutRetries(ctx, "DELETE", "/webhook_endpoints/{webhook_endpoint_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	_ = responseData
	resp.State.RemoveResource(ctx)
}

func (r *WebhookEndpointResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 1 {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("Expected import ID format %q.", "{id}"))
		return
	}
	if err := openaiapi.ValidatePathParameter("id", parts[0]); err != nil {
		resp.Diagnostics.AddError("Invalid import ID", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), parts[0])...)
}
