// Code generated by generate-terraform-provider. DO NOT EDIT.

package webhookendpoint

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"reflect"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	frameworkresource "github.com/hashicorp/terraform-plugin-framework/resource"
	resourceschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	schemavalidator "github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openai "github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

const (
	webhookTestID         = "whe_synthetic"
	webhookTestAPIKey     = "sk-project-synthetic-webhook-test"
	webhookTestSecret     = "whsec_synthetic_create_only_secret"
	webhookTestSecretHint = "whsec_...cret"
)

func webhookEndpointSchema(t *testing.T, managed *WebhookEndpointResource) tfsdk.State {
	t.Helper()
	var response frameworkresource.SchemaResponse
	managed.Schema(context.Background(), frameworkresource.SchemaRequest{}, &response)
	return tfsdk.State{Schema: response.Schema}
}

func webhookEndpointResource(t *testing.T, baseURL string) *WebhookEndpointResource {
	t.Helper()
	managed := NewWebhookEndpointResource().(*WebhookEndpointResource)
	providerData := openaiapi.NewProviderData()
	providerData.SetClient("project", &openaiapi.APIClient{
		Client: openai.NewClient(
			option.WithAPIKey(webhookTestAPIKey),
			option.WithBaseURL(baseURL+"/v1/"),
		),
	})
	var response frameworkresource.ConfigureResponse
	managed.Configure(
		context.Background(),
		frameworkresource.ConfigureRequest{ProviderData: providerData},
		&response,
	)
	if response.Diagnostics.HasError() {
		t.Fatalf("configure webhook endpoint resource: %v", response.Diagnostics)
	}
	return managed
}

func webhookEndpointPlan(
	t *testing.T,
	schema tfsdk.State,
	model WebhookEndpointResourceModel,
) tfsdk.Plan {
	t.Helper()
	plan := tfsdk.Plan{Schema: schema.Schema}
	if diagnostics := plan.Set(context.Background(), &model); diagnostics.HasError() {
		t.Fatalf("initialize webhook endpoint plan: %v", diagnostics)
	}
	return plan
}

func webhookEndpointModel(name string, secret types.String) WebhookEndpointResourceModel {
	return WebhookEndpointResourceModel{
		ID:   types.StringUnknown(),
		Name: types.StringValue(name),
		URL:  types.StringValue("https://example.com/openai/webhooks"),
		EventTypes: types.SetValueMust(types.StringType, []attr.Value{
			types.StringValue("response.completed"),
		}),
		Object:            types.StringUnknown(),
		CreatedAt:         types.Int64Unknown(),
		UpdatedAt:         types.Int64Unknown(),
		SigningSecretHint: types.StringUnknown(),
		SigningSecret:     secret,
	}
}

func TestWebhookEndpointURLRequiresHTTPS(t *testing.T) {
	managed := NewWebhookEndpointResource().(*WebhookEndpointResource)
	var schemaResponse frameworkresource.SchemaResponse
	managed.Schema(context.Background(), frameworkresource.SchemaRequest{}, &schemaResponse)
	urlAttribute, ok := schemaResponse.Schema.Attributes["url"].(resourceschema.StringAttribute)
	if !ok {
		t.Fatalf("url attribute has unexpected schema type %T", schemaResponse.Schema.Attributes["url"])
	}

	tests := []struct {
		name      string
		value     string
		wantError bool
	}{
		{name: "HTTPS URL", value: "https://example.com/openai/webhooks"},
		{name: "HTTP URL", value: "http://example.com/openai/webhooks", wantError: true},
		{name: "relative URL", value: "/openai/webhooks", wantError: true},
		{name: "missing host", value: "https:///openai/webhooks", wantError: true},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			request := schemavalidator.StringRequest{
				Path:        path.Root("url"),
				ConfigValue: types.StringValue(test.value),
			}
			var response schemavalidator.StringResponse
			for _, configuredValidator := range urlAttribute.Validators {
				configuredValidator.ValidateString(context.Background(), request, &response)
			}
			if gotError := response.Diagnostics.HasError(); gotError != test.wantError {
				t.Fatalf("URL validation error = %t, want %t: %v", gotError, test.wantError, response.Diagnostics)
			}
		})
	}
}

func webhookEndpointResponse(name string) map[string]any {
	return map[string]any{
		"id":                  webhookTestID,
		"object":              "webhook_endpoint",
		"created_at":          1,
		"updated_at":          2,
		"name":                name,
		"url":                 "https://example.com/openai/webhooks",
		"event_types":         []string{"response.completed"},
		"signing_secret_hint": webhookTestSecretHint,
	}
}

func writeWebhookEndpoint(w http.ResponseWriter, name string, includeSecret bool) {
	response := webhookEndpointResponse(name)
	if includeSecret {
		response["signing_secret"] = webhookTestSecret
	}
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(response)
}

func TestWebhookEndpointCreateRejectsNullSigningSecret(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		response := webhookEndpointResponse("created")
		response["signing_secret"] = nil
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(response)
	}))
	t.Cleanup(server.Close)

	managed := webhookEndpointResource(t, server.URL)
	state := webhookEndpointSchema(t, managed)
	createResponse := &frameworkresource.CreateResponse{
		State: tfsdk.State{Schema: state.Schema},
	}
	managed.Create(
		context.Background(),
		frameworkresource.CreateRequest{
			Plan: webhookEndpointPlan(
				t,
				state,
				webhookEndpointModel("created", types.StringUnknown()),
			),
		},
		createResponse,
	)
	if !createResponse.Diagnostics.HasError() {
		t.Fatal("create accepted a null signing_secret")
	}
}

func TestWebhookEndpointLifecyclePreservesCreateOnlySigningSecret(t *testing.T) {
	var requestBodies []map[string]any
	var requests []string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if got := req.Header.Get("Authorization"); got != "Bearer "+webhookTestAPIKey {
			t.Errorf("authorization = %q", got)
		}
		requests = append(requests, req.Method+" "+req.URL.Path)
		switch {
		case req.Method == http.MethodPost && req.URL.Path == "/v1/webhook_endpoints":
			var body map[string]any
			if err := json.NewDecoder(req.Body).Decode(&body); err != nil {
				t.Errorf("decode create body: %v", err)
				http.Error(w, "invalid body", http.StatusBadRequest)
				return
			}
			requestBodies = append(requestBodies, body)
			writeWebhookEndpoint(w, "created", true)
		case req.Method == http.MethodGet && req.URL.Path == "/v1/webhook_endpoints/"+webhookTestID:
			writeWebhookEndpoint(w, "created", false)
		case req.Method == http.MethodPost && req.URL.Path == "/v1/webhook_endpoints/"+webhookTestID:
			var body map[string]any
			if err := json.NewDecoder(req.Body).Decode(&body); err != nil {
				t.Errorf("decode update body: %v", err)
				http.Error(w, "invalid body", http.StatusBadRequest)
				return
			}
			requestBodies = append(requestBodies, body)
			writeWebhookEndpoint(w, "updated", false)
		case req.Method == http.MethodDelete && req.URL.Path == "/v1/webhook_endpoints/"+webhookTestID:
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintf(w, "{\"id\":%q,\"object\":\"webhook_endpoint.deleted\",\"deleted\":true}", webhookTestID)
		default:
			http.Error(w, "unexpected request", http.StatusNotFound)
		}
	}))
	t.Cleanup(server.Close)

	managed := webhookEndpointResource(t, server.URL)
	initialState := webhookEndpointSchema(t, managed)
	createResponse := &frameworkresource.CreateResponse{
		State: tfsdk.State{Schema: initialState.Schema},
	}
	managed.Create(
		context.Background(),
		frameworkresource.CreateRequest{
			Plan: webhookEndpointPlan(
				t,
				initialState,
				webhookEndpointModel("created", types.StringUnknown()),
			),
		},
		createResponse,
	)
	if createResponse.Diagnostics.HasError() {
		t.Fatalf("create webhook endpoint: %v", createResponse.Diagnostics)
	}

	var created WebhookEndpointResourceModel
	if diagnostics := createResponse.State.Get(context.Background(), &created); diagnostics.HasError() {
		t.Fatalf("read created state: %v", diagnostics)
	}
	if got := created.SigningSecret.ValueString(); got != webhookTestSecret {
		t.Fatalf("created signing secret = %q", got)
	}

	readResponse := &frameworkresource.ReadResponse{State: createResponse.State}
	managed.Read(
		context.Background(),
		frameworkresource.ReadRequest{State: createResponse.State},
		readResponse,
	)
	if readResponse.Diagnostics.HasError() {
		t.Fatalf("read webhook endpoint: %v", readResponse.Diagnostics)
	}
	var refreshed WebhookEndpointResourceModel
	if diagnostics := readResponse.State.Get(context.Background(), &refreshed); diagnostics.HasError() {
		t.Fatalf("read refreshed state: %v", diagnostics)
	}
	if got := refreshed.SigningSecret.ValueString(); got != webhookTestSecret {
		t.Fatalf("refreshed signing secret = %q", got)
	}

	refreshed.Name = types.StringValue("updated")
	updateResponse := &frameworkresource.UpdateResponse{
		State: tfsdk.State{Schema: initialState.Schema},
	}
	managed.Update(
		context.Background(),
		frameworkresource.UpdateRequest{
			Plan: webhookEndpointPlan(t, initialState, refreshed),
		},
		updateResponse,
	)
	if updateResponse.Diagnostics.HasError() {
		t.Fatalf("update webhook endpoint: %v", updateResponse.Diagnostics)
	}
	var updated WebhookEndpointResourceModel
	if diagnostics := updateResponse.State.Get(context.Background(), &updated); diagnostics.HasError() {
		t.Fatalf("read updated state: %v", diagnostics)
	}
	if got := updated.SigningSecret.ValueString(); got != webhookTestSecret {
		t.Fatalf("updated signing secret = %q", got)
	}

	for index, body := range requestBodies {
		want := map[string]any{
			"name":        []string{"created", "updated"}[index],
			"url":         "https://example.com/openai/webhooks",
			"event_types": []any{"response.completed"},
		}
		if !reflect.DeepEqual(body, want) {
			t.Fatalf("request body %d = %#v, want %#v", index, body, want)
		}
		if _, ok := body["signing_secret"]; ok {
			t.Fatalf("request body %d exposed the signing secret", index)
		}
	}

	deleteResponse := &frameworkresource.DeleteResponse{State: updateResponse.State}
	managed.Delete(
		context.Background(),
		frameworkresource.DeleteRequest{State: updateResponse.State},
		deleteResponse,
	)
	if deleteResponse.Diagnostics.HasError() {
		t.Fatalf("delete webhook endpoint: %v", deleteResponse.Diagnostics)
	}
	if !deleteResponse.State.Raw.IsNull() {
		t.Fatal("deleted webhook endpoint remained in state")
	}

	wantRequests := []string{
		"POST /v1/webhook_endpoints",
		"GET /v1/webhook_endpoints/" + webhookTestID,
		"POST /v1/webhook_endpoints/" + webhookTestID,
		"DELETE /v1/webhook_endpoints/" + webhookTestID,
	}
	if !reflect.DeepEqual(requests, wantRequests) {
		t.Fatalf("requests = %v, want %v", requests, wantRequests)
	}
}

func TestWebhookEndpointImportCannotRecoverSigningSecret(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.Method != http.MethodGet || req.URL.Path != "/v1/webhook_endpoints/"+webhookTestID {
			http.Error(w, "unexpected request", http.StatusNotFound)
			return
		}
		writeWebhookEndpoint(w, "imported", false)
	}))
	t.Cleanup(server.Close)

	managed := webhookEndpointResource(t, server.URL)
	state := webhookEndpointSchema(t, managed)
	if diagnostics := state.Set(context.Background(), &WebhookEndpointResourceModel{
		ID:                types.StringNull(),
		Name:              types.StringNull(),
		URL:               types.StringNull(),
		EventTypes:        types.SetNull(types.StringType),
		Object:            types.StringNull(),
		CreatedAt:         types.Int64Null(),
		UpdatedAt:         types.Int64Null(),
		SigningSecretHint: types.StringNull(),
		SigningSecret:     types.StringNull(),
	}); diagnostics.HasError() {
		t.Fatalf("initialize import state: %v", diagnostics)
	}
	importResponse := &frameworkresource.ImportStateResponse{State: state}
	managed.ImportState(
		context.Background(),
		frameworkresource.ImportStateRequest{ID: webhookTestID},
		importResponse,
	)
	if importResponse.Diagnostics.HasError() {
		t.Fatalf("import webhook endpoint: %v", importResponse.Diagnostics)
	}
	readResponse := &frameworkresource.ReadResponse{State: importResponse.State}
	managed.Read(
		context.Background(),
		frameworkresource.ReadRequest{State: importResponse.State},
		readResponse,
	)
	if readResponse.Diagnostics.HasError() {
		t.Fatalf("read imported webhook endpoint: %v", readResponse.Diagnostics)
	}
	var imported WebhookEndpointResourceModel
	if diagnostics := readResponse.State.Get(context.Background(), &imported); diagnostics.HasError() {
		t.Fatalf("read imported state: %v", diagnostics)
	}
	if !imported.SigningSecret.IsNull() {
		t.Fatalf("imported signing secret must be null, got %#v", imported.SigningSecret)
	}
}

func TestWebhookEndpointRejectsAdminCredentialAudience(t *testing.T) {
	managed := NewWebhookEndpointResource().(*WebhookEndpointResource)
	providerData := openaiapi.NewProviderData()
	providerData.SetClient("admin", &openaiapi.APIClient{})
	var response frameworkresource.ConfigureResponse
	managed.Configure(
		context.Background(),
		frameworkresource.ConfigureRequest{ProviderData: providerData},
		&response,
	)
	if !response.Diagnostics.HasError() {
		t.Fatal("webhook endpoint resource accepted only an admin credential")
	}
	if managed.client != nil {
		t.Fatal("webhook endpoint resource received the admin API client")
	}
}

func TestWebhookEndpointSigningSecretSchemaIsSensitive(t *testing.T) {
	managed := NewWebhookEndpointResource().(*WebhookEndpointResource)
	state := webhookEndpointSchema(t, managed)
	attribute := state.Schema.GetAttributes()["signing_secret"]
	if !attribute.IsSensitive() {
		t.Fatal("signing_secret is not marked sensitive")
	}
}
