// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectmodelpermissions

import (
	"context"
	"fmt"

	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &ProjectModelPermissionsDataSource{}
var _ datasource.DataSourceWithConfigure = &ProjectModelPermissionsDataSource{}

type ProjectModelPermissionsDataSource struct {
	client *openaiapi.APIClient
}

type ProjectModelPermissionsDataSourceModel struct {
	ProjectID    types.String `tfsdk:"project_id"`
	Object       types.String `tfsdk:"object"`
	Mode         types.String `tfsdk:"mode"`
	ModelIDs     types.List   `tfsdk:"model_ids"`
	ID           types.String `tfsdk:"id"`
	ResponseJSON types.String `tfsdk:"response_json"`
}

func NewProjectModelPermissionsDataSource() datasource.DataSource {
	return &ProjectModelPermissionsDataSource{}
}

func (d *ProjectModelPermissionsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_project_model_permissions"
}

func (d *ProjectModelPermissionsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieve project model permissions.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "project id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"object": schema.StringAttribute{
				MarkdownDescription: "object",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"mode": schema.StringAttribute{
				MarkdownDescription: "mode",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"model_ids": schema.ListAttribute{
				MarkdownDescription: "model ids",
				ElementType:         types.StringType,
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Synthetic data source identifier.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
		},
	}
}

func (d *ProjectModelPermissionsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *ProjectModelPermissionsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectModelPermissionsDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"project_id": data.ProjectID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := d.client.Request(ctx, "GET", "/organization/projects/{project_id}/model_permissions", pathParams, queryParams, nil)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	data.ID = types.StringValue(fmt.Sprintf("openai_project_model_permissions/%s", data.ProjectID.ValueString()))
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"object"}, &data.Object, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"mode"}, &data.Mode, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"model_ids"}, &data.ModelIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
