// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectmodelpermissions_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceProjectModelPermissionsBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

resource "openai_project_model_permissions" "source" {
  project_id = openai_project.source.project_id
  mode = "allow_list"
  model_ids = [%q]
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-model-permissions-{suffix}"),
		acctest.FixtureValue(t, "model_id"),
	)
}

func testAccDataSourceProjectModelPermissionsBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

resource "openai_project_model_permissions" "source" {
  project_id = openai_project.source.project_id
  mode = "allow_list"
  model_ids = [%q]
}

data "openai_project_model_permissions" "lookup" {
  project_id = openai_project.source.project_id
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-model-permissions-{suffix}"),
		acctest.FixtureValue(t, "model_id"),
	)
}

func TestAccDataSourceProjectModelPermissions_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceProjectModelPermissionsBasicConfig1(t),
			},
			{
				Config: testAccDataSourceProjectModelPermissionsBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("data.openai_project_model_permissions.lookup", "project_id", "openai_project.source", "project_id"),
				),
			},
		},
	})
}
