// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectspendalert

import (
	"context"
	"fmt"

	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &ProjectSpendAlertDataSource{}
var _ datasource.DataSourceWithConfigure = &ProjectSpendAlertDataSource{}

type ProjectSpendAlertDataSource struct {
	client *openaiapi.APIClient
}

type ProjectSpendAlertDataSourceModel struct {
	ProjectID                        types.String `tfsdk:"project_id"`
	AlertID                          types.String `tfsdk:"alert_id"`
	ID                               types.String `tfsdk:"id"`
	ThresholdAmount                  types.Int64  `tfsdk:"threshold_amount"`
	Currency                         types.String `tfsdk:"currency"`
	Interval                         types.String `tfsdk:"interval"`
	NotificationChannelType          types.String `tfsdk:"notification_channel_type"`
	NotificationChannelRecipients    types.List   `tfsdk:"notification_channel_recipients"`
	NotificationChannelSubjectPrefix types.String `tfsdk:"notification_channel_subject_prefix"`
	ResponseJSON                     types.String `tfsdk:"response_json"`
}

func NewProjectSpendAlertDataSource() datasource.DataSource {
	return &ProjectSpendAlertDataSource{}
}

func (d *ProjectSpendAlertDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_project_spend_alert"
}

func (d *ProjectSpendAlertDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Look up a project spend alert by ID.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "project id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"alert_id": schema.StringAttribute{
				MarkdownDescription: "alert id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "id",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"threshold_amount": schema.Int64Attribute{
				MarkdownDescription: "threshold amount",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"currency": schema.StringAttribute{
				MarkdownDescription: "currency",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"interval": schema.StringAttribute{
				MarkdownDescription: "interval",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"notification_channel_type": schema.StringAttribute{
				MarkdownDescription: "notification channel type",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"notification_channel_recipients": schema.ListAttribute{
				MarkdownDescription: "notification channel recipients",
				ElementType:         types.StringType,
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"notification_channel_subject_prefix": schema.StringAttribute{
				MarkdownDescription: "notification channel subject prefix",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
		},
	}
}

func (d *ProjectSpendAlertDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *ProjectSpendAlertDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectSpendAlertDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"project_id": data.ProjectID.ValueString(),
	}
	queryParams := map[string]string{
		"limit": "100",
	}
	responseData, err := d.client.PaginatedRequest(ctx, "GET", "/organization/projects/{project_id}/spend_alerts", pathParams, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	selectedResponseData, found, err := openaiapi.ResponseObjectByField(responseData, "data", "id", data.AlertID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("OpenAI API response did not contain the requested item", "The list response did not include an item matching the configured identifier.")
		return
	}
	responseData = selectedResponseData
	data.ID = types.StringValue(fmt.Sprintf("openai_project_spend_alert/%s/%s", data.ProjectID.ValueString(), data.AlertID.ValueString()))
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"threshold_amount"}, &data.ThresholdAmount, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"currency"}, &data.Currency, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"interval"}, &data.Interval, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"notification_channel.type"}, &data.NotificationChannelType, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"notification_channel.recipients"}, &data.NotificationChannelRecipients, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"notification_channel.subject_prefix"}, &data.NotificationChannelSubjectPrefix, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
