// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectspendalert_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceProjectSpendAlertsBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

resource "openai_project_spend_alert" "source" {
  project_id = openai_project.source.project_id
  threshold_amount = 100
  currency = "USD"
  interval = "month"
  notification_channel_type = "email"
  notification_channel_recipients = [%q]
  notification_channel_subject_prefix = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-project-spend-alerts-{suffix}"),
		acctest.FixtureValue(t, "notification_email"),
		acctest.TemplateValue(t, "tf-acc-ds-project-alerts-{suffix}"),
	)
}

func testAccDataSourceProjectSpendAlertsBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

resource "openai_project_spend_alert" "source" {
  project_id = openai_project.source.project_id
  threshold_amount = 100
  currency = "USD"
  interval = "month"
  notification_channel_type = "email"
  notification_channel_recipients = [%q]
  notification_channel_subject_prefix = %q
}

data "openai_project_spend_alerts" "lookup" {
  project_id = openai_project.source.project_id
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-project-spend-alerts-{suffix}"),
		acctest.FixtureValue(t, "notification_email"),
		acctest.TemplateValue(t, "tf-acc-ds-project-alerts-{suffix}"),
	)
}

func TestAccDataSourceProjectSpendAlerts_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceProjectSpendAlertsBasicConfig1(t),
			},
			{
				Config: testAccDataSourceProjectSpendAlertsBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("data.openai_project_spend_alerts.lookup", "project_id", "openai_project.source", "project_id"),
				),
			},
		},
	})
}
