// Code generated by generate-terraform-provider. DO NOT EDIT.

package projecthostedtoolpermissions_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceProjectHostedToolPermissionsBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-hosted-tools-{suffix}"),
	)
}

func testAccDataSourceProjectHostedToolPermissionsBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "source" {
  name = %q
}

data "openai_project_hosted_tool_permissions" "lookup" {
  project_id = openai_project.source.project_id
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-hosted-tools-{suffix}"),
	)
}

func TestAccDataSourceProjectHostedToolPermissions_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceProjectHostedToolPermissionsBasicConfig1(t),
			},
			{
				Config: testAccDataSourceProjectHostedToolPermissionsBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("data.openai_project_hosted_tool_permissions.lookup", "project_id", "openai_project.source", "project_id"),
				),
			},
		},
	})
}
