// Code generated by generate-terraform-provider. DO NOT EDIT.

package mcptunnel

import (
	"context"
	"fmt"

	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &McpTunnelDataSource{}
var _ datasource.DataSourceWithConfigure = &McpTunnelDataSource{}

type McpTunnelDataSource struct {
	client *openaiapi.APIClient
}

type McpTunnelDataSourceModel struct {
	ID              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	Description     types.String `tfsdk:"description"`
	Creator         types.String `tfsdk:"creator"`
	OrganizationIDs types.List   `tfsdk:"organization_ids"`
	WorkspaceIDs    types.List   `tfsdk:"workspace_ids"`
	TenantIDs       types.List   `tfsdk:"tenant_ids"`
}

func NewMcpTunnelDataSource() datasource.DataSource {
	return &McpTunnelDataSource{}
}

func (d *McpTunnelDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_mcp_tunnel"
}

func (d *McpTunnelDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieve an MCP tunnel registration by ID using an organization admin API key.\n\nAuthentication: Set the admin_api_key provider attribute or OPENAI_ADMIN_KEY environment variable for the admin API audience.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Tunnel identifier.",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "name",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "description",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"creator": schema.StringAttribute{
				MarkdownDescription: "creator",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"organization_ids": schema.ListAttribute{
				MarkdownDescription: "organization ids",
				ElementType:         types.StringType,
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"workspace_ids": schema.ListAttribute{
				MarkdownDescription: "workspace ids",
				ElementType:         types.StringType,
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"tenant_ids": schema.ListAttribute{
				MarkdownDescription: "tenant ids",
				ElementType:         types.StringType,
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
		},
	}
}

func (d *McpTunnelDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	providerData, ok := req.ProviderData.(*openaiapi.ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.ProviderData, got: %T", req.ProviderData))
		return
	}
	client, ok := providerData.Client("admin")
	if !ok {
		resp.Diagnostics.AddError(
			"Missing OpenAI credential for admin API",
			"Set the admin_api_key provider attribute or OPENAI_ADMIN_KEY environment variable for the admin API audience before using openai_mcp_tunnel. Credentials are not reused across API audiences.",
		)
		return
	}
	d.client = client
}

func (d *McpTunnelDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data McpTunnelDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"tunnel_id": data.ID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := d.client.Request(ctx, "GET", "/tunnels/{tunnel_id}", pathParams, queryParams, nil)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"description"}, &data.Description, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"creator"}, &data.Creator, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"organization_ids"}, &data.OrganizationIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"workspace_ids"}, &data.WorkspaceIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"tenant_ids"}, &data.TenantIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
