// Code generated by generate-terraform-provider. DO NOT EDIT.

package mcptunnel_test

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"reflect"
	"regexp"
	"sort"
	"sync"
	"sync/atomic"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	frameworkresource "github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	openai "github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
	provider "github.com/openai/terraform-provider-openai/internal/provider"
	"github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

const tunnelTestID = "tunnel_00000000000000000000000000000001"
const tunnelTestAdminKey = "sk-admin-synthetic-mcp-tunnel-test"

type tunnelServerState struct {
	mu          sync.Mutex
	exists      bool
	name        string
	description string
	creates     int
	updates     int
	reads       int
	deletes     int
	unexpected  string
}

func newTunnelServer(t *testing.T) (*httptest.Server, *tunnelServerState) {
	t.Helper()
	state := &tunnelServerState{}
	server := httptest.NewServer(http.HandlerFunc(state.handle))
	t.Cleanup(server.Close)
	return server, state
}

func writeTunnelError(w http.ResponseWriter, status int, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]any{
		"error": map[string]any{
			"message": message,
			"type":    "invalid_request_error",
			"param":   nil,
			"code":    nil,
		},
	})
}

func (s *tunnelServerState) handle(w http.ResponseWriter, req *http.Request) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if req.Header.Get("Authorization") != "Bearer "+tunnelTestAdminKey {
		s.unexpected = "missing synthetic admin authorization"
		writeTunnelError(w, http.StatusUnauthorized, s.unexpected)
		return
	}
	if req.URL.RawQuery != "" || (req.URL.Path != "/v1/tunnels" && req.URL.Path != "/v1/tunnels/"+tunnelTestID) {
		s.unexpected = fmt.Sprintf("unexpected API route: %s %s", req.Method, req.URL.Path)
		writeTunnelError(w, http.StatusNotFound, "Invalid URL")
		return
	}

	switch {
	case req.Method == http.MethodPost:
		var body map[string]any
		if err := json.NewDecoder(req.Body).Decode(&body); err != nil {
			s.unexpected = "invalid request body"
			writeTunnelError(w, http.StatusBadRequest, s.unexpected)
			return
		}
		name, hasName := body["name"].(string)
		description, hasDescription := body["description"].(string)
		if len(body) != 2 || !hasName || !hasDescription {
			s.unexpected = "mutation must contain only name and description"
			writeTunnelError(w, http.StatusBadRequest, s.unexpected)
			return
		}
		if req.URL.Path == "/v1/tunnels" {
			s.creates++
			s.exists = true
		} else {
			if !s.exists {
				writeTunnelError(w, http.StatusNotFound, "Tunnel not found")
				return
			}
			s.updates++
		}
		s.name, s.description = name, description
		s.writeTunnel(w)
	case req.Method == http.MethodGet && req.URL.Path == "/v1/tunnels/"+tunnelTestID:
		s.reads++
		if !s.exists {
			writeTunnelError(w, http.StatusNotFound, "Tunnel not found")
			return
		}
		s.writeTunnel(w)
	case req.Method == http.MethodDelete && req.URL.Path == "/v1/tunnels/"+tunnelTestID:
		s.deletes++
		if !s.exists {
			writeTunnelError(w, http.StatusNotFound, "Tunnel not found")
			return
		}
		s.writeTunnel(w)
		s.exists = false
	default:
		s.unexpected = fmt.Sprintf("unexpected API method: %s", req.Method)
		writeTunnelError(w, http.StatusMethodNotAllowed, s.unexpected)
	}
}

func (s *tunnelServerState) writeTunnel(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]any{
		"id":               tunnelTestID,
		"name":             s.name,
		"description":      s.description,
		"creator":          "user_synthetic",
		"tenant_ids":       []string{},
		"workspace_ids":    []string{"workspace_synthetic"},
		"organization_ids": []string{"org_synthetic"},
		"private_connectivity": map[string]any{
			"target": "https://private.example.invalid/mcp",
		},
	})
}

func tunnelProviderFactories() map[string]func() (tfprotov6.ProviderServer, error) {
	return map[string]func() (tfprotov6.ProviderServer, error){
		"openai": providerserver.NewProtocol6WithError(provider.New("test")()),
	}
}

func tunnelConfig(baseURL, name, description string) string {
	return fmt.Sprintf(`
provider "openai" {
  admin_api_key = %q
  base_url     = %q
}

resource "openai_mcp_tunnel" "test" {
  name        = %q
  description = %q
}

data "openai_mcp_tunnel" "lookup" {
  id = openai_mcp_tunnel.test.id
}
`, tunnelTestAdminKey, baseURL+"/v1", name, description)
}

func TestMCPTunnelProtocolLifecycleAndDataSource(t *testing.T) {
	server, state := newTunnelServer(t)
	resource.UnitTest(t, resource.TestCase{
		ProtoV6ProviderFactories: tunnelProviderFactories(),
		Steps: []resource.TestStep{
			{
				Config: tunnelConfig(server.URL, "terraform-test", "Original description"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "id", tunnelTestID),
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "name", "terraform-test"),
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "description", "Original description"),
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "creator", "user_synthetic"),
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "tenant_ids.#", "0"),
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "workspace_ids.0", "workspace_synthetic"),
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "organization_ids.0", "org_synthetic"),
					resource.TestCheckResourceAttr("data.openai_mcp_tunnel.lookup", "name", "terraform-test"),
					resource.TestCheckResourceAttr("data.openai_mcp_tunnel.lookup", "id", tunnelTestID),
					resource.TestCheckNoResourceAttr("data.openai_mcp_tunnel.lookup", "response_json"),
				),
			},
			{
				Config: tunnelConfig(server.URL, "renamed", ""),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "id", tunnelTestID),
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "name", "renamed"),
					resource.TestCheckResourceAttr("openai_mcp_tunnel.test", "description", ""),
					resource.TestCheckResourceAttr("data.openai_mcp_tunnel.lookup", "description", ""),
				),
			},
			{
				ResourceName:      "openai_mcp_tunnel.test",
				ImportState:       true,
				ImportStateId:     tunnelTestID,
				ImportStateVerify: true,
			},
		},
	})
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.unexpected != "" {
		t.Fatal(state.unexpected)
	}
	if state.creates != 1 || state.updates != 1 || state.deletes != 1 || state.reads == 0 || state.exists {
		t.Fatalf("unexpected lifecycle: create=%d update=%d read=%d delete=%d exists=%t",
			state.creates, state.updates, state.reads, state.deletes, state.exists)
	}
}

func newTunnelResource(t *testing.T) frameworkresource.Resource {
	t.Helper()
	ctx := context.Background()
	for _, factory := range provider.New("test")().Resources(ctx) {
		managed := factory()
		var metadata frameworkresource.MetadataResponse
		managed.Metadata(ctx, frameworkresource.MetadataRequest{ProviderTypeName: "openai"}, &metadata)
		if metadata.TypeName == "openai_mcp_tunnel" {
			return managed
		}
	}
	t.Fatal("openai_mcp_tunnel is not registered")
	return nil
}

type tunnelTestModel struct {
	ID              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	Description     types.String `tfsdk:"description"`
	Creator         types.String `tfsdk:"creator"`
	TenantIDs       types.List   `tfsdk:"tenant_ids"`
	WorkspaceIDs    types.List   `tfsdk:"workspace_ids"`
	OrganizationIDs types.List   `tfsdk:"organization_ids"`
}

func tunnelResourceAndState(t *testing.T, baseURL string) (frameworkresource.Resource, tfsdk.State) {
	t.Helper()
	ctx := context.Background()
	managed := newTunnelResource(t)
	var configured frameworkresource.ConfigureResponse
	managed.(frameworkresource.ResourceWithConfigure).Configure(ctx, frameworkresource.ConfigureRequest{
		ProviderData: &openaiapi.APIClient{
			Client: openai.NewClient(option.WithAPIKey(tunnelTestAdminKey), option.WithBaseURL(baseURL+"/v1")),
		},
	}, &configured)
	if configured.Diagnostics.HasError() {
		t.Fatalf("configure tunnel: %v", configured.Diagnostics)
	}
	var schema frameworkresource.SchemaResponse
	managed.Schema(ctx, frameworkresource.SchemaRequest{}, &schema)
	state := tfsdk.State{Schema: schema.Schema}
	model := tunnelTestModel{
		ID: types.StringValue(tunnelTestID), Name: types.StringValue("existing"),
		Description: types.StringValue("existing description"), Creator: types.StringValue("user_synthetic"),
		TenantIDs: types.ListNull(types.StringType), WorkspaceIDs: types.ListNull(types.StringType),
		OrganizationIDs: types.ListNull(types.StringType),
	}
	if diagnostics := state.Set(ctx, &model); diagnostics.HasError() {
		t.Fatalf("initialize tunnel state: %v", diagnostics)
	}
	return managed, state
}

func TestMCPTunnelNotFoundDistinguishesMissingTunnelFromUnavailableRoute(t *testing.T) {
	for _, method := range []string{http.MethodGet, http.MethodDelete} {
		for _, test := range []struct {
			name    string
			status  int
			message string
			missing bool
		}{
			{name: "deleted tunnel", status: http.StatusNotFound, message: "Tunnel not found", missing: true},
			{name: "route unavailable", status: http.StatusNotFound, message: "Invalid URL"},
			{name: "unauthorized", status: http.StatusUnauthorized, message: "Invalid API key"},
		} {
			t.Run(method+"/"+test.name, func(t *testing.T) {
				server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
					if req.Method != method || req.URL.Path != "/v1/tunnels/"+tunnelTestID {
						t.Errorf("unexpected request: %s %s", req.Method, req.URL.Path)
					}
					writeTunnelError(w, test.status, test.message)
				}))
				t.Cleanup(server.Close)
				managed, state := tunnelResourceAndState(t, server.URL)
				if method == http.MethodGet {
					response := &frameworkresource.ReadResponse{State: state}
					managed.Read(context.Background(), frameworkresource.ReadRequest{State: state}, response)
					if response.Diagnostics.HasError() == test.missing || response.State.Raw.IsNull() != test.missing {
						t.Fatalf("read missing=%t: null state=%t diagnostics=%v", test.missing, response.State.Raw.IsNull(), response.Diagnostics)
					}
				} else {
					response := &frameworkresource.DeleteResponse{State: state}
					managed.Delete(context.Background(), frameworkresource.DeleteRequest{State: state}, response)
					if response.Diagnostics.HasError() == test.missing || response.State.Raw.IsNull() != test.missing {
						t.Fatalf("delete missing=%t: null state=%t diagnostics=%v", test.missing, response.State.Raw.IsNull(), response.Diagnostics)
					}
				}
			})
		}
	}
}

func TestMCPTunnelRejectsInvalidImportIdentifiers(t *testing.T) {
	for _, id := range []string{"", " ", ".", "..", "../other", "one/two"} {
		t.Run(fmt.Sprintf("%q", id), func(t *testing.T) {
			managed := newTunnelResource(t)
			var response frameworkresource.ImportStateResponse
			managed.(frameworkresource.ResourceWithImportState).ImportState(context.Background(), frameworkresource.ImportStateRequest{ID: id}, &response)
			if !response.Diagnostics.HasError() {
				t.Fatal("unsafe import identifier accepted")
			}
		})
	}
}

func TestMCPTunnelCreateDoesNotRetryAmbiguousFailure(t *testing.T) {
	var requests atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		requests.Add(1)
		if req.Method != http.MethodPost || req.URL.Path != "/v1/tunnels" {
			t.Errorf("unexpected request: %s %s", req.Method, req.URL.Path)
		}
		// An upstream error can occur after allocation. Retrying would create an
		// additional tunnel because this API has no idempotency key contract.
		writeTunnelError(w, http.StatusInternalServerError, "Synthetic upstream failure")
	}))
	t.Cleanup(server.Close)
	managed, state := tunnelResourceAndState(t, server.URL)
	plan := tfsdk.Plan{Schema: state.Schema}
	model := tunnelTestModel{
		ID: types.StringUnknown(), Name: types.StringValue("new tunnel"),
		Description: types.StringValue(""), Creator: types.StringUnknown(),
		TenantIDs: types.ListUnknown(types.StringType), WorkspaceIDs: types.ListUnknown(types.StringType),
		OrganizationIDs: types.ListUnknown(types.StringType),
	}
	if diagnostics := plan.Set(context.Background(), &model); diagnostics.HasError() {
		t.Fatalf("initialize tunnel plan: %v", diagnostics)
	}
	response := &frameworkresource.CreateResponse{State: tfsdk.State{Schema: state.Schema}}
	managed.Create(context.Background(), frameworkresource.CreateRequest{Plan: plan}, response)
	if !response.Diagnostics.HasError() {
		t.Fatal("ambiguous create failure must be reported")
	}
	if got := requests.Load(); got != 1 {
		t.Fatalf("non-idempotent create was attempted %d times, want exactly once", got)
	}
}

func TestMCPTunnelEmptyNameFailsBeforeAnyAPICall(t *testing.T) {
	server, state := newTunnelServer(t)
	resource.UnitTest(t, resource.TestCase{
		ProtoV6ProviderFactories: tunnelProviderFactories(),
		Steps: []resource.TestStep{{
			Config:      tunnelConfig(server.URL, "", ""),
			ExpectError: regexp.MustCompile("(?i)at least 1"),
		}},
	})
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.creates+state.updates+state.reads+state.deletes != 0 || state.unexpected != "" {
		t.Fatal("invalid configuration reached the API")
	}
}

func TestMCPTunnelSchemaContainsOnlyMetadata(t *testing.T) {
	managed := newTunnelResource(t)
	var response frameworkresource.SchemaResponse
	managed.Schema(context.Background(), frameworkresource.SchemaRequest{}, &response)
	var names []string
	for name, attribute := range response.Schema.Attributes {
		names = append(names, name)
		if name != "name" && name != "description" && (!attribute.IsComputed() || attribute.IsOptional() || attribute.IsRequired()) {
			t.Errorf("attribute %q must be computed only", name)
		}
	}
	sort.Strings(names)
	want := []string{"creator", "description", "id", "name", "organization_ids", "tenant_ids", "workspace_ids"}
	if !reflect.DeepEqual(names, want) {
		t.Fatalf("tunnel schema must contain only metadata, got %v", names)
	}
}

func TestMCPTunnelDataSourceSchemaContainsOnlyMetadata(t *testing.T) {
	ctx := context.Background()
	for _, factory := range provider.New("test")().DataSources(ctx) {
		lookup := factory()
		var metadata datasource.MetadataResponse
		lookup.Metadata(ctx, datasource.MetadataRequest{ProviderTypeName: "openai"}, &metadata)
		if metadata.TypeName != "openai_mcp_tunnel" {
			continue
		}
		var response datasource.SchemaResponse
		lookup.Schema(ctx, datasource.SchemaRequest{}, &response)
		var names []string
		for name, attribute := range response.Schema.Attributes {
			names = append(names, name)
			if name != "id" && (!attribute.IsComputed() || attribute.IsOptional() || attribute.IsRequired()) {
				t.Errorf("attribute %q must be computed only", name)
			}
		}
		sort.Strings(names)
		want := []string{"creator", "description", "id", "name", "organization_ids", "tenant_ids", "workspace_ids"}
		if !reflect.DeepEqual(names, want) {
			t.Fatalf("data source schema must contain only metadata, got %v", names)
		}
		return
	}
	t.Fatal("openai_mcp_tunnel data source is not registered")
}
