// Code generated by generate-terraform-provider. DO NOT EDIT.

package mcptunnel

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ resource.Resource = &McpTunnelResource{}
var _ resource.ResourceWithConfigure = &McpTunnelResource{}
var _ resource.ResourceWithImportState = &McpTunnelResource{}

type McpTunnelResource struct {
	client *openaiapi.APIClient
}

type McpTunnelResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	Description     types.String `tfsdk:"description"`
	Creator         types.String `tfsdk:"creator"`
	OrganizationIDs types.List   `tfsdk:"organization_ids"`
	WorkspaceIDs    types.List   `tfsdk:"workspace_ids"`
	TenantIDs       types.List   `tfsdk:"tenant_ids"`
}

func NewMcpTunnelResource() resource.Resource {
	return &McpTunnelResource{}
}

func (r *McpTunnelResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "openai_mcp_tunnel"
}

func (r *McpTunnelResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manage an MCP tunnel registration. Requires access to the Tunnels API and an organization admin API key. Manages the name and description; associated organizations, workspaces, and tenants are read-only. Creation associates the authenticated organization or workspace. Deploy and authenticate the tunnel client separately; this resource does not issue credentials.\n\nAuthentication: Set the admin_api_key provider attribute or OPENAI_ADMIN_KEY environment variable for the admin API audience.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Tunnel identifier.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Human-readable tunnel name.",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Tunnel description. Use an empty string to clear it.",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
			},
			"creator": schema.StringAttribute{
				MarkdownDescription: "Identifier of the principal that created the tunnel.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organization_ids": schema.ListAttribute{
				MarkdownDescription: "Organization identifiers associated with the tunnel.",
				ElementType:         types.StringType,
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"workspace_ids": schema.ListAttribute{
				MarkdownDescription: "Workspace identifiers associated with the tunnel.",
				ElementType:         types.StringType,
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"tenant_ids": schema.ListAttribute{
				MarkdownDescription: "Tenant identifiers associated with the tunnel.",
				ElementType:         types.StringType,
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
		},
	}
}

func (r *McpTunnelResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	providerData, ok := req.ProviderData.(*openaiapi.ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *openaiapi.ProviderData, got: %T", req.ProviderData))
		return
	}
	client, ok := providerData.Client("admin")
	if !ok {
		resp.Diagnostics.AddError(
			"Missing OpenAI credential for admin API",
			"Set the admin_api_key provider attribute or OPENAI_ADMIN_KEY environment variable for the admin API audience before using openai_mcp_tunnel. Credentials are not reused across API audiences.",
		)
		return
	}
	r.client = client
}

func (r *McpTunnelResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data McpTunnelResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{}
	queryParams := map[string]string{}
	body := map[string]any{}
	openaiapi.AddStringBodyField(body, "name", data.Name)
	openaiapi.AddStringBodyField(body, "description", data.Description)
	responseData, err := r.client.RequestWithoutRetries(ctx, "POST", "/tunnels", pathParams, queryParams, body)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"description"}, &data.Description, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"creator"}, &data.Creator, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"organization_ids"}, &data.OrganizationIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"workspace_ids"}, &data.WorkspaceIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"tenant_ids"}, &data.TenantIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *McpTunnelResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data McpTunnelResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"tunnel_id": data.ID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.Request(ctx, "GET", "/tunnels/{tunnel_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFoundMessage(err, "Tunnel not found") {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"description"}, &data.Description, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"creator"}, &data.Creator, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"organization_ids"}, &data.OrganizationIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"workspace_ids"}, &data.WorkspaceIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"tenant_ids"}, &data.TenantIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *McpTunnelResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data McpTunnelResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"tunnel_id": data.ID.ValueString(),
	}
	queryParams := map[string]string{}
	body := map[string]any{}
	openaiapi.AddStringBodyField(body, "name", data.Name)
	openaiapi.AddStringBodyField(body, "description", data.Description)
	responseData, err := r.client.RequestWithoutRetries(ctx, "POST", "/tunnels/{tunnel_id}", pathParams, queryParams, body)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"description"}, &data.Description, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"creator"}, &data.Creator, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"organization_ids"}, &data.OrganizationIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"workspace_ids"}, &data.WorkspaceIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringListResponseField(responseData, []string{"tenant_ids"}, &data.TenantIDs, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *McpTunnelResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data McpTunnelResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"tunnel_id": data.ID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.RequestWithoutRetries(ctx, "DELETE", "/tunnels/{tunnel_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFoundMessage(err, "Tunnel not found") {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	_ = responseData
	resp.State.RemoveResource(ctx)
}

func (r *McpTunnelResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 1 {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("Expected import ID format %q.", "{id}"))
		return
	}
	if err := openaiapi.ValidatePathParameter("id", parts[0]); err != nil {
		resp.Diagnostics.AddError("Invalid import ID", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), parts[0])...)
}
