// Code generated by generate-terraform-provider. DO NOT EDIT.

package openaiapi

import (
	"bytes"
	"container/list"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	openai "github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
)

type APIClient struct {
	AdminAPIKey        string
	BaseURL            string
	Organization       string
	Project            string
	ProviderVersion    string
	Client             openai.Client
	responseCache      responseCache
	retryAfterCooldown retryAfterCooldown

	// The following fields are test hooks. Provider operation uses the bounded
	// defaults below.
	requestTimeout            time.Duration
	requestAttemptTimeout     time.Duration
	slowRequestThreshold      time.Duration
	maxResponseBytes          int64
	maxPaginatedResponseBytes int64
	requestMaxRetries         *int
	requestObserver           func(requestObservation)
	paginationObserver        func(paginationObservation)
	responseCacheObserver     func(responseCacheObservation)
}

const maxPaginatedPages = 1000

// Keep a production-sized project working set so Terraform's interleaved
// refresh order can reuse paginated responses while retaining a fixed bound.
const defaultResponseCacheMaxEntries = 2048

const (
	responseCacheOutcomeHit       = "hit"
	responseCacheOutcomeMiss      = "miss"
	responseCacheOutcomeCoalesced = "coalesced"
	responseCacheOutcomeCanceled  = "canceled"
	responseCacheOutcomeError     = "error"
)

type responseCacheObservation struct {
	CacheName    string
	Outcome      string
	Duration     time.Duration
	WaitDuration time.Duration
	LoadDuration time.Duration
}

type responseCacheKey struct {
	name   string
	values string
}

type responseCacheEntry struct {
	key         responseCacheKey
	ready       chan struct{}
	invalidated bool
	evicted     bool
	response    map[string]any
	err         error
	loaderEnded bool
	lruElement  *list.Element
}

type responseCache struct {
	mu         sync.Mutex
	entries    map[responseCacheKey]*responseCacheEntry
	lru        list.List
	maxEntries int

	// testHookAfterLoadPublished makes the narrow publication/invalidation
	// ordering deterministic in tests. It is nil in provider operation.
	testHookAfterLoadPublished func(responseCacheKey)
}

func buildResponseCacheKey(name string, pathParams map[string]string, keyFields []string) (responseCacheKey, error) {
	if strings.TrimSpace(name) == "" {
		return responseCacheKey{}, fmt.Errorf("response cache name must not be empty")
	}

	var values strings.Builder
	for _, field := range keyFields {
		value, ok := pathParams[field]
		if !ok {
			return responseCacheKey{}, fmt.Errorf("response cache %q is missing path parameter %q", name, field)
		}
		_, _ = fmt.Fprintf(&values, "%d:%s=%d:%s;", len(field), field, len(value), value)
	}
	return responseCacheKey{name: name, values: values.String()}, nil
}

func (c *responseCache) acquire(key responseCacheKey) (*responseCacheEntry, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.entries == nil {
		c.entries = make(map[responseCacheKey]*responseCacheEntry)
	}
	if entry, ok := c.entries[key]; ok {
		if entry.lruElement != nil {
			c.lru.MoveToFront(entry.lruElement)
		}
		return entry, true
	}

	entry := &responseCacheEntry{
		key:   key,
		ready: make(chan struct{}),
	}
	c.entries[key] = entry
	return entry, false
}

func (c *responseCache) finishLoad(entry *responseCacheEntry, response map[string]any, err error, loaderEnded bool) {
	c.mu.Lock()
	defer c.mu.Unlock()

	entry.response = response
	entry.err = err
	entry.loaderEnded = loaderEnded
	if current, ok := c.entries[entry.key]; ok && current == entry {
		if err != nil || entry.invalidated {
			delete(c.entries, entry.key)
		} else {
			entry.lruElement = c.lru.PushFront(entry)
			c.evictLocked()
		}
	}
	close(entry.ready)
}

func (c *responseCache) evictLocked() {
	maxEntries := c.maxEntries
	if maxEntries <= 0 {
		maxEntries = defaultResponseCacheMaxEntries
	}
	for c.lru.Len() > maxEntries {
		oldest := c.lru.Back()
		entry := oldest.Value.(*responseCacheEntry)
		c.lru.Remove(oldest)
		entry.lruElement = nil
		entry.evicted = true
		if current, ok := c.entries[entry.key]; ok && current == entry {
			delete(c.entries, entry.key)
		}
	}
}

func (c *responseCache) result(ctx context.Context, entry *responseCacheEntry, retryLoaderCancellation bool) (map[string]any, error, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()

	if entry.invalidated || entry.evicted || (retryLoaderCancellation && ctx.Err() == nil && entry.loaderEnded) {
		return nil, nil, true
	}
	if entry.lruElement != nil {
		c.lru.MoveToFront(entry.lruElement)
	}
	return entry.response, entry.err, false
}

func (c *responseCache) get(
	ctx context.Context,
	key responseCacheKey,
	load func(context.Context) (map[string]any, error),
	observe func(responseCacheObservation),
) (response map[string]any, err error) {
	startedAt := time.Now()
	observation := responseCacheObservation{CacheName: key.name}
	loadedByCaller := false
	waitedForLoader := false
	defer func() {
		observation.Duration = time.Since(startedAt)
		switch {
		case errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded):
			observation.Outcome = responseCacheOutcomeCanceled
		case err != nil:
			observation.Outcome = responseCacheOutcomeError
		case loadedByCaller:
			observation.Outcome = responseCacheOutcomeMiss
		case waitedForLoader:
			observation.Outcome = responseCacheOutcomeCoalesced
		default:
			observation.Outcome = responseCacheOutcomeHit
		}
		if observe != nil {
			observe(observation)
		}
	}()

	for {
		if err := ctx.Err(); err != nil {
			return nil, err
		}

		entry, loaded := c.acquire(key)
		if !loaded {
			loadedByCaller = true
			loadStartedAt := time.Now()
			response, err := load(ctx)
			observation.LoadDuration += time.Since(loadStartedAt)
			loaderEnded := ctx.Err() != nil && errors.Is(err, ctx.Err())
			c.finishLoad(entry, response, err, loaderEnded)
			if c.testHookAfterLoadPublished != nil {
				c.testHookAfterLoadPublished(key)
			}
		} else {
			select {
			case <-entry.ready:
			default:
				waitedForLoader = true
				waitStartedAt := time.Now()
				select {
				case <-ctx.Done():
					observation.WaitDuration += time.Since(waitStartedAt)
					return nil, ctx.Err()
				case <-entry.ready:
					observation.WaitDuration += time.Since(waitStartedAt)
				}
			}
		}

		response, err, retry := c.result(ctx, entry, loaded)
		if retry {
			continue
		}
		return response, err
	}
}

func (c *APIClient) recordResponseCacheObservation(ctx context.Context, observation responseCacheObservation) {
	fields := map[string]any{
		"cache_name":       observation.CacheName,
		"outcome":          observation.Outcome,
		"duration_ms":      observation.Duration.Milliseconds(),
		"wait_duration_ms": observation.WaitDuration.Milliseconds(),
		"load_duration_ms": observation.LoadDuration.Milliseconds(),
	}
	logContext := openAIClientLogContext(ctx)
	if observation.Duration >= c.effectiveSlowRequestThreshold() {
		tflog.SubsystemWarn(logContext, openAIClientLogSubsystem, "OpenAI API response cache operation completed after delay", fields)
	} else {
		tflog.SubsystemDebug(logContext, openAIClientLogSubsystem, "OpenAI API response cache operation completed", fields)
	}
	if c.responseCacheObserver != nil {
		c.responseCacheObserver(observation)
	}
}

func (c *responseCache) invalidate(key responseCacheKey) {
	c.mu.Lock()
	defer c.mu.Unlock()

	entry, ok := c.entries[key]
	if !ok {
		return
	}
	delete(c.entries, key)
	if entry.lruElement != nil {
		c.lru.Remove(entry.lruElement)
		entry.lruElement = nil
	}
	entry.invalidated = true
}

// CachedRequest coalesces concurrent cache misses and retains one successful
// response without following pagination. Callers must treat the response as immutable.
func (c *APIClient) CachedRequest(ctx context.Context, cacheName string, cacheKeyFields []string, method string, path string, pathParams map[string]string, queryParams map[string]string) (map[string]any, error) {
	ctx = openAIClientLogContext(ctx)
	if method != http.MethodGet {
		return nil, fmt.Errorf("cached requests require GET, got %q", method)
	}
	key, err := buildResponseCacheKey(cacheName, pathParams, cacheKeyFields)
	if err != nil {
		return nil, err
	}
	return c.responseCache.get(ctx, key, func(loadCtx context.Context) (map[string]any, error) {
		return c.Request(loadCtx, method, path, pathParams, queryParams, nil)
	}, func(observation responseCacheObservation) {
		c.recordResponseCacheObservation(ctx, observation)
	})
}

// CachedPaginatedRequest coalesces concurrent cache misses and retains a bounded
// set of recently used successful responses. An empty cacheKeyFields slice creates
// one entry per API client and cache name. Callers must treat the response as immutable.
func (c *APIClient) CachedPaginatedRequest(ctx context.Context, cacheName string, cacheKeyFields []string, method string, path string, pathParams map[string]string, queryParams map[string]string) (map[string]any, error) {
	ctx = openAIClientLogContext(ctx)
	if method != http.MethodGet {
		return nil, fmt.Errorf("cached paginated requests require GET, got %q", method)
	}
	key, err := buildResponseCacheKey(cacheName, pathParams, cacheKeyFields)
	if err != nil {
		return nil, err
	}
	return c.responseCache.get(ctx, key, func(loadCtx context.Context) (map[string]any, error) {
		return c.PaginatedRequest(loadCtx, method, path, pathParams, queryParams)
	}, func(observation responseCacheObservation) {
		c.recordResponseCacheObservation(ctx, observation)
	})
}

func (c *APIClient) InvalidateResponseCache(cacheName string, cacheKeyFields []string, pathParams map[string]string) error {
	key, err := buildResponseCacheKey(cacheName, pathParams, cacheKeyFields)
	if err != nil {
		return err
	}
	c.responseCache.invalidate(key)
	return nil
}

const (
	defaultMaxResponseBytes          int64 = 32 << 20
	defaultMaxPaginatedResponseBytes int64 = 256 << 20
)

type paginatedResponseBudgetKey struct{}

type paginatedResponseBudget struct {
	remaining int64
}

type responseBodyLimitError struct {
	scope string
	limit int64
}

func (e *responseBodyLimitError) Error() string {
	return fmt.Sprintf("%s exceeded the %d-byte response size limit", e.scope, e.limit)
}

func (c *APIClient) effectiveMaxResponseBytes() int64 {
	if c.maxResponseBytes > 0 {
		return c.maxResponseBytes
	}
	return defaultMaxResponseBytes
}

func (c *APIClient) effectiveMaxPaginatedResponseBytes() int64 {
	if c.maxPaginatedResponseBytes > 0 {
		return c.maxPaginatedResponseBytes
	}
	return defaultMaxPaginatedResponseBytes
}

func (c *APIClient) readResponseBody(ctx context.Context, response *http.Response) (body []byte, err error) {
	defer func() {
		if closeErr := response.Body.Close(); err == nil && closeErr != nil {
			err = closeErr
		}
	}()

	limit := c.effectiveMaxResponseBytes()
	var budget *paginatedResponseBudget
	scope := "OpenAI API response"
	if response.StatusCode >= http.StatusOK && response.StatusCode < http.StatusMultipleChoices {
		budget, _ = ctx.Value(paginatedResponseBudgetKey{}).(*paginatedResponseBudget)
		if budget != nil && budget.remaining < limit {
			limit = budget.remaining
			scope = "OpenAI API paginated responses"
		}
	}
	if response.ContentLength > limit {
		return nil, &responseBodyLimitError{scope: scope, limit: limit}
	}

	body, err = io.ReadAll(io.LimitReader(response.Body, limit+1))
	if err != nil {
		return nil, err
	}
	if int64(len(body)) > limit {
		return nil, &responseBodyLimitError{scope: scope, limit: limit}
	}
	if budget != nil {
		budget.remaining -= int64(len(body))
	}
	return body, nil
}

func IsNotFound(err error) bool {
	var apiErr *openai.Error
	return errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound
}

func ValidatePathParameter(name string, value string) error {
	if strings.TrimSpace(value) == "" {
		return fmt.Errorf("missing value for path parameter %q", name)
	}
	if value == "." || value == ".." {
		return fmt.Errorf("invalid value for path parameter %q: URL dot segments are not allowed", name)
	}
	return nil
}

func expandAPIPath(path string, params map[string]string) (string, error) {
	expanded := path
	for name, value := range params {
		if err := ValidatePathParameter(name, value); err != nil {
			return "", err
		}
		expanded = strings.ReplaceAll(expanded, "{"+name+"}", url.PathEscape(value))
	}
	if strings.Contains(expanded, "{") || strings.Contains(expanded, "}") {
		return "", fmt.Errorf("unresolved path parameter in %q", expanded)
	}
	if !strings.HasPrefix(expanded, "/") {
		expanded = "/" + expanded
	}
	return expanded, nil
}

func appendQuery(path string, queryParams map[string]string) string {
	if len(queryParams) == 0 {
		return path
	}
	values := url.Values{}
	for name, value := range queryParams {
		if strings.TrimSpace(value) == "" {
			continue
		}
		values.Set(name, value)
	}
	encoded := values.Encode()
	if encoded == "" {
		return path
	}
	separator := "?"
	if strings.Contains(path, "?") {
		separator = "&"
	}
	return path + separator + encoded
}

func copyQueryParams(queryParams map[string]string) map[string]string {
	copy := map[string]string{}
	for name, value := range queryParams {
		copy[name] = value
	}
	return copy
}

const (
	defaultRequestTimeout        = 5 * time.Minute
	defaultRequestAttemptTimeout = 30 * time.Second
	defaultSlowRequestThreshold  = 30 * time.Second
	defaultRequestMaxRetries     = 2
	defaultReadRequestMaxRetries = 4
	requestObservationPending    = "retry_lifecycle_pending"
	requestObservationLifecycle  = "retry_lifecycle_completed"
	requestObservationAttempt    = "attempt_completed"
	requestOutcomePending        = "pending"
	requestOutcomeSuccess        = "success"
	requestOutcomeAPIError       = "api_error"
	requestOutcomeRequestError   = "request_error"
	requestOutcomeCanceled       = "canceled"
	requestOutcomeDeadline       = "deadline_exceeded"
	openAIClientLogSubsystem     = "openai_client"
	openAIClientLogLevelEnv      = "TF_LOG_PROVIDER_OPENAI_CLIENT"
)

type requestObservation struct {
	Phase                string
	Outcome              string
	Method               string
	Path                 string
	Duration             time.Duration
	AttemptDuration      time.Duration
	NonAttemptDuration   time.Duration
	CooldownWaitDuration time.Duration
	AttemptCount         int
	RetryCount           int
	StatusCode           int
	ResponseBytes        int64
	TimedOut             bool
}

type paginationObservation struct {
	Outcome   string
	Method    string
	Path      string
	Duration  time.Duration
	PageCount int
	ItemCount int
}

type openAIClientLogContextKey struct{}

type requestLifecycleState struct {
	attempts                 atomic.Int64
	attemptDurationNano      atomic.Int64
	cooldownWaitDurationNano atomic.Int64
	lastStatusCode           atomic.Int64
	responseBytes            atomic.Int64
	responseBytesUnknown     atomic.Bool
}

type retryAfterCooldown struct {
	mu          sync.Mutex
	until       time.Time
	generation  uint64
	releaseOnce sync.Once
	releaseGate chan struct{}
}

func sanitizeRedirectError(response *http.Response, err error) error {
	if response == nil || err == nil {
		return err
	}
	redirectErr, ok := err.(*url.Error)
	if !ok {
		return err
	}
	redirectURL, parseErr := url.Parse(redirectErr.URL)
	if parseErr != nil {
		return &url.Error{Op: redirectErr.Op, URL: "[redacted]", Err: redirectErr.Err}
	}
	sanitizedURL := (&url.URL{
		Scheme:  redirectURL.Scheme,
		Host:    redirectURL.Host,
		Path:    redirectURL.Path,
		RawPath: redirectURL.RawPath,
	}).String()
	return &url.Error{Op: redirectErr.Op, URL: sanitizedURL, Err: redirectErr.Err}
}

func retryAfterDuration(response *http.Response, now time.Time) (time.Duration, bool) {
	if response == nil || response.StatusCode != http.StatusTooManyRequests {
		return 0, false
	}
	if value := strings.TrimSpace(response.Header.Get("Retry-After-Ms")); value != "" {
		if delay, err := time.ParseDuration(value + "ms"); err == nil && delay > 0 {
			return delay, true
		}
	}
	value := strings.TrimSpace(response.Header.Get("Retry-After"))
	if value == "" {
		return 0, false
	}
	if delay, err := time.ParseDuration(value + "s"); err == nil && delay > 0 {
		return delay, true
	}
	if retryAt, err := http.ParseTime(value); err == nil {
		if delay := retryAt.Sub(now); delay > 0 {
			return delay, true
		}
	}
	return 0, false
}

func (c *retryAfterCooldown) observeResponse(response *http.Response, now time.Time, coordinated bool, generation uint64) {
	delay, ok := retryAfterDuration(response, now)
	c.mu.Lock()
	defer c.mu.Unlock()
	if ok {
		until := now.Add(delay)
		if until.After(c.until) {
			c.until = until
		}
		c.generation++
		return
	}
	if coordinated &&
		response != nil &&
		response.StatusCode != http.StatusTooManyRequests &&
		c.generation == generation {
		c.until = time.Time{}
	}
}

func (c *retryAfterCooldown) acquireDelayedRelease(ctx context.Context) (func(), error) {
	c.releaseOnce.Do(func() {
		c.releaseGate = make(chan struct{}, 1)
		c.releaseGate <- struct{}{}
	})
	if err := ctx.Err(); err != nil {
		return func() {}, err
	}
	select {
	case <-ctx.Done():
		return func() {}, ctx.Err()
	case <-c.releaseGate:
		if err := ctx.Err(); err != nil {
			c.releaseGate <- struct{}{}
			return func() {}, err
		}
		var releaseOnce sync.Once
		return func() {
			releaseOnce.Do(func() {
				c.releaseGate <- struct{}{}
			})
		}, nil
	}
}

func (c *retryAfterCooldown) wait(ctx context.Context) (bool, uint64, func(), error) {
	coordinated := false
	var generation uint64
	for {
		c.mu.Lock()
		until := c.until
		currentGeneration := c.generation
		c.mu.Unlock()
		if until.IsZero() {
			if !coordinated {
				return false, 0, func() {}, nil
			}
		} else {
			coordinated = true
			generation = currentGeneration
			if delay := time.Until(until); delay > 0 {
				timer := time.NewTimer(delay)
				select {
				case <-ctx.Done():
					if !timer.Stop() {
						<-timer.C
					}
					return true, generation, func() {}, ctx.Err()
				case <-timer.C:
				}
				continue
			}
		}

		release, err := c.acquireDelayedRelease(ctx)
		if err != nil {
			return true, generation, func() {}, err
		}
		c.mu.Lock()
		until = c.until
		generation = c.generation
		c.mu.Unlock()
		if !until.IsZero() && time.Until(until) > 0 {
			release()
			continue
		}
		return true, generation, release, nil
	}
}

func (s *requestLifecycleState) beginAttempt() int {
	return int(s.attempts.Add(1) - 1)
}

func (s *requestLifecycleState) recordStatusCode(statusCode int) {
	s.lastStatusCode.Store(int64(statusCode))
}

func (s *requestLifecycleState) recordAttempt(duration time.Duration, responseBytes int64) {
	s.attemptDurationNano.Add(duration.Nanoseconds())
	if responseBytes < 0 {
		s.responseBytesUnknown.Store(true)
		return
	}
	s.responseBytes.Add(responseBytes)
}

func (s *requestLifecycleState) recordCooldownWait(duration time.Duration) {
	s.cooldownWaitDurationNano.Add(duration.Nanoseconds())
}

func (s *requestLifecycleState) snapshot() (int, int, int, time.Duration, time.Duration, int64) {
	attempts := s.attempts.Load()
	retryCount := 0
	if attempts > 0 {
		retryCount = int(attempts - 1)
	}
	responseBytes := s.responseBytes.Load()
	if s.responseBytesUnknown.Load() {
		responseBytes = -1
	}
	return int(attempts),
		retryCount,
		int(s.lastStatusCode.Load()),
		time.Duration(s.attemptDurationNano.Load()),
		time.Duration(s.cooldownWaitDurationNano.Load()),
		responseBytes
}

func openAIClientLogContext(ctx context.Context) context.Context {
	if configured, _ := ctx.Value(openAIClientLogContextKey{}).(bool); configured {
		return ctx
	}
	ctx = tflog.NewSubsystem(
		ctx,
		openAIClientLogSubsystem,
		tflog.WithLevelFromEnv(openAIClientLogLevelEnv),
		tflog.WithRootFields(),
	)
	return context.WithValue(ctx, openAIClientLogContextKey{}, true)
}

func (c *APIClient) effectiveRequestTimeout() time.Duration {
	if c.requestTimeout > 0 {
		return c.requestTimeout
	}
	return defaultRequestTimeout
}

func (c *APIClient) effectiveRequestAttemptTimeout() time.Duration {
	if c.requestAttemptTimeout > 0 {
		return c.requestAttemptTimeout
	}
	return defaultRequestAttemptTimeout
}

func (c *APIClient) effectiveSlowRequestThreshold() time.Duration {
	if c.slowRequestThreshold > 0 {
		return c.slowRequestThreshold
	}
	return defaultSlowRequestThreshold
}

func (c *APIClient) effectiveRequestMaxRetries(method string) int {
	if c.requestMaxRetries != nil {
		return *c.requestMaxRetries
	}
	// Plans are read-heavy, and GET requests are safe to repeat when the API is transiently unavailable.
	if method == http.MethodGet {
		return defaultReadRequestMaxRetries
	}
	return defaultRequestMaxRetries
}

func requestErrorStatusCode(err error) int {
	var apiErr *openai.Error
	if errors.As(err, &apiErr) {
		return apiErr.StatusCode
	}
	return 0
}

func classifyRequestOutcome(err error, contextErr error, statusCode int) string {
	switch {
	case errors.Is(err, context.DeadlineExceeded) || errors.Is(contextErr, context.DeadlineExceeded):
		return requestOutcomeDeadline
	case errors.Is(err, context.Canceled) || errors.Is(contextErr, context.Canceled):
		return requestOutcomeCanceled
	case statusCode >= http.StatusBadRequest:
		return requestOutcomeAPIError
	case err != nil:
		return requestOutcomeRequestError
	default:
		return requestOutcomeSuccess
	}
}

func responseMetadataControlsRetry(response *http.Response) bool {
	if response == nil {
		return false
	}
	if retryPolicy := response.Header.Get("x-should-retry"); retryPolicy == "true" || retryPolicy == "false" {
		return true
	}
	return response.StatusCode == http.StatusRequestTimeout ||
		response.StatusCode == http.StatusConflict ||
		response.StatusCode == http.StatusTooManyRequests ||
		response.StatusCode >= http.StatusInternalServerError
}

func (c *APIClient) requestObservationErrorMessage(observation requestObservation) (string, bool) {
	switch {
	case observation.Phase == requestObservationLifecycle && observation.Outcome == requestOutcomeDeadline:
		return "OpenAI API retry lifecycle exceeded its deadline", true
	case observation.Phase == requestObservationLifecycle && observation.Outcome == requestOutcomeRequestError:
		return "OpenAI API retry lifecycle failed during request transport or response decoding", true
	case observation.Phase == requestObservationLifecycle && observation.Outcome == requestOutcomeAPIError && (observation.StatusCode == http.StatusTooManyRequests || observation.StatusCode >= http.StatusInternalServerError):
		return "OpenAI API retry lifecycle ended with a terminal retryable API error", true
	default:
		return "", false
	}
}

func (c *APIClient) requestObservationWarningMessage(observation requestObservation) (string, bool) {
	switch {
	case observation.Phase == requestObservationPending:
		return "OpenAI API request is still pending", true
	case observation.Phase == requestObservationLifecycle && observation.Duration >= c.effectiveSlowRequestThreshold():
		return "OpenAI API retry lifecycle completed after delay", true
	case observation.Phase == requestObservationAttempt && (observation.TimedOut || observation.Duration >= c.effectiveSlowRequestThreshold()):
		return "OpenAI API request attempt completed after delay or timeout", true
	default:
		return "", false
	}
}

func (c *APIClient) recordRequestObservation(ctx context.Context, observation requestObservation) {
	fields := map[string]any{
		"method":        observation.Method,
		"outcome":       observation.Outcome,
		"path":          observation.Path,
		"phase":         observation.Phase,
		"duration_ms":   observation.Duration.Milliseconds(),
		"attempt_count": observation.AttemptCount,
		"retry_count":   observation.RetryCount,
		"status_code":   observation.StatusCode,
		"timed_out":     observation.TimedOut,
	}
	if observation.Phase == requestObservationAttempt || observation.Phase == requestObservationLifecycle {
		fields["attempt_duration_ms"] = observation.AttemptDuration.Milliseconds()
		fields["cooldown_wait_duration_ms"] = observation.CooldownWaitDuration.Milliseconds()
		fields["response_bytes"] = observation.ResponseBytes
	}
	if observation.Phase == requestObservationLifecycle {
		fields["non_attempt_duration_ms"] = observation.NonAttemptDuration.Milliseconds()
	}
	logContext := openAIClientLogContext(ctx)
	if message, failed := c.requestObservationErrorMessage(observation); failed {
		tflog.SubsystemError(logContext, openAIClientLogSubsystem, message, fields)
	} else if message, warn := c.requestObservationWarningMessage(observation); warn {
		tflog.SubsystemWarn(logContext, openAIClientLogSubsystem, message, fields)
	} else {
		tflog.SubsystemDebug(logContext, openAIClientLogSubsystem, "OpenAI API request completed", fields)
	}
	if c.requestObserver != nil {
		c.requestObserver(observation)
	}
}

func (c *APIClient) recordPaginationObservation(ctx context.Context, observation paginationObservation) {
	fields := map[string]any{
		"method":      observation.Method,
		"outcome":     observation.Outcome,
		"path":        observation.Path,
		"duration_ms": observation.Duration.Milliseconds(),
		"page_count":  observation.PageCount,
		"item_count":  observation.ItemCount,
	}
	logContext := openAIClientLogContext(ctx)
	if observation.Duration >= c.effectiveSlowRequestThreshold() {
		tflog.SubsystemWarn(logContext, openAIClientLogSubsystem, "OpenAI API pagination completed after delay", fields)
	} else {
		tflog.SubsystemDebug(logContext, openAIClientLogSubsystem, "OpenAI API pagination completed", fields)
	}
	if c.paginationObserver != nil {
		c.paginationObserver(observation)
	}
}

func (c *APIClient) requestTelemetryMiddleware(ctx context.Context, method string, path string, lifecycle *requestLifecycleState) option.Middleware {
	return func(request *http.Request, next option.MiddlewareNext) (*http.Response, error) {
		cooldownWaitStartedAt := time.Now()
		coordinatedCooldown, cooldownGeneration, releaseCooldown, err := c.retryAfterCooldown.wait(request.Context())
		cooldownWaitDuration := time.Since(cooldownWaitStartedAt)
		lifecycle.recordCooldownWait(cooldownWaitDuration)
		if err != nil {
			return nil, err
		}
		defer releaseCooldown()
		startedAt := time.Now()
		retryCount := lifecycle.beginAttempt()

		attemptContext := request.Context()
		cancelAttempt := func() {}
		attemptRequest := request
		if method == http.MethodGet {
			attemptContext, cancelAttempt = context.WithTimeout(attemptContext, c.effectiveRequestAttemptTimeout())
			attemptRequest = request.Clone(attemptContext)
		}
		response, err := next(attemptRequest)
		err = sanitizeRedirectError(response, err)
		c.retryAfterCooldown.observeResponse(response, time.Now(), coordinatedCooldown, cooldownGeneration)
		releaseCooldown()
		statusCode := 0
		responseBytes := int64(-1)
		if response != nil {
			statusCode = response.StatusCode
			responseBytes = response.ContentLength
		}
		if err == nil && method == http.MethodGet && response != nil && response.Body != nil {
			responseBody, bodyErr := c.readResponseBody(attemptContext, response)
			responseBytes = int64(len(responseBody))
			if bodyErr != nil {
				err = bodyErr
				var limitErr *responseBodyLimitError
				if errors.As(bodyErr, &limitErr) {
					response.Header.Set("x-should-retry", "false")
				} else if !responseMetadataControlsRetry(response) {
					response = nil
				}
			} else {
				response.Body = io.NopCloser(bytes.NewReader(responseBody))
				response.ContentLength = int64(len(responseBody))
			}
		}
		attemptContextErr := attemptContext.Err()
		cancelAttempt()
		attemptDuration := time.Since(startedAt)
		observation := requestObservation{
			Phase:                requestObservationAttempt,
			Method:               method,
			Path:                 path,
			Duration:             attemptDuration,
			AttemptDuration:      attemptDuration,
			CooldownWaitDuration: cooldownWaitDuration,
			AttemptCount:         retryCount + 1,
			RetryCount:           retryCount,
			StatusCode:           statusCode,
			ResponseBytes:        responseBytes,
			TimedOut:             errors.Is(err, context.DeadlineExceeded) || errors.Is(attemptContextErr, context.DeadlineExceeded),
		}
		observation.Outcome = classifyRequestOutcome(err, attemptContextErr, observation.StatusCode)
		lifecycle.recordStatusCode(observation.StatusCode)
		lifecycle.recordAttempt(attemptDuration, responseBytes)
		c.recordRequestObservation(ctx, observation)
		return response, err
	}
}

func (c *APIClient) requestOptions(ctx context.Context, method string, path string, lifecycle *requestLifecycleState) []option.RequestOption {
	version := strings.TrimSpace(c.ProviderVersion)
	if version == "" {
		version = "dev"
	}
	return []option.RequestOption{
		option.WithHeader("User-Agent", "terraform-provider-openai/"+version),
		option.WithMaxRetries(c.effectiveRequestMaxRetries(method)),
		option.WithMiddleware(c.requestTelemetryMiddleware(ctx, method, path, lifecycle)),
	}
}

func (c *APIClient) Request(ctx context.Context, method string, path string, pathParams map[string]string, queryParams map[string]string, body map[string]any) (map[string]any, error) {
	ctx = openAIClientLogContext(ctx)
	expandedPath, err := expandAPIPath(path, pathParams)
	if err != nil {
		return nil, err
	}
	expandedPath = appendQuery(expandedPath, queryParams)

	requestTimeout := c.effectiveRequestTimeout()
	requestContext, cancel := context.WithTimeout(ctx, requestTimeout)
	defer cancel()
	requestStartedAt := time.Now()
	slowThreshold := c.effectiveSlowRequestThreshold()
	lifecycle := &requestLifecycleState{}
	pendingTimerDone := make(chan struct{})
	pendingTimer := time.AfterFunc(slowThreshold, func() {
		defer close(pendingTimerDone)
		attemptCount, retryCount, statusCode, _, _, _ := lifecycle.snapshot()
		c.recordRequestObservation(ctx, requestObservation{
			Phase:        requestObservationPending,
			Outcome:      requestOutcomePending,
			Method:       method,
			Path:         path,
			Duration:     slowThreshold,
			AttemptCount: attemptCount,
			RetryCount:   retryCount,
			StatusCode:   statusCode,
		})
	})
	var stopPendingTimerOnce sync.Once
	stopPendingTimer := func() {
		stopPendingTimerOnce.Do(func() {
			if !pendingTimer.Stop() {
				<-pendingTimerDone
			}
		})
	}
	defer stopPendingTimer()
	requestOptions := c.requestOptions(ctx, method, path, lifecycle)

	var response map[string]any
	switch method {
	case http.MethodGet:
		err = c.Client.Get(requestContext, expandedPath, nil, &response, requestOptions...)
	case http.MethodPost:
		err = c.Client.Post(requestContext, expandedPath, body, &response, requestOptions...)
	case http.MethodPut:
		err = c.Client.Put(requestContext, expandedPath, body, &response, requestOptions...)
	case http.MethodPatch:
		err = c.Client.Patch(requestContext, expandedPath, body, &response, requestOptions...)
	case http.MethodDelete:
		err = c.Client.Delete(requestContext, expandedPath, nil, &response, requestOptions...)
	default:
		return nil, fmt.Errorf("unsupported OpenAI API method %q", method)
	}
	stopPendingTimer()
	requestDuration := time.Since(requestStartedAt)
	attemptCount, retryCount, statusCode, attemptDuration, cooldownWaitDuration, responseBytes := lifecycle.snapshot()
	nonAttemptDuration := requestDuration - attemptDuration
	if nonAttemptDuration < 0 {
		nonAttemptDuration = 0
	}
	c.recordRequestObservation(ctx, requestObservation{
		Phase:                requestObservationLifecycle,
		Outcome:              classifyRequestOutcome(err, requestContext.Err(), statusCode),
		Method:               method,
		Path:                 path,
		Duration:             requestDuration,
		AttemptDuration:      attemptDuration,
		NonAttemptDuration:   nonAttemptDuration,
		CooldownWaitDuration: cooldownWaitDuration,
		AttemptCount:         attemptCount,
		RetryCount:           retryCount,
		StatusCode:           statusCode,
		ResponseBytes:        responseBytes,
		TimedOut:             errors.Is(err, context.DeadlineExceeded) || errors.Is(requestContext.Err(), context.DeadlineExceeded),
	})
	if err != nil {
		if ctx.Err() == nil && errors.Is(requestContext.Err(), context.DeadlineExceeded) {
			return nil, fmt.Errorf(
				"OpenAI API %s %s exceeded the %s retry-lifecycle timeout after %d attempt(s) (last_status_code=%d): %w",
				method,
				path,
				requestTimeout,
				attemptCount,
				statusCode,
				context.DeadlineExceeded,
			)
		}
		if ctx.Err() == nil && errors.Is(err, context.DeadlineExceeded) {
			return nil, fmt.Errorf(
				"OpenAI API %s %s exhausted %d attempt(s) after per-attempt timeouts within the %s retry lifecycle (last_status_code=%d): %w",
				method,
				path,
				attemptCount,
				requestTimeout,
				statusCode,
				context.DeadlineExceeded,
			)
		}
		return nil, err
	}
	if response == nil {
		response = map[string]any{}
	}
	return response, nil
}

func nextPageCursor(response map[string]any, items []any) string {
	if next, ok := response["next"].(string); ok && strings.TrimSpace(next) != "" {
		return next
	}
	if len(items) == 0 {
		return ""
	}
	last, ok := items[len(items)-1].(map[string]any)
	if !ok {
		return ""
	}
	if id, ok := responseString(last["id"]); ok {
		return id
	}
	return ""
}

func (c *APIClient) PaginatedRequest(ctx context.Context, method string, path string, pathParams map[string]string, queryParams map[string]string) (responseData map[string]any, err error) {
	if method != http.MethodGet {
		return c.Request(ctx, method, path, pathParams, queryParams, nil)
	}
	ctx = context.WithValue(ctx, paginatedResponseBudgetKey{}, &paginatedResponseBudget{
		remaining: c.effectiveMaxPaginatedResponseBytes(),
	})
	ctx = openAIClientLogContext(ctx)
	startedAt := time.Now()
	observation := paginationObservation{
		Method: method,
		Path:   path,
	}
	defer func() {
		observation.Duration = time.Since(startedAt)
		observation.Outcome = requestOutcomeSuccess
		if err != nil {
			observation.Outcome = classifyRequestOutcome(err, ctx.Err(), requestErrorStatusCode(err))
		}
		c.recordPaginationObservation(ctx, observation)
	}()
	nextQueryParams := copyQueryParams(queryParams)
	var merged map[string]any
	items := []any{}
	seenCursors := map[string]struct{}{}
	for page := 1; ; page++ {
		if page > maxPaginatedPages {
			return nil, fmt.Errorf("pagination exceeded %d pages for %s", maxPaginatedPages, path)
		}
		response, err := c.Request(ctx, method, path, pathParams, nextQueryParams, nil)
		if err != nil {
			return nil, err
		}
		observation.PageCount = page
		if merged == nil {
			merged = response
		}
		pageItemsValue, ok := response["data"]
		if !ok {
			return nil, fmt.Errorf("pagination response field %q is missing for %s", "data", path)
		}
		pageItems, ok := pageItemsValue.([]any)
		if !ok {
			return nil, fmt.Errorf("pagination response field %q is not a list for %s", "data", path)
		}
		items = append(items, pageItems...)
		observation.ItemCount = len(items)
		hasMoreValue, ok := response["has_more"]
		if !ok {
			return nil, fmt.Errorf("pagination response field %q is missing for %s", "has_more", path)
		}
		hasMore, ok := hasMoreValue.(bool)
		if !ok {
			return nil, fmt.Errorf("pagination response field %q is not a bool for %s", "has_more", path)
		}
		cursor := strings.TrimSpace(nextPageCursor(response, pageItems))
		if !hasMore {
			if merged == nil {
				merged = map[string]any{}
			}
			merged["data"] = items
			merged["has_more"] = false
			merged["next"] = nil
			return merged, nil
		}
		if cursor == "" {
			return nil, fmt.Errorf("pagination response has_more=true without usable cursor for %s", path)
		}
		if _, seen := seenCursors[cursor]; seen {
			return nil, fmt.Errorf("pagination cursor repeated for %s: %q", path, cursor)
		}
		seenCursors[cursor] = struct{}{}
		nextQueryParams["after"] = cursor
	}
}

func SetBodyField(body map[string]any, path []string, value any) {
	if len(path) == 0 {
		return
	}
	current := body
	for _, part := range path[:len(path)-1] {
		next, ok := current[part].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[part] = next
		}
		current = next
	}
	current[path[len(path)-1]] = value
}

func AddStringBodyField(body map[string]any, name string, value types.String) {
	if value.IsUnknown() {
		return
	}
	if value.IsNull() {
		return
	}
	SetBodyField(body, []string{name}, value.ValueString())
}

func AddInt64BodyField(body map[string]any, name string, value types.Int64) {
	if value.IsUnknown() {
		return
	}
	if value.IsNull() {
		return
	}
	SetBodyField(body, []string{name}, value.ValueInt64())
}

func AddBoolBodyField(body map[string]any, name string, value types.Bool) {
	if value.IsUnknown() {
		return
	}
	if value.IsNull() {
		return
	}
	SetBodyField(body, []string{name}, value.ValueBool())
}

func AddNullableStringBodyFieldForUpdate(body map[string]any, name string, planned types.String, prior types.String) {
	if planned.IsUnknown() {
		return
	}
	if planned.IsNull() {
		if !prior.IsNull() && !prior.IsUnknown() {
			body[name] = nil
		}
		return
	}
	body[name] = planned.ValueString()
}

func ResponseObjectByField(response map[string]any, sourcePath string, matchField string, matchValue string) (map[string]any, bool, error) {
	objects, err := ResponseObjectList(response, sourcePath, true)
	if err != nil {
		return nil, false, err
	}
	for _, object := range objects {
		value, ok := responseValue(object, matchField)
		if !ok {
			continue
		}
		stringValue, ok := responseString(value)
		if ok && stringValue == matchValue {
			return object, true, nil
		}
	}
	return nil, false, nil
}

func responseValue(response map[string]any, path string) (any, bool) {
	if path == "" {
		return response, true
	}
	var current any = response
	for _, part := range strings.Split(path, ".") {
		object, ok := current.(map[string]any)
		if !ok {
			return nil, false
		}
		current, ok = object[part]
		if !ok {
			return nil, false
		}
	}
	return current, true
}

func responseString(value any) (string, bool) {
	switch typed := value.(type) {
	case string:
		return typed, true
	case float64:
		return fmt.Sprintf("%v", typed), true
	case bool:
		if typed {
			return "true", true
		}
		return "false", true
	default:
		return "", false
	}
}

func responseStringList(value any) ([]string, bool) {
	switch typed := value.(type) {
	case []string:
		return typed, true
	case []any:
		values := make([]string, 0, len(typed))
		for _, item := range typed {
			stringValue, ok := responseString(item)
			if !ok {
				return nil, false
			}
			values = append(values, stringValue)
		}
		return values, true
	default:
		return nil, false
	}
}

func responseBool(value any) (bool, bool) {
	switch typed := value.(type) {
	case bool:
		return typed, true
	case string:
		if typed == "true" {
			return true, true
		}
		if typed == "false" {
			return false, true
		}
		return false, false
	default:
		return false, false
	}
}

func responseInt64(value any) (int64, bool) {
	switch typed := value.(type) {
	case int64:
		return typed, true
	case int:
		return int64(typed), true
	case float64:
		return int64(typed), true
	default:
		return 0, false
	}
}

func responseFieldPathText(paths []string) string {
	return strings.Join(paths, ", ")
}

func missingRequiredResponseFieldError(paths []string) error {
	return fmt.Errorf("missing required response field; tried paths: %s", responseFieldPathText(paths))
}

func malformedResponseFieldError(path string, expected string) error {
	return fmt.Errorf("response field %q is not %s", path, expected)
}

func ApplyStringResponseField(response map[string]any, paths []string, target *types.String, required bool) error {
	for _, path := range paths {
		value, ok := responseValue(response, path)
		if !ok {
			continue
		}
		if value == nil {
			*target = types.StringNull()
			return nil
		}
		if stringValue, ok := responseString(value); ok {
			*target = types.StringValue(stringValue)
			return nil
		}
		return malformedResponseFieldError(path, "a string-compatible value")
	}
	if required {
		return missingRequiredResponseFieldError(paths)
	}
	if target.IsUnknown() {
		*target = types.StringNull()
	}
	return nil
}

func ApplyStringListResponseField(response map[string]any, paths []string, target *types.List, required bool) error {
	for _, path := range paths {
		value, ok := responseValue(response, path)
		if !ok {
			continue
		}
		if value == nil {
			*target = types.ListNull(types.StringType)
			return nil
		}
		if listValue, ok := responseStringList(value); ok {
			*target = types.ListValueMust(types.StringType, stringListValues(listValue))
			return nil
		}
		return malformedResponseFieldError(path, "a string list")
	}
	if required {
		return missingRequiredResponseFieldError(paths)
	}
	if target.IsUnknown() {
		*target = types.ListNull(types.StringType)
	}
	return nil
}

func ApplyBoolResponseField(response map[string]any, paths []string, target *types.Bool, required bool) error {
	for _, path := range paths {
		value, ok := responseValue(response, path)
		if !ok {
			continue
		}
		if value == nil {
			*target = types.BoolNull()
			return nil
		}
		if boolValue, ok := responseBool(value); ok {
			*target = types.BoolValue(boolValue)
			return nil
		}
		return malformedResponseFieldError(path, "a bool-compatible value")
	}
	if required {
		return missingRequiredResponseFieldError(paths)
	}
	if target.IsUnknown() {
		*target = types.BoolNull()
	}
	return nil
}

func ApplyInt64ResponseField(response map[string]any, paths []string, target *types.Int64, required bool) error {
	for _, path := range paths {
		value, ok := responseValue(response, path)
		if !ok {
			continue
		}
		if value == nil {
			*target = types.Int64Null()
			return nil
		}
		if intValue, ok := responseInt64(value); ok {
			*target = types.Int64Value(intValue)
			return nil
		}
		return malformedResponseFieldError(path, "an integer-compatible value")
	}
	if required {
		return missingRequiredResponseFieldError(paths)
	}
	if target.IsUnknown() {
		*target = types.Int64Null()
	}
	return nil
}

func ResponseObjectList(response map[string]any, path string, required bool) ([]map[string]any, error) {
	value, ok := responseValue(response, path)
	if !ok {
		if required {
			return nil, missingRequiredResponseFieldError([]string{path})
		}
		return nil, nil
	}
	items, ok := value.([]any)
	if !ok {
		return nil, malformedResponseFieldError(path, "a list of objects")
	}
	objects := make([]map[string]any, 0, len(items))
	for index, item := range items {
		object, ok := item.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("response field %q item %d is not an object", path, index)
		}
		objects = append(objects, object)
	}
	return objects, nil
}

func stringListValues(values []string) []attr.Value {
	result := make([]attr.Value, 0, len(values))
	for _, value := range values {
		result = append(result, types.StringValue(value))
	}
	return result
}

func ResponseJSONValue(response map[string]any) types.String {
	payload, err := json.Marshal(response)
	if err != nil {
		return types.StringValue("{}")
	}
	return types.StringValue(string(payload))
}

type stringLengthAtLeastValidator struct {
	min int
}

func StringLengthAtLeast(min int) validator.String {
	return stringLengthAtLeastValidator{min: min}
}

func (v stringLengthAtLeastValidator) Description(ctx context.Context) string {
	return fmt.Sprintf("length must be at least %d", v.min)
}

func (v stringLengthAtLeastValidator) MarkdownDescription(ctx context.Context) string {
	return v.Description(ctx)
}

func (v stringLengthAtLeastValidator) ValidateString(ctx context.Context, req validator.StringRequest, resp *validator.StringResponse) {
	if req.ConfigValue.IsNull() || req.ConfigValue.IsUnknown() {
		return
	}
	if len(req.ConfigValue.ValueString()) < v.min {
		resp.Diagnostics.AddAttributeError(req.Path, "Invalid string length", fmt.Sprintf("Value must be at least %d characters.", v.min))
	}
}

type int64AtLeastValidator struct {
	min int64
}

func Int64AtLeast(min int64) validator.Int64 {
	return int64AtLeastValidator{min: min}
}

func (v int64AtLeastValidator) Description(ctx context.Context) string {
	return fmt.Sprintf("value must be at least %d", v.min)
}

func (v int64AtLeastValidator) MarkdownDescription(ctx context.Context) string {
	return v.Description(ctx)
}

func (v int64AtLeastValidator) ValidateInt64(ctx context.Context, req validator.Int64Request, resp *validator.Int64Response) {
	if req.ConfigValue.IsNull() || req.ConfigValue.IsUnknown() {
		return
	}
	if req.ConfigValue.ValueInt64() < v.min {
		resp.Diagnostics.AddAttributeError(req.Path, "Invalid integer value", fmt.Sprintf("Value must be at least %d.", v.min))
	}
}

type stringIsValidPathParameterValidator struct{}

func StringIsValidPathParameter() validator.String {
	return stringIsValidPathParameterValidator{}
}

func (v stringIsValidPathParameterValidator) Description(ctx context.Context) string {
	return "value must be a non-empty URL path parameter and cannot be a dot segment"
}

func (v stringIsValidPathParameterValidator) MarkdownDescription(ctx context.Context) string {
	return v.Description(ctx)
}

func (v stringIsValidPathParameterValidator) ValidateString(ctx context.Context, req validator.StringRequest, resp *validator.StringResponse) {
	if req.ConfigValue.IsNull() || req.ConfigValue.IsUnknown() {
		return
	}
	if err := ValidatePathParameter(req.Path.String(), req.ConfigValue.ValueString()); err != nil {
		resp.Diagnostics.AddAttributeError(req.Path, "Invalid API path parameter", err.Error())
	}
}

type stringOneOfValidator struct {
	values []string
}

func StringOneOf(values ...string) validator.String {
	return stringOneOfValidator{values: values}
}

func (v stringOneOfValidator) Description(ctx context.Context) string {
	return "value must be one of " + strings.Join(v.values, ", ")
}

func (v stringOneOfValidator) MarkdownDescription(ctx context.Context) string {
	return v.Description(ctx)
}

func (v stringOneOfValidator) ValidateString(ctx context.Context, req validator.StringRequest, resp *validator.StringResponse) {
	if req.ConfigValue.IsNull() || req.ConfigValue.IsUnknown() {
		return
	}
	value := req.ConfigValue.ValueString()
	for _, allowed := range v.values {
		if value == allowed {
			return
		}
	}
	resp.Diagnostics.AddAttributeError(req.Path, "Invalid string value", "Value must be one of: "+strings.Join(v.values, ", "))
}

type stringExactlyOneOfValidator struct {
	names []string
}

func StringExactlyOneOf(names ...string) validator.String {
	return stringExactlyOneOfValidator{names: names}
}

func (v stringExactlyOneOfValidator) Description(ctx context.Context) string {
	return "exactly one of " + strings.Join(v.names, ", ") + " must be configured"
}

func (v stringExactlyOneOfValidator) MarkdownDescription(ctx context.Context) string {
	return v.Description(ctx)
}

func (v stringExactlyOneOfValidator) ValidateString(ctx context.Context, req validator.StringRequest, resp *validator.StringResponse) {
	configured := 0
	for _, name := range v.names {
		var value types.String
		resp.Diagnostics.Append(req.Config.GetAttribute(ctx, path.Root(name), &value)...)
		if resp.Diagnostics.HasError() {
			return
		}
		if value.IsUnknown() {
			return
		}
		if !value.IsNull() && strings.TrimSpace(value.ValueString()) != "" {
			configured++
		}
	}
	if configured != 1 {
		resp.Diagnostics.AddAttributeError(req.Path, "Invalid attribute combination", "Exactly one of "+strings.Join(v.names, ", ")+" must be configured.")
	}
}

type listSizeAtLeastValidator struct {
	min int
}

func ListSizeAtLeast(min int) validator.List {
	return listSizeAtLeastValidator{min: min}
}

func (v listSizeAtLeastValidator) Description(ctx context.Context) string {
	return fmt.Sprintf("list size must be at least %d", v.min)
}

func (v listSizeAtLeastValidator) MarkdownDescription(ctx context.Context) string {
	return v.Description(ctx)
}

func (v listSizeAtLeastValidator) ValidateList(ctx context.Context, req validator.ListRequest, resp *validator.ListResponse) {
	if req.ConfigValue.IsNull() || req.ConfigValue.IsUnknown() {
		return
	}
	if len(req.ConfigValue.Elements()) < v.min {
		resp.Diagnostics.AddAttributeError(req.Path, "Invalid list size", fmt.Sprintf("List must contain at least %d elements.", v.min))
	}
}
