// Code generated by generate-terraform-provider. DO NOT EDIT.

package openaiapi

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/types"
	openai "github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
)

func TestRequestExpandsPathQueryAndUserAgent(t *testing.T) {
	var gotPath string
	var gotLimit string
	var gotUserAgent string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotLimit = r.URL.Query().Get("limit")
		gotUserAgent = r.Header.Get("User-Agent")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group_1"})
	}))
	t.Cleanup(server.Close)

	client := &APIClient{
		ProviderVersion: "test",
		Client:          openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
	}
	response, err := client.Request(
		context.Background(),
		http.MethodGet,
		"/organization/groups/{group_id}/users",
		map[string]string{"group_id": "group_1"},
		map[string]string{"limit": "2"},
		nil,
	)
	if err != nil {
		t.Fatalf("Request returned error: %v", err)
	}
	if response["id"] != "group_1" {
		t.Fatalf("unexpected response: %#v", response)
	}
	if !strings.HasSuffix(gotPath, "/organization/groups/group_1/users") {
		t.Fatalf("unexpected path: %s", gotPath)
	}
	if gotLimit != "2" {
		t.Fatalf("unexpected limit query param: %q", gotLimit)
	}
	if !strings.Contains(gotUserAgent, "terraform-provider-openai/test") {
		t.Fatalf("expected terraform provider user agent, got %q", gotUserAgent)
	}
}

func TestRequestRejectsPathDotSegments(t *testing.T) {
	calls := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls++
		http.Error(w, "unexpected request", http.StatusInternalServerError)
	}))
	t.Cleanup(server.Close)

	client := &APIClient{
		ProviderVersion: "test",
		Client:          openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
	}
	tests := []struct {
		name   string
		method string
		path   string
		params map[string]string
	}{
		{
			name:   "single dot",
			method: http.MethodGet,
			path:   "/projects/{project_id}",
			params: map[string]string{"project_id": "."},
		},
		{
			name:   "project group role delete",
			method: http.MethodDelete,
			path:   "/projects/{project_id}/groups/{group_id}/roles/{role_id}",
			params: map[string]string{"project_id": "project_1", "group_id": "..", "role_id": "role_1"},
		},
		{
			name:   "project spend alert create",
			method: http.MethodPost,
			path:   "/organization/projects/{project_id}/spend_alerts",
			params: map[string]string{"project_id": ".."},
		},
		{
			name:   "project spend alert update",
			method: http.MethodPost,
			path:   "/organization/projects/{project_id}/spend_alerts/{alert_id}",
			params: map[string]string{"project_id": "..", "alert_id": "alert_1"},
		},
		{
			name:   "project spend alert delete",
			method: http.MethodDelete,
			path:   "/organization/projects/{project_id}/spend_alerts/{alert_id}",
			params: map[string]string{"project_id": "..", "alert_id": "alert_1"},
		},
		{
			name:   "project user role delete",
			method: http.MethodDelete,
			path:   "/projects/{project_id}/users/{user_id}/roles/{role_id}",
			params: map[string]string{"project_id": "project_1", "user_id": "..", "role_id": "role_1"},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := client.Request(
				context.Background(),
				test.method,
				test.path,
				test.params,
				map[string]string{},
				nil,
			)
			if err == nil || !strings.Contains(err.Error(), "URL dot segments are not allowed") {
				t.Fatalf("expected dot-segment validation error, got %v", err)
			}
		})
	}
	if calls != 0 {
		t.Fatalf("expected invalid paths to be rejected before dispatch, got %d requests", calls)
	}
}

func TestRetryAfterDuration(t *testing.T) {
	now := time.Date(2026, time.July, 20, 12, 0, 0, 0, time.UTC)
	tests := []struct {
		name     string
		status   int
		headers  map[string]string
		expected time.Duration
		ok       bool
	}{
		{
			name:     "standard seconds",
			status:   http.StatusTooManyRequests,
			headers:  map[string]string{"Retry-After": "2"},
			expected: 2 * time.Second,
			ok:       true,
		},
		{
			name:     "standard HTTP date",
			status:   http.StatusTooManyRequests,
			headers:  map[string]string{"Retry-After": now.Add(3 * time.Second).Format(http.TimeFormat)},
			expected: 3 * time.Second,
			ok:       true,
		},
		{
			name:     "millisecond extension",
			status:   http.StatusTooManyRequests,
			headers:  map[string]string{"Retry-After-Ms": "75", "Retry-After": "2"},
			expected: 75 * time.Millisecond,
			ok:       true,
		},
		{
			name:    "non-rate-limit response",
			status:  http.StatusServiceUnavailable,
			headers: map[string]string{"Retry-After": "2"},
		},
		{
			name:    "invalid value",
			status:  http.StatusTooManyRequests,
			headers: map[string]string{"Retry-After": "later"},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			response := &http.Response{StatusCode: test.status, Header: make(http.Header)}
			for name, value := range test.headers {
				response.Header.Set(name, value)
			}
			delay, ok := retryAfterDuration(response, now)
			if ok != test.ok || delay != test.expected {
				t.Fatalf("retryAfterDuration() = (%s, %t), want (%s, %t)", delay, ok, test.expected, test.ok)
			}
		})
	}
}

func TestRequestSharesRetryAfterCooldown(t *testing.T) {
	var calls atomic.Int64
	var callsMu sync.Mutex
	var callTimes []time.Time
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		call := calls.Add(1)
		callsMu.Lock()
		callTimes = append(callTimes, time.Now())
		callsMu.Unlock()
		w.Header().Set("Content-Type", "application/json")
		if call == 1 {
			w.Header().Set("Retry-After-Ms", "75")
			w.WriteHeader(http.StatusTooManyRequests)
			_ = json.NewEncoder(w).Encode(map[string]any{
				"error": map[string]any{"message": "retry later", "type": "rate_limit_error"},
			})
			return
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	maxRetries := 0
	client := &APIClient{
		ProviderVersion:   "test",
		Client:            openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestMaxRetries: &maxRetries,
	}
	_, err := client.Request(context.Background(), http.MethodGet, "/organization/groups", nil, nil, nil)
	if err == nil {
		t.Fatal("expected the first request to return a rate-limit error")
	}
	response, err := client.Request(context.Background(), http.MethodGet, "/organization/groups", nil, nil, nil)
	if err != nil {
		t.Fatalf("second request returned error after shared cooldown: %v", err)
	}
	if response["id"] != "group-1" {
		t.Fatalf("unexpected response after shared cooldown: %#v", response)
	}

	callsMu.Lock()
	defer callsMu.Unlock()
	if len(callTimes) != 2 {
		t.Fatalf("expected two requests, got %d", len(callTimes))
	}
	if delay := callTimes[1].Sub(callTimes[0]); delay < 70*time.Millisecond {
		t.Fatalf("shared Retry-After cooldown was not honored: %s", delay)
	}
}

func TestRetryAfterCooldownHonorsCancellation(t *testing.T) {
	cooldown := &retryAfterCooldown{until: time.Now().Add(time.Hour)}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Millisecond)
	defer cancel()
	startedAt := time.Now()
	_, _, err := cooldown.wait(ctx)
	if !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("cooldown wait returned %v, want context deadline exceeded", err)
	}
	if duration := time.Since(startedAt); duration > time.Second {
		t.Fatalf("cooldown wait did not stop promptly after cancellation: %s", duration)
	}
}

func TestRetryAfterCooldownSerializesDelayedWaiters(t *testing.T) {
	cooldown := &retryAfterCooldown{until: time.Now().Add(20 * time.Millisecond)}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	entered := make(chan int64, 2)
	releaseFirst := make(chan struct{})
	done := make(chan error, 2)
	var order atomic.Int64
	for range 2 {
		go func() {
			delayed, release, err := cooldown.wait(ctx)
			if err != nil {
				done <- err
				return
			}
			defer release()
			if !delayed {
				done <- errors.New("waiter did not observe the active cooldown")
				return
			}
			position := order.Add(1)
			entered <- position
			if position == 1 {
				<-releaseFirst
			}
			done <- nil
		}()
	}

	if position := <-entered; position != 1 {
		t.Fatalf("first released waiter has position %d", position)
	}
	select {
	case position := <-entered:
		t.Fatalf("second waiter was released concurrently with position %d", position)
	case <-time.After(25 * time.Millisecond):
	}
	close(releaseFirst)
	select {
	case position := <-entered:
		if position != 2 {
			t.Fatalf("second released waiter has position %d", position)
		}
	case <-ctx.Done():
		t.Fatal("second waiter was not released after the first completed")
	}
	for range 2 {
		if err := <-done; err != nil {
			t.Fatal(err)
		}
	}
}

func TestRequestAttemptTimingExcludesSharedCooldown(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	maxRetries := 0
	var attemptDuration time.Duration
	client := &APIClient{
		ProviderVersion:      "test",
		Client:               openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:       time.Second,
		slowRequestThreshold: time.Second,
		requestMaxRetries:    &maxRetries,
		requestObserver: func(observation requestObservation) {
			if observation.Phase == requestObservationAttempt {
				attemptDuration = observation.Duration
			}
		},
	}
	client.retryAfterCooldown.until = time.Now().Add(250 * time.Millisecond)

	if _, err := client.Request(context.Background(), http.MethodGet, "/organization/groups", nil, nil, nil); err != nil {
		t.Fatalf("Request returned error after shared cooldown: %v", err)
	}
	if attemptDuration <= 0 || attemptDuration >= 200*time.Millisecond {
		t.Fatalf("attempt duration %s includes the shared cooldown", attemptDuration)
	}
}

func TestRequestReportsZeroAttemptsWhenCooldownExhaustsLifecycle(t *testing.T) {
	var calls atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	maxRetries := 0
	client := &APIClient{
		ProviderVersion:      "test",
		Client:               openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:       20 * time.Millisecond,
		slowRequestThreshold: time.Second,
		requestMaxRetries:    &maxRetries,
	}
	client.retryAfterCooldown.until = time.Now().Add(time.Second)

	_, err := client.Request(context.Background(), http.MethodGet, "/organization/groups", nil, nil, nil)
	if err == nil || !strings.Contains(err.Error(), "after 0 attempt(s)") {
		t.Fatalf("expected zero-attempt retry-lifecycle timeout, got %v", err)
	}
	if calls.Load() != 0 {
		t.Fatalf("expected no HTTP attempts before cooldown timeout, got %d", calls.Load())
	}
}

func TestRequestBoundsRetryLifecycleAndRedactsTelemetry(t *testing.T) {
	var calls atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Retry-After", "10")
		w.WriteHeader(http.StatusTooManyRequests)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"error": map[string]any{"message": "retry later", "type": "rate_limit_error"},
		})
	}))
	t.Cleanup(server.Close)

	maxRetries := 2
	var observationsMu sync.Mutex
	var observations []requestObservation
	client := &APIClient{
		ProviderVersion:      "test",
		Client:               openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:       75 * time.Millisecond,
		slowRequestThreshold: 10 * time.Millisecond,
		requestMaxRetries:    &maxRetries,
		requestObserver: func(observation requestObservation) {
			observationsMu.Lock()
			defer observationsMu.Unlock()
			observations = append(observations, observation)
		},
	}

	startedAt := time.Now()
	_, err := client.Request(
		context.Background(),
		http.MethodGet,
		"/organization/projects/{project_id}/rate_limits",
		map[string]string{"project_id": "secret-project-id"},
		map[string]string{"after": "secret-cursor"},
		nil,
	)
	duration := time.Since(startedAt)
	if err == nil || !strings.Contains(err.Error(), "retry-lifecycle timeout") {
		t.Fatalf("expected bounded retry-lifecycle timeout, got %v", err)
	}
	if !strings.Contains(err.Error(), "GET /organization/projects/{project_id}/rate_limits") ||
		!strings.Contains(err.Error(), "after 1 attempt(s)") ||
		!strings.Contains(err.Error(), "last_status_code=429") {
		t.Fatalf("expected safe terminal request metadata, got %v", err)
	}
	if strings.Contains(err.Error(), "secret-project-id") || strings.Contains(err.Error(), "secret-cursor") {
		t.Fatalf("terminal request metadata contained a concrete path or query value: %v", err)
	}
	if duration > time.Second {
		t.Fatalf("request exceeded its bounded lifecycle: %s", duration)
	}
	if calls.Load() != 1 {
		t.Fatalf("expected timeout during retry backoff before another attempt, got %d calls", calls.Load())
	}

	observationsMu.Lock()
	defer observationsMu.Unlock()
	var sawPending bool
	var sawTimedOutLifecycle bool
	for _, observation := range observations {
		if strings.Contains(observation.Path, "secret-project-id") || strings.Contains(observation.Path, "secret-cursor") {
			t.Fatalf("telemetry contained a concrete path or query value: %#v", observation)
		}
		if observation.Path != "/organization/projects/{project_id}/rate_limits" {
			t.Fatalf("telemetry did not retain the safe path template: %#v", observation)
		}
		sawPending = sawPending || observation.Phase == requestObservationPending
		sawTimedOutLifecycle = sawTimedOutLifecycle || observation.Phase == requestObservationLifecycle && observation.TimedOut
	}
	if !sawPending {
		t.Fatalf("expected pending retry-lifecycle telemetry, got %#v", observations)
	}
	if !sawTimedOutLifecycle {
		t.Fatalf("expected timed-out retry-lifecycle telemetry, got %#v", observations)
	}
	for _, observation := range observations {
		switch observation.Phase {
		case requestObservationPending:
			if observation.Outcome != requestOutcomePending {
				t.Fatalf("pending observation has outcome %q: %#v", observation.Outcome, observation)
			}
		case requestObservationLifecycle:
			if observation.Outcome != requestOutcomeDeadline {
				t.Fatalf("timed-out lifecycle has outcome %q: %#v", observation.Outcome, observation)
			}
			if message, failed := client.requestObservationErrorMessage(observation); !failed {
				t.Fatalf("timed-out lifecycle was not classified as an error: %q %#v", message, observation)
			}
		}
	}
}

func TestRequestRetriesTimedOutGETAttempt(t *testing.T) {
	var calls atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		call := calls.Add(1)
		if call == 1 {
			<-r.Context().Done()
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	maxRetries := 1
	var observationsMu sync.Mutex
	var observations []requestObservation
	client := &APIClient{
		ProviderVersion:       "test",
		Client:                openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:        2 * time.Second,
		requestAttemptTimeout: 10 * time.Millisecond,
		slowRequestThreshold:  2 * time.Second,
		requestMaxRetries:     &maxRetries,
		requestObserver: func(observation requestObservation) {
			observationsMu.Lock()
			defer observationsMu.Unlock()
			observations = append(observations, observation)
		},
	}

	if _, err := client.Request(
		context.Background(),
		http.MethodGet,
		"/organization/projects/{project_id}/groups",
		map[string]string{"project_id": "project-1"},
		nil,
		nil,
	); err != nil {
		t.Fatalf("Request returned error after retryable attempt timeout: %v", err)
	}
	if calls.Load() != 2 {
		t.Fatalf("expected one timed-out attempt and one successful retry, got %d calls", calls.Load())
	}

	observationsMu.Lock()
	defer observationsMu.Unlock()
	var sawTimedOutAttempt bool
	var completedLifecycle requestObservation
	for _, observation := range observations {
		if observation.Phase == requestObservationAttempt && observation.RetryCount == 0 && observation.TimedOut {
			sawTimedOutAttempt = true
		}
		if observation.Phase == requestObservationLifecycle {
			completedLifecycle = observation
		}
	}
	if !sawTimedOutAttempt {
		t.Fatalf("expected timeout telemetry for the first attempt, got %#v", observations)
	}
	if completedLifecycle.Outcome != requestOutcomeSuccess || completedLifecycle.RetryCount != 1 {
		t.Fatalf("expected a successful lifecycle after one retry, got %#v", completedLifecycle)
	}
}

func TestRequestRetriesTimedOutGETResponseBody(t *testing.T) {
	var calls atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		call := calls.Add(1)
		w.Header().Set("Content-Type", "application/json")
		if call == 1 {
			w.WriteHeader(http.StatusOK)
			if flusher, ok := w.(http.Flusher); ok {
				flusher.Flush()
			}
			<-r.Context().Done()
			return
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	maxRetries := 1
	client := &APIClient{
		ProviderVersion:       "test",
		Client:                openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:        2 * time.Second,
		requestAttemptTimeout: 10 * time.Millisecond,
		slowRequestThreshold:  2 * time.Second,
		requestMaxRetries:     &maxRetries,
	}

	response, err := client.Request(
		context.Background(),
		http.MethodGet,
		"/organization/projects/{project_id}/groups",
		map[string]string{"project_id": "project-1"},
		nil,
		nil,
	)
	if err != nil {
		t.Fatalf("Request returned error after retryable response-body timeout: %v", err)
	}
	if response["id"] != "group-1" {
		t.Fatalf("unexpected response after response-body retry: %#v", response)
	}
	if calls.Load() != 2 {
		t.Fatalf("expected one timed-out response body and one successful retry, got %d calls", calls.Load())
	}
}

func TestRequestPreservesRetryAfterWhenGETResponseBodyTimesOut(t *testing.T) {
	var calls atomic.Int64
	var callsMu sync.Mutex
	var callTimes []time.Time
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		call := calls.Add(1)
		callsMu.Lock()
		callTimes = append(callTimes, time.Now())
		callsMu.Unlock()
		w.Header().Set("Content-Type", "application/json")
		if call == 1 {
			w.Header().Set("Retry-After-Ms", "75")
			w.WriteHeader(http.StatusTooManyRequests)
			if flusher, ok := w.(http.Flusher); ok {
				flusher.Flush()
			}
			<-r.Context().Done()
			return
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	maxRetries := 1
	client := &APIClient{
		ProviderVersion:       "test",
		Client:                openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:        2 * time.Second,
		requestAttemptTimeout: 10 * time.Millisecond,
		slowRequestThreshold:  2 * time.Second,
		requestMaxRetries:     &maxRetries,
	}

	response, err := client.Request(
		context.Background(),
		http.MethodGet,
		"/organization/projects/{project_id}/groups",
		map[string]string{"project_id": "project-1"},
		nil,
		nil,
	)
	if err != nil {
		t.Fatalf("Request returned error after retryable response-body timeout: %v", err)
	}
	if response["id"] != "group-1" {
		t.Fatalf("unexpected response after response-body retry: %#v", response)
	}
	if calls.Load() != 2 {
		t.Fatalf("expected one timed-out response body and one successful retry, got %d calls", calls.Load())
	}

	callsMu.Lock()
	defer callsMu.Unlock()
	if retryDelay := callTimes[1].Sub(callTimes[0]); retryDelay < 70*time.Millisecond {
		t.Fatalf("retry did not honor Retry-After-Ms: %s", retryDelay)
	}
}

func TestRequestKeepsGETAttemptContextThroughResponseBody(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		if flusher, ok := w.(http.Flusher); ok {
			flusher.Flush()
		}
		time.Sleep(20 * time.Millisecond)
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	maxRetries := 0
	client := &APIClient{
		ProviderVersion:       "test",
		Client:                openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:        time.Second,
		requestAttemptTimeout: 100 * time.Millisecond,
		slowRequestThreshold:  time.Second,
		requestMaxRetries:     &maxRetries,
	}

	response, err := client.Request(
		context.Background(),
		http.MethodGet,
		"/organization/projects/{project_id}/groups",
		map[string]string{"project_id": "project-1"},
		nil,
		nil,
	)
	if err != nil {
		t.Fatalf("Request canceled a healthy response body: %v", err)
	}
	if response["id"] != "group-1" {
		t.Fatalf("unexpected delayed-body response: %#v", response)
	}
}

func TestRequestReportsExhaustedGETAttemptTimeouts(t *testing.T) {
	var calls atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		<-r.Context().Done()
	}))
	t.Cleanup(server.Close)

	maxRetries := 0
	client := &APIClient{
		ProviderVersion:       "test",
		Client:                openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:        time.Second,
		requestAttemptTimeout: 10 * time.Millisecond,
		slowRequestThreshold:  time.Second,
		requestMaxRetries:     &maxRetries,
	}

	_, err := client.Request(
		context.Background(),
		http.MethodGet,
		"/organization/projects/{project_id}/groups",
		map[string]string{"project_id": "secret-project-id"},
		nil,
		nil,
	)
	if err == nil ||
		!strings.Contains(err.Error(), "GET /organization/projects/{project_id}/groups exhausted 1 attempt(s)") ||
		!strings.Contains(err.Error(), "last_status_code=0") {
		t.Fatalf("expected safe exhausted-attempt diagnostic, got %v", err)
	}
	if strings.Contains(err.Error(), "secret-project-id") {
		t.Fatalf("exhausted-attempt diagnostic contained a concrete project id: %v", err)
	}
	if calls.Load() != 1 {
		t.Fatalf("expected retries to honor max retries, got %d calls", calls.Load())
	}
}

func TestRequestDoesNotApplyAttemptTimeoutToMutation(t *testing.T) {
	var calls atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		time.Sleep(25 * time.Millisecond)
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	maxRetries := 1
	client := &APIClient{
		ProviderVersion:       "test",
		Client:                openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:        time.Second,
		requestAttemptTimeout: time.Millisecond,
		slowRequestThreshold:  time.Second,
		requestMaxRetries:     &maxRetries,
	}

	if _, err := client.Request(
		context.Background(),
		http.MethodPost,
		"/organization/projects/{project_id}/groups",
		map[string]string{"project_id": "project-1"},
		nil,
		map[string]any{"group_id": "group-1"},
	); err != nil {
		t.Fatalf("mutation unexpectedly inherited the GET attempt timeout: %v", err)
	}
	if calls.Load() != 1 {
		t.Fatalf("expected one mutation request, got %d calls", calls.Load())
	}
}

func TestRequestRecordsRetryAttempts(t *testing.T) {
	var calls atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		call := calls.Add(1)
		w.Header().Set("Content-Type", "application/json")
		if call == 1 {
			w.Header().Set("Retry-After-Ms", "1")
			w.WriteHeader(http.StatusInternalServerError)
			_ = json.NewEncoder(w).Encode(map[string]any{
				"error": map[string]any{"message": "retry", "type": "server_error"},
			})
			return
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	maxRetries := 2
	var observationsMu sync.Mutex
	var observations []requestObservation
	client := &APIClient{
		ProviderVersion: "test",
		Client: openai.NewClient(
			option.WithAPIKey("test"),
			option.WithBaseURL(server.URL),
			option.WithHeader("X-Stainless-Retry-Count", "42"),
		),
		requestTimeout:       time.Second,
		slowRequestThreshold: time.Second,
		requestMaxRetries:    &maxRetries,
		requestObserver: func(observation requestObservation) {
			observationsMu.Lock()
			defer observationsMu.Unlock()
			observations = append(observations, observation)
		},
	}

	if _, err := client.Request(context.Background(), http.MethodGet, "/organization/groups/{group_id}", map[string]string{"group_id": "group-1"}, nil, nil); err != nil {
		t.Fatalf("Request returned error: %v", err)
	}
	if calls.Load() != 2 {
		t.Fatalf("expected one retry before success, got %d calls", calls.Load())
	}

	observationsMu.Lock()
	defer observationsMu.Unlock()
	var sawInitialFailure bool
	var sawRetrySuccess bool
	var completedLifecycle requestObservation
	for _, observation := range observations {
		switch observation.Phase {
		case requestObservationAttempt:
			sawInitialFailure = sawInitialFailure || observation.RetryCount == 0 && observation.StatusCode == http.StatusInternalServerError && observation.Outcome == requestOutcomeAPIError
			sawRetrySuccess = sawRetrySuccess || observation.RetryCount == 1 && observation.StatusCode == http.StatusOK && observation.Outcome == requestOutcomeSuccess
			if message, warn := client.requestObservationWarningMessage(observation); warn {
				t.Fatalf("routine retry attempt was classified as warning %q: %#v", message, observation)
			}
		case requestObservationLifecycle:
			completedLifecycle = observation
		}
	}
	if !sawInitialFailure || !sawRetrySuccess {
		t.Fatalf("expected telemetry for the failed attempt and successful retry, got %#v", observations)
	}
	if completedLifecycle.RetryCount != 1 || completedLifecycle.StatusCode != http.StatusOK || completedLifecycle.Outcome != requestOutcomeSuccess {
		t.Fatalf("expected successful lifecycle to summarize one retry, got %#v", completedLifecycle)
	}
	if message, failed := client.requestObservationErrorMessage(completedLifecycle); failed {
		t.Fatalf("successful retry lifecycle was classified as error %q: %#v", message, completedLifecycle)
	}
	if message, warn := client.requestObservationWarningMessage(completedLifecycle); warn {
		t.Fatalf("successful retry lifecycle was classified as warning %q: %#v", message, completedLifecycle)
	}
	completedLifecycle.StatusCode = http.StatusInternalServerError
	completedLifecycle.Outcome = requestOutcomeAPIError
	if _, failed := client.requestObservationErrorMessage(completedLifecycle); !failed {
		t.Fatalf("terminal server error lifecycle was not classified as an error: %#v", completedLifecycle)
	}
}

func TestRequestWaitsForPendingObservationBeforeLifecycleCompletion(t *testing.T) {
	pendingStarted := make(chan struct{})
	releasePending := make(chan struct{})
	attemptCompleted := make(chan struct{})
	lifecycleCompleted := make(chan struct{})
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		<-pendingStarted
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"id": "group-1"})
	}))
	t.Cleanup(server.Close)

	pendingReleased := false
	defer func() {
		if !pendingReleased {
			close(releasePending)
		}
	}()

	maxRetries := 0
	client := &APIClient{
		ProviderVersion:      "test",
		Client:               openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
		requestTimeout:       time.Second,
		slowRequestThreshold: time.Millisecond,
		requestMaxRetries:    &maxRetries,
		requestObserver: func(observation requestObservation) {
			switch observation.Phase {
			case requestObservationPending:
				close(pendingStarted)
				<-releasePending
			case requestObservationAttempt:
				close(attemptCompleted)
			case requestObservationLifecycle:
				close(lifecycleCompleted)
			}
		},
	}

	requestCompleted := make(chan error, 1)
	go func() {
		_, err := client.Request(context.Background(), http.MethodGet, "/organization/groups/{group_id}", map[string]string{"group_id": "group-1"}, nil, nil)
		requestCompleted <- err
	}()

	select {
	case <-attemptCompleted:
	case <-time.After(time.Second):
		t.Fatal("HTTP attempt did not complete while the pending observation was blocked")
	}
	select {
	case <-lifecycleCompleted:
		t.Fatal("lifecycle completion overtook the pending observation")
	case <-time.After(25 * time.Millisecond):
	}

	close(releasePending)
	pendingReleased = true
	select {
	case err := <-requestCompleted:
		if err != nil {
			t.Fatalf("Request returned error: %v", err)
		}
	case <-time.After(time.Second):
		t.Fatal("request did not complete after the pending observation was released")
	}
	select {
	case <-lifecycleCompleted:
	case <-time.After(time.Second):
		t.Fatal("lifecycle completion was not observed")
	}
}

func TestClassifyRequestOutcome(t *testing.T) {
	tests := []struct {
		name       string
		err        error
		contextErr error
		statusCode int
		want       string
	}{
		{name: "success", statusCode: http.StatusOK, want: requestOutcomeSuccess},
		{name: "API error", statusCode: http.StatusInternalServerError, want: requestOutcomeAPIError},
		{name: "request error", err: errors.New("transport failed"), want: requestOutcomeRequestError},
		{name: "canceled", err: fmt.Errorf("wrapped: %w", context.Canceled), contextErr: context.Canceled, want: requestOutcomeCanceled},
		{name: "deadline exceeded", err: fmt.Errorf("wrapped: %w", context.DeadlineExceeded), contextErr: context.DeadlineExceeded, want: requestOutcomeDeadline},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := classifyRequestOutcome(test.err, test.contextErr, test.statusCode); got != test.want {
				t.Fatalf("classifyRequestOutcome() = %q, want %q", got, test.want)
			}
		})
	}
}

func TestPaginatedRequestFollowsNextCursor(t *testing.T) {
	calls := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls++
		w.Header().Set("Content-Type", "application/json")
		switch r.URL.Query().Get("after") {
		case "":
			_ = json.NewEncoder(w).Encode(map[string]any{
				"data":     []map[string]any{{"id": "role_1"}},
				"has_more": true,
				"next":     "cursor_2",
			})
		case "cursor_2":
			_ = json.NewEncoder(w).Encode(map[string]any{
				"data":     []map[string]any{{"id": "role_2"}},
				"has_more": false,
				"next":     nil,
			})
		default:
			http.Error(w, "unexpected after cursor", http.StatusBadRequest)
		}
	}))
	t.Cleanup(server.Close)

	client := &APIClient{
		ProviderVersion: "test",
		Client:          openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
	}
	response, err := client.PaginatedRequest(
		context.Background(),
		http.MethodGet,
		"/organization/roles",
		map[string]string{},
		map[string]string{"limit": "1"},
	)
	if err != nil {
		t.Fatalf("PaginatedRequest returned error: %v", err)
	}
	items, err := ResponseObjectList(response, "data", true)
	if err != nil {
		t.Fatalf("ResponseObjectList returned error: %v", err)
	}
	if len(items) != 2 {
		t.Fatalf("expected two merged items, got %#v", items)
	}
	if calls != 2 {
		t.Fatalf("expected two requests, got %d", calls)
	}
}

func TestPaginatedRequestRejectsRepeatedCursor(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data":     []map[string]any{{"id": "role_1"}},
			"has_more": true,
			"next":     "cursor_1",
		})
	}))
	t.Cleanup(server.Close)

	client := &APIClient{
		ProviderVersion: "test",
		Client:          openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
	}
	_, err := client.PaginatedRequest(
		context.Background(),
		http.MethodGet,
		"/organization/roles",
		map[string]string{},
		map[string]string{"limit": "1"},
	)
	if err == nil || !strings.Contains(err.Error(), "pagination cursor repeated") {
		t.Fatalf("expected repeated cursor error, got %v", err)
	}
}

func TestPaginatedRequestRejectsMalformedPageFields(t *testing.T) {
	tests := []struct {
		name     string
		response map[string]any
		want     string
	}{
		{
			name:     "missing data",
			response: map[string]any{"has_more": false},
			want:     "pagination response field \"data\" is missing",
		},
		{
			name:     "wrong type data",
			response: map[string]any{"data": "not-a-list", "has_more": false},
			want:     "pagination response field \"data\" is not a list",
		},
		{
			name:     "wrong type has_more",
			response: map[string]any{"data": []any{}, "has_more": "yes"},
			want:     "pagination response field \"has_more\" is not a bool",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				_ = json.NewEncoder(w).Encode(test.response)
			}))
			t.Cleanup(server.Close)

			client := &APIClient{
				ProviderVersion: "test",
				Client:          openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
			}
			_, err := client.PaginatedRequest(
				context.Background(),
				http.MethodGet,
				"/organization/roles",
				map[string]string{},
				map[string]string{"limit": "1"},
			)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("expected %q error, got %v", test.want, err)
			}
		})
	}
}

func TestPaginatedRequestRejectsMissingCursorWhenMorePagesRemain(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data":     []any{},
			"has_more": true,
		})
	}))
	t.Cleanup(server.Close)

	client := &APIClient{
		ProviderVersion: "test",
		Client:          openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
	}
	_, err := client.PaginatedRequest(
		context.Background(),
		http.MethodGet,
		"/organization/roles",
		map[string]string{},
		map[string]string{"limit": "1"},
	)
	if err == nil || !strings.Contains(err.Error(), "has_more=true without usable cursor") {
		t.Fatalf("expected missing cursor error, got %v", err)
	}
}

func TestCachedPaginatedRequestCoalescesConcurrentCalls(t *testing.T) {
	var calls atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		w.Header().Set("Content-Type", "application/json")
		switch r.URL.Query().Get("after") {
		case "":
			_ = json.NewEncoder(w).Encode(map[string]any{
				"data":     []map[string]any{{"id": "rl-1"}},
				"has_more": true,
				"next":     "rl-1",
			})
		case "rl-1":
			_ = json.NewEncoder(w).Encode(map[string]any{
				"data":     []map[string]any{{"id": "rl-2"}},
				"has_more": false,
			})
		default:
			http.Error(w, "unexpected after cursor", http.StatusBadRequest)
		}
	}))
	t.Cleanup(server.Close)

	client := &APIClient{
		ProviderVersion: "test",
		Client:          openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
	}
	const workers = 32
	start := make(chan struct{})
	results := make(chan map[string]any, workers)
	errors := make(chan error, workers)
	var wait sync.WaitGroup
	for range workers {
		wait.Add(1)
		go func() {
			defer wait.Done()
			<-start
			response, err := client.CachedPaginatedRequest(
				context.Background(),
				"project_rate_limits",
				[]string{"project_id"},
				http.MethodGet,
				"/organization/projects/{project_id}/rate_limits",
				map[string]string{"project_id": "proj-1"},
				map[string]string{"limit": "1"},
			)
			if err != nil {
				errors <- err
				return
			}
			results <- response
		}()
	}
	close(start)
	wait.Wait()
	close(results)
	close(errors)

	for err := range errors {
		t.Fatalf("CachedPaginatedRequest returned error: %v", err)
	}
	for response := range results {
		items, err := ResponseObjectList(response, "data", true)
		if err != nil || len(items) != 2 {
			t.Fatalf("unexpected cached response: %#v, err=%v", response, err)
		}
	}
	if calls.Load() != 2 {
		t.Fatalf("expected one two-page traversal, got %d requests", calls.Load())
	}
}

func TestCachedPaginatedRequestSupportsSingletonCache(t *testing.T) {
	var calls atomic.Int64
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data":     []map[string]any{{"id": "proj-1"}},
			"has_more": false,
		})
	}))
	t.Cleanup(server.Close)

	client := &APIClient{
		ProviderVersion: "test",
		Client:          openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
	}
	load := func() (map[string]any, error) {
		return client.CachedPaginatedRequest(
			context.Background(),
			"organization_projects",
			nil,
			http.MethodGet,
			"/organization/projects",
			map[string]string{},
			map[string]string{"limit": "100"},
		)
	}

	for range 2 {
		response, err := load()
		if err != nil {
			t.Fatalf("CachedPaginatedRequest returned error: %v", err)
		}
		items, err := ResponseObjectList(response, "data", true)
		if err != nil || len(items) != 1 || items[0]["id"] != "proj-1" {
			t.Fatalf("unexpected cached response: %#v, err=%v", response, err)
		}
	}
	if calls.Load() != 1 {
		t.Fatalf("expected one singleton cache load, got %d requests", calls.Load())
	}

	if err := client.InvalidateResponseCache("organization_projects", nil, map[string]string{}); err != nil {
		t.Fatalf("InvalidateResponseCache returned error: %v", err)
	}
	if _, err := load(); err != nil {
		t.Fatalf("CachedPaginatedRequest after invalidation returned error: %v", err)
	}
	if calls.Load() != 2 {
		t.Fatalf("expected singleton cache invalidation to reload, got %d requests", calls.Load())
	}
}

func TestCachedPaginatedRequestRetriesAfterInFlightInvalidation(t *testing.T) {
	var calls atomic.Int64
	firstStarted := make(chan struct{})
	releaseFirst := make(chan struct{})
	var releaseFirstOnce sync.Once
	release := func() { releaseFirstOnce.Do(func() { close(releaseFirst) }) }
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		call := calls.Add(1)
		if call == 1 {
			close(firstStarted)
			<-releaseFirst
		}
		w.Header().Set("Content-Type", "application/json")
		id := "rl-new"
		if call == 1 {
			id = "rl-old"
		}
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data":     []map[string]any{{"id": id}},
			"has_more": false,
		})
	}))
	t.Cleanup(server.Close)
	t.Cleanup(release)

	client := &APIClient{
		ProviderVersion: "test",
		Client:          openai.NewClient(option.WithAPIKey("test"), option.WithBaseURL(server.URL)),
	}
	pathParams := map[string]string{"project_id": "proj-1"}
	load := func() (map[string]any, error) {
		return client.CachedPaginatedRequest(
			context.Background(),
			"project_rate_limits",
			[]string{"project_id"},
			http.MethodGet,
			"/organization/projects/{project_id}/rate_limits",
			pathParams,
			map[string]string{"limit": "1000"},
		)
	}
	firstResult := make(chan map[string]any, 1)
	firstError := make(chan error, 1)
	go func() {
		response, err := load()
		firstResult <- response
		firstError <- err
	}()
	<-firstStarted

	if err := client.InvalidateResponseCache(
		"project_rate_limits", []string{"project_id"}, pathParams,
	); err != nil {
		t.Fatalf("InvalidateResponseCache returned error: %v", err)
	}
	second, err := load()
	release()
	if err != nil {
		t.Fatalf("second CachedPaginatedRequest returned error: %v", err)
	}
	first := <-firstResult
	if err := <-firstError; err != nil {
		t.Fatalf("first CachedPaginatedRequest returned error: %v", err)
	}

	for name, response := range map[string]map[string]any{"first": first, "second": second} {
		items, err := ResponseObjectList(response, "data", true)
		if err != nil || len(items) != 1 || items[0]["id"] != "rl-new" {
			t.Fatalf("%s request returned stale data: %#v, err=%v", name, response, err)
		}
	}
	third, err := load()
	if err != nil {
		t.Fatalf("third CachedPaginatedRequest returned error: %v", err)
	}
	items, err := ResponseObjectList(third, "data", true)
	if err != nil || len(items) != 1 || items[0]["id"] != "rl-new" {
		t.Fatalf("third request returned unexpected data: %#v, err=%v", third, err)
	}
	if calls.Load() != 2 {
		t.Fatalf("expected two traversals across invalidation, got %d requests", calls.Load())
	}
}

func TestResponseCacheRetriesAfterLateInvalidation(t *testing.T) {
	cache := &responseCache{}
	key := responseCacheKey{name: "project_rate_limits", values: "proj-1"}
	var loads atomic.Int64
	cache.testHookAfterLoadPublished = func(publishedKey responseCacheKey) {
		if publishedKey == key && loads.Load() == 1 {
			cache.invalidate(key)
		}
	}

	response, err := cache.get(context.Background(), key, func(context.Context) (map[string]any, error) {
		load := loads.Add(1)
		id := "rl-new"
		if load == 1 {
			id = "rl-old"
		}
		return map[string]any{"data": []any{map[string]any{"id": id}}}, nil
	})
	if err != nil {
		t.Fatalf("response cache get returned error: %v", err)
	}
	items, err := ResponseObjectList(response, "data", true)
	if err != nil || len(items) != 1 || items[0]["id"] != "rl-new" {
		t.Fatalf("late invalidation returned stale data: %#v, err=%v", response, err)
	}
	if loads.Load() != 2 {
		t.Fatalf("expected late invalidation to force one retry, got %d loads", loads.Load())
	}
}

func TestResponseCacheEvictsLeastRecentlyUsedEntry(t *testing.T) {
	cache := &responseCache{maxEntries: 2}
	loads := map[string]int{}
	read := func(projectID string) {
		t.Helper()
		key := responseCacheKey{name: "project_rate_limits", values: projectID}
		_, err := cache.get(context.Background(), key, func(context.Context) (map[string]any, error) {
			loads[projectID]++
			return map[string]any{"project_id": projectID}, nil
		})
		if err != nil {
			t.Fatalf("cache read for %s returned error: %v", projectID, err)
		}
	}

	read("proj-a")
	read("proj-b")
	read("proj-a")
	read("proj-c")
	read("proj-a")
	read("proj-b")

	if loads["proj-a"] != 1 || loads["proj-b"] != 2 || loads["proj-c"] != 1 {
		t.Fatalf("unexpected loads after LRU eviction: %#v", loads)
	}
	cache.mu.Lock()
	retainedEntries := cache.lru.Len()
	trackedEntries := len(cache.entries)
	cache.mu.Unlock()
	if retainedEntries != 2 || trackedEntries != 2 {
		t.Fatalf("expected cache to retain two completed entries, got lru=%d tracked=%d", retainedEntries, trackedEntries)
	}
}

func TestResponseCacheRetriesReaderOfEvictedEntry(t *testing.T) {
	cache := &responseCache{maxEntries: 1}
	keyA := responseCacheKey{name: "project_rate_limits", values: "proj-a"}
	keyB := responseCacheKey{name: "project_rate_limits", values: "proj-b"}
	entryA, loaded := cache.acquire(keyA)
	if loaded {
		t.Fatal("expected project A to start as a cache miss")
	}
	cache.finishLoad(entryA, map[string]any{"project_id": "proj-a"}, nil, false)
	acquiredA, loaded := cache.acquire(keyA)
	if !loaded || acquiredA != entryA {
		t.Fatal("expected project A to be acquired from the cache")
	}

	entryB, loaded := cache.acquire(keyB)
	if loaded {
		t.Fatal("expected project B to start as a cache miss")
	}
	cache.finishLoad(entryB, map[string]any{"project_id": "proj-b"}, nil, false)
	cache.invalidate(keyA)

	if _, _, retry := cache.result(context.Background(), acquiredA, true); !retry {
		t.Fatal("expected a reader of an evicted entry to retry")
	}
}

func TestResponseCacheDoesNotCacheErrors(t *testing.T) {
	cache := &responseCache{}
	key := responseCacheKey{name: "project_rate_limits", values: "proj-1"}
	loads := 0
	load := func(context.Context) (map[string]any, error) {
		loads++
		if loads == 1 {
			return nil, context.Canceled
		}
		return map[string]any{"data": []any{}}, nil
	}

	if _, err := cache.get(context.Background(), key, load); err == nil {
		t.Fatal("expected first cache load to fail")
	}
	if _, err := cache.get(context.Background(), key, load); err != nil {
		t.Fatalf("expected failed load to be retried, got %v", err)
	}
	if loads != 2 {
		t.Fatalf("expected two loads, got %d", loads)
	}
}

type observedDoneContext struct {
	context.Context
	once     sync.Once
	observed chan struct{}
}

func (c *observedDoneContext) Done() <-chan struct{} {
	c.once.Do(func() { close(c.observed) })
	return c.Context.Done()
}

func TestResponseCacheRetriesWhenLoaderContextIsCanceled(t *testing.T) {
	cache := &responseCache{}
	key := responseCacheKey{name: "project_rate_limits", values: "proj-1"}
	firstContext, cancelFirst := context.WithCancel(context.Background())
	t.Cleanup(cancelFirst)
	firstStarted := make(chan struct{})
	firstError := make(chan error, 1)
	go func() {
		_, err := cache.get(firstContext, key, func(ctx context.Context) (map[string]any, error) {
			close(firstStarted)
			<-ctx.Done()
			return nil, ctx.Err()
		})
		firstError <- err
	}()
	<-firstStarted

	waiterObserved := make(chan struct{})
	waiterContext := &observedDoneContext{
		Context:  context.Background(),
		observed: waiterObserved,
	}
	waiterResult := make(chan map[string]any, 1)
	waiterError := make(chan error, 1)
	loads := atomic.Int64{}
	go func() {
		response, err := cache.get(waiterContext, key, func(context.Context) (map[string]any, error) {
			loads.Add(1)
			return map[string]any{"data": []any{map[string]any{"id": "rl-fresh"}}}, nil
		})
		waiterResult <- response
		waiterError <- err
	}()
	<-waiterObserved

	cancelFirst()
	if err := <-firstError; !errors.Is(err, context.Canceled) {
		t.Fatalf("expected canceled first load, got %v", err)
	}
	response := <-waiterResult
	if err := <-waiterError; err != nil {
		t.Fatalf("live waiter inherited loader cancellation: %v", err)
	}
	items, err := ResponseObjectList(response, "data", true)
	if err != nil || len(items) != 1 || items[0]["id"] != "rl-fresh" {
		t.Fatalf("live waiter returned unexpected response: %#v, err=%v", response, err)
	}
	if loads.Load() != 1 {
		t.Fatalf("expected one retry by the live waiter, got %d", loads.Load())
	}
}

func TestResponseCacheRetainsSuccessfulLoadWhenLoaderContextEnds(t *testing.T) {
	cache := &responseCache{}
	key := responseCacheKey{name: "project_rate_limits", values: "proj-1"}
	loaderContext, cancelLoader := context.WithCancel(context.Background())
	t.Cleanup(cancelLoader)

	response, err := cache.get(loaderContext, key, func(context.Context) (map[string]any, error) {
		cancelLoader()
		return map[string]any{"data": []any{map[string]any{"id": "rl-success"}}}, nil
	})
	if err != nil {
		t.Fatalf("successful load returned error: %v", err)
	}
	items, err := ResponseObjectList(response, "data", true)
	if err != nil || len(items) != 1 || items[0]["id"] != "rl-success" {
		t.Fatalf("successful load returned unexpected response: %#v, err=%v", response, err)
	}

	entry, loaded := cache.acquire(key)
	if !loaded {
		t.Fatal("expected successful load to remain cached")
	}
	cached, cachedErr, retry := cache.result(context.Background(), entry, true)
	if retry {
		t.Fatal("successful load was misclassified as loader cancellation")
	}
	if cachedErr != nil {
		t.Fatalf("cached successful load returned error: %v", cachedErr)
	}
	items, err = ResponseObjectList(cached, "data", true)
	if err != nil || len(items) != 1 || items[0]["id"] != "rl-success" {
		t.Fatalf("cached successful load returned unexpected response: %#v, err=%v", cached, err)
	}
}

func TestResponseCacheSharesLoaderLocalDeadline(t *testing.T) {
	cache := &responseCache{}
	key := responseCacheKey{name: "project_rate_limits", values: "proj-1"}
	firstStarted := make(chan struct{})
	releaseFirst := make(chan struct{})
	var loads atomic.Int64
	var firstStartedOnce sync.Once
	load := func(context.Context) (map[string]any, error) {
		loads.Add(1)
		firstStartedOnce.Do(func() { close(firstStarted) })
		<-releaseFirst
		return nil, context.DeadlineExceeded
	}

	firstError := make(chan error, 1)
	go func() {
		_, err := cache.get(context.Background(), key, load)
		firstError <- err
	}()
	<-firstStarted

	waiterObserved := make(chan struct{})
	waiterContext := &observedDoneContext{
		Context:  context.Background(),
		observed: waiterObserved,
	}
	waiterError := make(chan error, 1)
	go func() {
		_, err := cache.get(waiterContext, key, load)
		waiterError <- err
	}()
	<-waiterObserved

	close(releaseFirst)
	if err := <-firstError; !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("expected first loader deadline, got %v", err)
	}
	if err := <-waiterError; !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("expected waiter to share loader-local deadline, got %v", err)
	}
	if loads.Load() != 1 {
		t.Fatalf("expected one shared loader-local deadline, got %d loads", loads.Load())
	}
}

func TestResponseCacheKeysAreIsolatedDuringInvalidation(t *testing.T) {
	cache := &responseCache{}
	keyForProject := func(projectID string) responseCacheKey {
		t.Helper()
		key, err := buildResponseCacheKey(
			"project_rate_limits",
			map[string]string{"project_id": projectID},
			[]string{"project_id"},
		)
		if err != nil {
			t.Fatalf("buildResponseCacheKey returned error: %v", err)
		}
		return key
	}
	keyA := keyForProject("proj-a")
	keyB := keyForProject("proj-b")
	loads := map[string]int{}
	read := func(key responseCacheKey, projectID string) {
		t.Helper()
		_, err := cache.get(context.Background(), key, func(context.Context) (map[string]any, error) {
			loads[projectID]++
			return map[string]any{"project_id": projectID}, nil
		})
		if err != nil {
			t.Fatalf("cache read for %s returned error: %v", projectID, err)
		}
	}

	read(keyA, "proj-a")
	read(keyB, "proj-b")
	read(keyA, "proj-a")
	read(keyB, "proj-b")
	cache.invalidate(keyA)
	read(keyA, "proj-a")
	read(keyB, "proj-b")

	if loads["proj-a"] != 2 || loads["proj-b"] != 1 {
		t.Fatalf("unexpected per-project cache loads: %#v", loads)
	}
}

func BenchmarkResponseCacheRetainedHeap(b *testing.B) {
	const rateLimitsPerProject = 3000
	b.ReportAllocs()

	for range b.N {
		cache := &responseCache{}
		runtime.GC()
		var before runtime.MemStats
		runtime.ReadMemStats(&before)

		for project := 0; project < defaultResponseCacheMaxEntries+1; project++ {
			limits := make([]any, rateLimitsPerProject)
			for limit := range rateLimitsPerProject {
				limits[limit] = map[string]any{
					"object":                           "project.rate_limit",
					"id":                               fmt.Sprintf("rl-%d-%d", project, limit),
					"model":                            fmt.Sprintf("model-%d-%d", project, limit),
					"max_requests_per_1_minute":        float64(limit + 1),
					"max_tokens_per_1_minute":          float64((limit + 1) * 1000),
					"max_images_per_1_minute":          nil,
					"max_audio_megabytes_per_1_minute": nil,
					"max_requests_per_1_day":           nil,
					"batch_1_day_max_input_tokens":     float64((limit + 1) * 10000),
				}
			}
			key := responseCacheKey{
				name:   "project_rate_limits",
				values: fmt.Sprintf("proj-%d", project),
			}
			payload, err := json.Marshal(map[string]any{
				"object":   "list",
				"data":     limits,
				"has_more": false,
				"next":     nil,
			})
			if err != nil {
				b.Fatalf("marshal representative response: %v", err)
			}
			var response map[string]any
			if err := json.Unmarshal(payload, &response); err != nil {
				b.Fatalf("unmarshal representative response: %v", err)
			}
			if _, err := cache.get(context.Background(), key, func(context.Context) (map[string]any, error) {
				return response, nil
			}); err != nil {
				b.Fatalf("cache load returned error: %v", err)
			}
		}

		runtime.GC()
		var after runtime.MemStats
		runtime.ReadMemStats(&after)
		cache.mu.Lock()
		retainedEntries := cache.lru.Len()
		cache.mu.Unlock()
		if retainedEntries != defaultResponseCacheMaxEntries {
			b.Fatalf("expected %d retained entries, got %d", defaultResponseCacheMaxEntries, retainedEntries)
		}

		retainedBytes := int64(after.HeapAlloc) - int64(before.HeapAlloc)
		if retainedBytes < 0 {
			retainedBytes = 0
		}
		b.ReportMetric(float64(retainedBytes)/(1024*1024), "retained-MiB")
		b.ReportMetric(float64(retainedBytes)/float64(retainedEntries), "retained-B/entry")
		b.ReportMetric(float64(retainedEntries), "retained-entries")
		runtime.KeepAlive(cache)
	}
}

func TestAddStringBodyFieldOmitsNullValues(t *testing.T) {
	body := map[string]any{}
	AddStringBodyField(body, "geography", types.StringNull())
	if _, ok := body["geography"]; ok {
		t.Fatalf("expected null create value to be omitted, got %#v", body)
	}

	AddStringBodyField(body, "name", types.StringValue("terraform-managed"))
	if body["name"] != "terraform-managed" {
		t.Fatalf("expected non-null value to be included, got %#v", body)
	}
}

func TestSetBodyFieldCreatesNestedObjects(t *testing.T) {
	body := map[string]any{}
	SetBodyField(body, []string{"notification_channel", "type"}, "email")
	SetBodyField(body, []string{"notification_channel", "recipients"}, []string{"terraform@example.com"})

	channel, ok := body["notification_channel"].(map[string]any)
	if !ok {
		t.Fatalf("expected nested notification channel body, got %#v", body)
	}
	if channel["type"] != "email" {
		t.Fatalf("expected nested type, got %#v", body)
	}
	recipients, ok := channel["recipients"].([]string)
	if !ok || len(recipients) != 1 || recipients[0] != "terraform@example.com" {
		t.Fatalf("expected nested recipients, got %#v", body)
	}
}

func TestAddInt64BodyFieldIncludesIntegerValues(t *testing.T) {
	body := map[string]any{}
	AddInt64BodyField(body, "threshold_amount", types.Int64Value(1000))
	if body["threshold_amount"] != int64(1000) {
		t.Fatalf("expected int64 body value, got %#v", body)
	}
}

func TestAddNullableStringBodyFieldForUpdateSendsNullOnlyForClears(t *testing.T) {
	body := map[string]any{}
	AddNullableStringBodyFieldForUpdate(body, "geography", types.StringNull(), types.StringNull())
	if _, ok := body["geography"]; ok {
		t.Fatalf("expected unchanged null update value to be omitted, got %#v", body)
	}

	AddNullableStringBodyFieldForUpdate(body, "external_key_id", types.StringNull(), types.StringValue("key_123"))
	value, ok := body["external_key_id"]
	if !ok || value != nil {
		t.Fatalf("expected explicit null clear, got %#v", body)
	}

	AddNullableStringBodyFieldForUpdate(body, "description", types.StringValue("updated"), types.StringValue("old"))
	if body["description"] != "updated" {
		t.Fatalf("expected update value to be included, got %#v", body)
	}
}

func TestApplyStringResponseFieldRequiresIdentityValue(t *testing.T) {
	var value types.String
	err := ApplyStringResponseField(map[string]any{}, []string{"id"}, &value, true)
	if err == nil || !strings.Contains(err.Error(), "missing required response field") {
		t.Fatalf("expected missing required response field error, got %v", err)
	}
}

func TestApplyStringResponseFieldRejectsMalformedValue(t *testing.T) {
	var value types.String
	err := ApplyStringResponseField(map[string]any{"id": []any{"not-a-string"}}, []string{"id"}, &value, true)
	if err == nil || !strings.Contains(err.Error(), "not a string-compatible value") {
		t.Fatalf("expected malformed string response field error, got %v", err)
	}
}

func TestApplyStringResponseFieldMissingOptionalPreservesKnownValue(t *testing.T) {
	value := types.StringValue("extkey_existing")
	err := ApplyStringResponseField(map[string]any{}, []string{"external_key_id"}, &value, false)
	if err != nil {
		t.Fatalf("ApplyStringResponseField returned error: %v", err)
	}
	if value.ValueString() != "extkey_existing" {
		t.Fatalf("expected missing optional response field to preserve known value, got %#v", value)
	}
}

func TestApplyInt64ResponseFieldMissingOptionalClearsUnknown(t *testing.T) {
	value := types.Int64Unknown()
	err := ApplyInt64ResponseField(map[string]any{}, []string{"limit"}, &value, false)
	if err != nil {
		t.Fatalf("ApplyInt64ResponseField returned error: %v", err)
	}
	if !value.IsNull() {
		t.Fatalf("expected missing optional unknown value to become null, got %#v", value)
	}
}

func TestResponseObjectListRejectsMalformedItems(t *testing.T) {
	_, err := ResponseObjectList(map[string]any{"data": []any{"not-an-object"}}, "data", true)
	if err == nil || !strings.Contains(err.Error(), "item 0 is not an object") {
		t.Fatalf("expected malformed response object list error, got %v", err)
	}
}

func TestResponseObjectByFieldSelectsMatchingItem(t *testing.T) {
	response := map[string]any{
		"data": []any{
			map[string]any{"id": "alert_1", "threshold_amount": float64(1000)},
			map[string]any{"id": "alert_2", "threshold_amount": float64(2000)},
		},
	}
	item, found, err := ResponseObjectByField(response, "data", "id", "alert_2")
	if err != nil {
		t.Fatalf("ResponseObjectByField returned error: %v", err)
	}
	if !found {
		t.Fatalf("expected item to be found")
	}
	if item["threshold_amount"] != float64(2000) {
		t.Fatalf("unexpected selected item: %#v", item)
	}
}
