// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectratelimits

import (
	"context"
	"fmt"
	"net/http"
	"sort"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ resource.Resource = &ProjectRateLimitsResource{}
var _ resource.ResourceWithConfigure = &ProjectRateLimitsResource{}
var _ resource.ResourceWithImportState = &ProjectRateLimitsResource{}

type ProjectRateLimitsResource struct {
	client *openaiapi.APIClient
}

type ProjectRateLimitsResourceModel struct {
	ProjectID  types.String `tfsdk:"project_id"`
	RateLimits types.Map    `tfsdk:"rate_limits"`
}

type ProjectRateLimitModel struct {
	RateLimitID                 types.String `tfsdk:"rate_limit_id"`
	MaxRequestsPer1Minute       types.Int64  `tfsdk:"max_requests_per_1_minute"`
	MaxTokensPer1Minute         types.Int64  `tfsdk:"max_tokens_per_1_minute"`
	MaxImagesPer1Minute         types.Int64  `tfsdk:"max_images_per_1_minute"`
	MaxAudioMegabytesPer1Minute types.Int64  `tfsdk:"max_audio_megabytes_per_1_minute"`
	MaxRequestsPer1Day          types.Int64  `tfsdk:"max_requests_per_1_day"`
	Batch1DayMaxInputTokens     types.Int64  `tfsdk:"batch_1_day_max_input_tokens"`
}

var projectRateLimitObjectType = types.ObjectType{AttrTypes: map[string]attr.Type{
	"rate_limit_id":                    types.StringType,
	"max_requests_per_1_minute":        types.Int64Type,
	"max_tokens_per_1_minute":          types.Int64Type,
	"max_images_per_1_minute":          types.Int64Type,
	"max_audio_megabytes_per_1_minute": types.Int64Type,
	"max_requests_per_1_day":           types.Int64Type,
	"batch_1_day_max_input_tokens":     types.Int64Type,
}}

func NewProjectRateLimitsResource() resource.Resource {
	return &ProjectRateLimitsResource{}
}

func (r *ProjectRateLimitsResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "openai_project_rate_limits"
}

func (r *ProjectRateLimitsResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Deprecated. Manage existing project rate limits as one resource per project. Use openai_project_rate_limit instead; this resource will be removed in provider v1.0.0.",
		DeprecationMessage:  "openai_project_rate_limits is deprecated. Use one openai_project_rate_limit resource per managed rate limit instead. This resource will be removed in provider v1.0.0.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "Project whose rate limits are managed.",
				Required:            true,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"rate_limits": schema.MapNestedAttribute{
				MarkdownDescription: "Rate limits keyed by public model name. Removing a key stops managing that model and does not reset its remote limits.",
				Required:            true,
				NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
					"rate_limit_id": schema.StringAttribute{
						MarkdownDescription: "Remote rate-limit identifier resolved by the provider.",
						Computed:            true,
					},
					"max_requests_per_1_minute":        schema.Int64Attribute{Optional: true, Computed: true},
					"max_tokens_per_1_minute":          schema.Int64Attribute{Optional: true, Computed: true},
					"max_images_per_1_minute":          schema.Int64Attribute{Optional: true, Computed: true},
					"max_audio_megabytes_per_1_minute": schema.Int64Attribute{Optional: true, Computed: true},
					"max_requests_per_1_day":           schema.Int64Attribute{Optional: true, Computed: true},
					"batch_1_day_max_input_tokens":     schema.Int64Attribute{Optional: true, Computed: true},
				}},
			},
		},
	}
}

func (r *ProjectRateLimitsResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *ProjectRateLimitsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ProjectRateLimitsResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() || r.client == nil {
		if r.client == nil && !resp.Diagnostics.HasError() {
			resp.Diagnostics.AddError("OpenAI API client unavailable", "The provider was not configured before the resource operation.")
		}
		return
	}
	desired, decodeDiags := projectRateLimitEntries(ctx, data.RateLimits)
	resp.Diagnostics.Append(decodeDiags...)
	if decodeDiags.HasError() {
		return
	}
	remote, readDiags, readErr := r.readProjectRateLimits(ctx, data.ProjectID.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if readErr != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", readErr.Error())
		return
	}
	if readDiags.HasError() {
		return
	}
	attempted, writeDiags := r.writeProjectRateLimitChanges(ctx, data.ProjectID.ValueString(), desired, remote)
	resp.Diagnostics.Append(writeDiags...)
	if writeDiags.HasError() && !attempted {
		return
	}
	if attempted {
		authoritative, authoritativeDiags, authoritativeErr := r.readProjectRateLimits(ctx, data.ProjectID.ValueString())
		resp.Diagnostics.Append(authoritativeDiags...)
		if authoritativeErr != nil {
			resp.Diagnostics.AddError("OpenAI API request failed", authoritativeErr.Error())
			return
		}
		if authoritativeDiags.HasError() {
			return
		}
		remote = authoritative
	}
	resp.Diagnostics.Append(setManagedRateLimits(ctx, &data, desired, remote)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectRateLimitsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ProjectRateLimitsResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() || r.client == nil {
		if r.client == nil && !resp.Diagnostics.HasError() {
			resp.Diagnostics.AddError("OpenAI API client unavailable", "The provider was not configured before the resource operation.")
		}
		return
	}
	managed, decodeDiags := projectRateLimitEntries(ctx, data.RateLimits)
	resp.Diagnostics.Append(decodeDiags...)
	if decodeDiags.HasError() {
		return
	}
	remote, readDiags, readErr := r.readProjectRateLimits(ctx, data.ProjectID.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if readErr != nil {
		if openaiapi.IsNotFound(readErr) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", readErr.Error())
		return
	}
	if readDiags.HasError() {
		return
	}
	resp.Diagnostics.Append(setManagedRateLimits(ctx, &data, managed, remote)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectRateLimitsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var planned ProjectRateLimitsResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &planned)...)
	if resp.Diagnostics.HasError() || r.client == nil {
		if r.client == nil && !resp.Diagnostics.HasError() {
			resp.Diagnostics.AddError("OpenAI API client unavailable", "The provider was not configured before the resource operation.")
		}
		return
	}
	desired, desiredDiags := projectRateLimitEntries(ctx, planned.RateLimits)
	resp.Diagnostics.Append(desiredDiags...)
	if desiredDiags.HasError() {
		return
	}
	remote, readDiags, readErr := r.readProjectRateLimits(ctx, planned.ProjectID.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if readErr != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", readErr.Error())
		return
	}
	if readDiags.HasError() {
		return
	}
	attempted, writeDiags := r.writeProjectRateLimitChanges(ctx, planned.ProjectID.ValueString(), desired, remote)
	resp.Diagnostics.Append(writeDiags...)
	if writeDiags.HasError() && !attempted {
		return
	}
	if attempted {
		authoritative, authoritativeDiags, authoritativeErr := r.readProjectRateLimits(ctx, planned.ProjectID.ValueString())
		resp.Diagnostics.Append(authoritativeDiags...)
		if authoritativeErr != nil {
			resp.Diagnostics.AddError("OpenAI API request failed", authoritativeErr.Error())
			return
		}
		if authoritativeDiags.HasError() {
			return
		}
		remote = authoritative
	}
	resp.Diagnostics.Append(setManagedRateLimits(ctx, &planned, desired, remote)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &planned)...)
}

func (r *ProjectRateLimitsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *ProjectRateLimitsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	if err := openaiapi.ValidatePathParameter("project_id", req.ID); err != nil {
		resp.Diagnostics.AddError("Invalid import ID", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("project_id"), req.ID)...)
}

func projectRateLimitEntries(ctx context.Context, value types.Map) (map[string]ProjectRateLimitModel, diag.Diagnostics) {
	entries := map[string]ProjectRateLimitModel{}
	var diagnostics diag.Diagnostics
	if value.IsNull() || value.IsUnknown() {
		return entries, diagnostics
	}
	diagnostics.Append(value.ElementsAs(ctx, &entries, false)...)
	return entries, diagnostics
}

func emptyProjectRateLimitModel() ProjectRateLimitModel {
	return ProjectRateLimitModel{
		RateLimitID:                 types.StringNull(),
		MaxRequestsPer1Minute:       types.Int64Null(),
		MaxTokensPer1Minute:         types.Int64Null(),
		MaxImagesPer1Minute:         types.Int64Null(),
		MaxAudioMegabytesPer1Minute: types.Int64Null(),
		MaxRequestsPer1Day:          types.Int64Null(),
		Batch1DayMaxInputTokens:     types.Int64Null(),
	}
}

func projectRateLimitFromResponse(item map[string]any) (string, ProjectRateLimitModel, error) {
	modelName := types.StringNull()
	result := emptyProjectRateLimitModel()
	if err := openaiapi.ApplyStringResponseField(item, []string{"model"}, &modelName, true); err != nil {
		return "", result, err
	}
	if err := openaiapi.ApplyStringResponseField(item, []string{"id"}, &result.RateLimitID, true); err != nil {
		return "", result, err
	}
	fields := []struct {
		name   string
		target *types.Int64
	}{
		{"max_requests_per_1_minute", &result.MaxRequestsPer1Minute},
		{"max_tokens_per_1_minute", &result.MaxTokensPer1Minute},
		{"max_images_per_1_minute", &result.MaxImagesPer1Minute},
		{"max_audio_megabytes_per_1_minute", &result.MaxAudioMegabytesPer1Minute},
		{"max_requests_per_1_day", &result.MaxRequestsPer1Day},
		{"batch_1_day_max_input_tokens", &result.Batch1DayMaxInputTokens},
	}
	for _, field := range fields {
		if err := openaiapi.ApplyInt64ResponseField(item, []string{field.name}, field.target, false); err != nil {
			return "", result, err
		}
	}
	return modelName.ValueString(), result, nil
}

func (r *ProjectRateLimitsResource) readProjectRateLimits(ctx context.Context, projectID string) (map[string]ProjectRateLimitModel, diag.Diagnostics, error) {
	var diagnostics diag.Diagnostics
	response, err := r.client.PaginatedRequest(ctx, http.MethodGet, "/organization/projects/{project_id}/rate_limits", map[string]string{"project_id": projectID}, map[string]string{"limit": "1000"})
	if err != nil {
		return nil, diagnostics, err
	}
	items, err := openaiapi.ResponseObjectList(response, "data", true)
	if err != nil {
		diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return nil, diagnostics, nil
	}
	result := make(map[string]ProjectRateLimitModel, len(items))
	for index, item := range items {
		modelName, rateLimit, itemErr := projectRateLimitFromResponse(item)
		if itemErr != nil {
			diagnostics.AddError("Invalid OpenAI API response", fmt.Sprintf("rate limit item %d: %v", index, itemErr))
			continue
		}
		if _, exists := result[modelName]; exists {
			diagnostics.AddError("Invalid OpenAI API response", fmt.Sprintf("project rate limits contain duplicate model %q", modelName))
			continue
		}
		result[modelName] = rateLimit
	}
	return result, diagnostics, nil
}

func sortedProjectRateLimitModels(entries map[string]ProjectRateLimitModel) []string {
	models := make([]string, 0, len(entries))
	for modelName := range entries {
		models = append(models, modelName)
	}
	sort.Strings(models)
	return models
}

type projectRateLimitFieldValue struct {
	name    string
	planned types.Int64
	current types.Int64
}

func projectRateLimitFieldValues(planned ProjectRateLimitModel, current ProjectRateLimitModel) []projectRateLimitFieldValue {
	return []projectRateLimitFieldValue{
		{"max_requests_per_1_minute", planned.MaxRequestsPer1Minute, current.MaxRequestsPer1Minute},
		{"max_tokens_per_1_minute", planned.MaxTokensPer1Minute, current.MaxTokensPer1Minute},
		{"max_images_per_1_minute", planned.MaxImagesPer1Minute, current.MaxImagesPer1Minute},
		{"max_audio_megabytes_per_1_minute", planned.MaxAudioMegabytesPer1Minute, current.MaxAudioMegabytesPer1Minute},
		{"max_requests_per_1_day", planned.MaxRequestsPer1Day, current.MaxRequestsPer1Day},
		{"batch_1_day_max_input_tokens", planned.Batch1DayMaxInputTokens, current.Batch1DayMaxInputTokens},
	}
}

func projectRateLimitUpdateBody(planned ProjectRateLimitModel, current ProjectRateLimitModel) (map[string]any, []string) {
	body := map[string]any{}
	unavailable := []string{}
	for _, field := range projectRateLimitFieldValues(planned, current) {
		if field.planned.IsNull() || field.planned.IsUnknown() {
			continue
		}
		if field.current.IsNull() || field.current.IsUnknown() {
			unavailable = append(unavailable, field.name)
			continue
		}
		if field.planned.ValueInt64() != field.current.ValueInt64() {
			body[field.name] = field.planned.ValueInt64()
		}
	}
	return body, unavailable
}

func (r *ProjectRateLimitsResource) invalidateProjectRateLimits(projectID string) error {
	return r.client.InvalidateResponseCache("project_rate_limits", []string{"project_id"}, map[string]string{"project_id": projectID})
}

func (r *ProjectRateLimitsResource) writeProjectRateLimitChanges(ctx context.Context, projectID string, desired map[string]ProjectRateLimitModel, current map[string]ProjectRateLimitModel) (bool, diag.Diagnostics) {
	var diagnostics diag.Diagnostics
	models := sortedProjectRateLimitModels(desired)
	bodies := make(map[string]map[string]any, len(models))
	for _, modelName := range models {
		currentRateLimit, found := current[modelName]
		if !found {
			diagnostics.AddError("Project rate limit not found", fmt.Sprintf("The OpenAI API did not return a rate limit for configured model %q in project %q.", modelName, projectID))
			continue
		}
		body, unavailableFields := projectRateLimitUpdateBody(desired[modelName], currentRateLimit)
		bodies[modelName] = body
		for _, fieldName := range unavailableFields {
			diagnostics.AddAttributeError(path.Root("rate_limits").AtMapKey(modelName).AtName(fieldName), "Project rate limit field unavailable", fmt.Sprintf("The OpenAI API does not expose field %q for configured model %q in project %q.", fieldName, modelName, projectID))
		}
		if len(body) > 0 && (currentRateLimit.RateLimitID.IsNull() || currentRateLimit.RateLimitID.IsUnknown()) {
			diagnostics.AddError("Project rate limit identifier unavailable", fmt.Sprintf("The OpenAI API did not return an identifier for model %q in project %q.", modelName, projectID))
		}
	}
	if diagnostics.HasError() {
		return false, diagnostics
	}
	invalidated := false
	attempted := false
	for _, modelName := range models {
		currentRateLimit := current[modelName]
		body := bodies[modelName]
		if len(body) == 0 {
			continue
		}
		if !invalidated {
			if err := r.invalidateProjectRateLimits(projectID); err != nil {
				diagnostics.AddError("Response cache invalidation failed", err.Error())
				return attempted, diagnostics
			}
			invalidated = true
		}
		attempted = true
		_, err := r.client.Request(ctx, http.MethodPost, "/organization/projects/{project_id}/rate_limits/{rate_limit_id}", map[string]string{
			"project_id":    projectID,
			"rate_limit_id": currentRateLimit.RateLimitID.ValueString(),
		}, map[string]string{}, body)
		if err != nil {
			diagnostics.AddError("OpenAI API request failed", fmt.Sprintf("updating model %q: %v", modelName, err))
			break
		}
	}
	if invalidated {
		if err := r.invalidateProjectRateLimits(projectID); err != nil {
			diagnostics.AddError("Response cache invalidation failed", err.Error())
		}
	}
	return attempted, diagnostics
}

func setManagedRateLimits(ctx context.Context, data *ProjectRateLimitsResourceModel, managed map[string]ProjectRateLimitModel, remote map[string]ProjectRateLimitModel) diag.Diagnostics {
	var diagnostics diag.Diagnostics
	selected := map[string]ProjectRateLimitModel{}
	models := sortedProjectRateLimitModels(managed)
	if data.RateLimits.IsNull() || data.RateLimits.IsUnknown() {
		models = sortedProjectRateLimitModels(remote)
	}
	for _, modelName := range models {
		rateLimit, found := remote[modelName]
		if !found {
			diagnostics.AddError("Project rate limit not found", fmt.Sprintf("The OpenAI API no longer returns the managed model %q.", modelName))
			continue
		}
		selected[modelName] = rateLimit
	}
	value, valueDiags := types.MapValueFrom(ctx, projectRateLimitObjectType, selected)
	diagnostics.Append(valueDiags...)
	if !valueDiags.HasError() {
		data.RateLimits = value
	}
	return diagnostics
}
