// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectserviceaccount

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ resource.Resource = &ProjectServiceAccountResource{}
var _ resource.ResourceWithConfigure = &ProjectServiceAccountResource{}
var _ resource.ResourceWithImportState = &ProjectServiceAccountResource{}

type ProjectServiceAccountResource struct {
	client *openaiapi.APIClient
}

type ProjectServiceAccountResourceModel struct {
	ProjectID        types.String `tfsdk:"project_id"`
	ServiceAccountID types.String `tfsdk:"service_account_id"`
	ID               types.String `tfsdk:"id"`
	Name             types.String `tfsdk:"name"`
	CreatedAt        types.Int64  `tfsdk:"created_at"`
}

func NewProjectServiceAccountResource() resource.Resource {
	return &ProjectServiceAccountResource{}
}

func (r *ProjectServiceAccountResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "openai_project_service_account"
}

func (r *ProjectServiceAccountResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manage a project service account. The API returns an unredacted API key on create, but the Terraform provider does not model or store that key.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "project id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"service_account_id": schema.StringAttribute{
				MarkdownDescription: "service account id",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "id",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "name",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringLengthAtLeast(1),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"created_at": schema.Int64Attribute{
				MarkdownDescription: "created at",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
		},
	}
}

func (r *ProjectServiceAccountResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *ProjectServiceAccountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ProjectServiceAccountResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"project_id": data.ProjectID.ValueString(),
	}
	queryParams := map[string]string{}
	body := map[string]any{}
	openaiapi.SetBodyField(body, []string{"create_service_account_only"}, true)
	openaiapi.AddStringBodyField(body, "name", data.Name)
	responseData, err := r.client.Request(ctx, "POST", "/organization/projects/{project_id}/service_accounts", pathParams, queryParams, body)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ServiceAccountID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"created_at"}, &data.CreatedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectServiceAccountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ProjectServiceAccountResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"project_id":         data.ProjectID.ValueString(),
		"service_account_id": data.ServiceAccountID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.Request(ctx, "GET", "/organization/projects/{project_id}/service_accounts/{service_account_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ServiceAccountID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"created_at"}, &data.CreatedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectServiceAccountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data ProjectServiceAccountResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	resp.Diagnostics.AddError("Unsupported update", "The provider config does not define an update operation for openai_project_service_account. Change replace-only attributes by recreating the resource.")
}

func (r *ProjectServiceAccountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data ProjectServiceAccountResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"project_id":         data.ProjectID.ValueString(),
		"service_account_id": data.ServiceAccountID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.Request(ctx, "DELETE", "/organization/projects/{project_id}/service_accounts/{service_account_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	_ = responseData
	resp.State.RemoveResource(ctx)
}

func (r *ProjectServiceAccountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("Expected import ID format %q.", "{project_id}/{service_account_id}"))
		return
	}
	if err := openaiapi.ValidatePathParameter("project_id", parts[0]); err != nil {
		resp.Diagnostics.AddError("Invalid import ID", err.Error())
		return
	}
	if err := openaiapi.ValidatePathParameter("service_account_id", parts[1]); err != nil {
		resp.Diagnostics.AddError("Invalid import ID", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("project_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("service_account_id"), parts[1])...)
}
