// Code generated by generate-terraform-provider. DO NOT EDIT.

package groupuser

import (
	"context"
	"fmt"

	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &GroupUserDataSource{}
var _ datasource.DataSourceWithConfigure = &GroupUserDataSource{}

type GroupUserDataSource struct {
	client *openaiapi.APIClient
}

type GroupUserDataSourceModel struct {
	GroupID          types.String `tfsdk:"group_id"`
	UserID           types.String `tfsdk:"user_id"`
	ID               types.String `tfsdk:"id"`
	Name             types.String `tfsdk:"name"`
	Email            types.String `tfsdk:"email"`
	IsServiceAccount types.Bool   `tfsdk:"is_service_account"`
	UserType         types.String `tfsdk:"user_type"`
	ResponseJSON     types.String `tfsdk:"response_json"`
}

func NewGroupUserDataSource() datasource.DataSource {
	return &GroupUserDataSource{}
}

func (d *GroupUserDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_group_user"
}

func (d *GroupUserDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Look up a user's membership in an organization group.",
		Attributes: map[string]schema.Attribute{
			"group_id": schema.StringAttribute{
				MarkdownDescription: "group id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"user_id": schema.StringAttribute{
				MarkdownDescription: "user id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "id",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "name",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"email": schema.StringAttribute{
				MarkdownDescription: "email",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"is_service_account": schema.BoolAttribute{
				MarkdownDescription: "is service account",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"user_type": schema.StringAttribute{
				MarkdownDescription: "user type",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
		},
	}
}

func (d *GroupUserDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *GroupUserDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data GroupUserDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"group_id": data.GroupID.ValueString(),
		"user_id":  data.UserID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := d.client.Request(ctx, "GET", "/organization/groups/{group_id}/users/{user_id}", pathParams, queryParams, nil)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	data.ID = types.StringValue(fmt.Sprintf("openai_group_user/%s/%s", data.GroupID.ValueString(), data.UserID.ValueString()))
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"email"}, &data.Email, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_service_account"}, &data.IsServiceAccount, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"user_type"}, &data.UserType, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
