// Code generated by generate-terraform-provider. DO NOT EDIT.

package organizationuser

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ resource.Resource = &OrganizationUserResource{}
var _ resource.ResourceWithConfigure = &OrganizationUserResource{}
var _ resource.ResourceWithImportState = &OrganizationUserResource{}

type OrganizationUserResource struct {
	client *openaiapi.APIClient
}

type OrganizationUserResourceModel struct {
	UserID                         types.String `tfsdk:"user_id"`
	ID                             types.String `tfsdk:"id"`
	Name                           types.String `tfsdk:"name"`
	Email                          types.String `tfsdk:"email"`
	Role                           types.String `tfsdk:"role"`
	AddedAt                        types.Int64  `tfsdk:"added_at"`
	IsDefault                      types.Bool   `tfsdk:"is_default"`
	Created                        types.Int64  `tfsdk:"created"`
	IsServiceAccount               types.Bool   `tfsdk:"is_service_account"`
	IsScaleTierAuthorizedPurchaser types.Bool   `tfsdk:"is_scale_tier_authorized_purchaser"`
	IsScimManaged                  types.Bool   `tfsdk:"is_scim_managed"`
	APIKeyLastUsedAt               types.Int64  `tfsdk:"api_key_last_used_at"`
	TechnicalLevel                 types.String `tfsdk:"technical_level"`
	DeveloperPersona               types.String `tfsdk:"developer_persona"`
}

func NewOrganizationUserResource() resource.Resource {
	return &OrganizationUserResource{}
}

func (r *OrganizationUserResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "openai_organization_user"
}

func (r *OrganizationUserResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manage an existing organization user. This resource is import-only; configuration alone cannot create a user. Import an existing organization user before Terraform can manage update or delete behavior.",
		Attributes: map[string]schema.Attribute{
			"user_id": schema.StringAttribute{
				MarkdownDescription: "user id",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "id",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "name",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"email": schema.StringAttribute{
				MarkdownDescription: "email",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"role": schema.StringAttribute{
				MarkdownDescription: "role",
				Required:            false,
				Optional:            true,
				Computed:            true,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringOneOf("owner", "reader"),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"added_at": schema.Int64Attribute{
				MarkdownDescription: "added at",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"is_default": schema.BoolAttribute{
				MarkdownDescription: "is default",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"created": schema.Int64Attribute{
				MarkdownDescription: "created",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"is_service_account": schema.BoolAttribute{
				MarkdownDescription: "is service account",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"is_scale_tier_authorized_purchaser": schema.BoolAttribute{
				MarkdownDescription: "is scale tier authorized purchaser",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"is_scim_managed": schema.BoolAttribute{
				MarkdownDescription: "is scim managed",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"api_key_last_used_at": schema.Int64Attribute{
				MarkdownDescription: "api key last used at",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"technical_level": schema.StringAttribute{
				MarkdownDescription: "technical level",
				Required:            false,
				Optional:            true,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"developer_persona": schema.StringAttribute{
				MarkdownDescription: "developer persona",
				Required:            false,
				Optional:            true,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *OrganizationUserResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *OrganizationUserResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data OrganizationUserResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	resp.Diagnostics.AddError("Unsupported create", "The provider config does not define a create operation for openai_organization_user.")
}

func (r *OrganizationUserResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data OrganizationUserResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"user_id": data.UserID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.Request(ctx, "GET", "/organization/users/{user_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.UserID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"email"}, &data.Email, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"role"}, &data.Role, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"added_at"}, &data.AddedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_default"}, &data.IsDefault, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"created"}, &data.Created, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_service_account"}, &data.IsServiceAccount, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_scale_tier_authorized_purchaser"}, &data.IsScaleTierAuthorizedPurchaser, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_scim_managed"}, &data.IsScimManaged, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"api_key_last_used_at"}, &data.APIKeyLastUsedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"technical_level"}, &data.TechnicalLevel, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"developer_persona"}, &data.DeveloperPersona, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OrganizationUserResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data OrganizationUserResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var stateData OrganizationUserResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &stateData)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"user_id": data.UserID.ValueString(),
	}
	queryParams := map[string]string{}
	body := map[string]any{}
	openaiapi.AddNullableStringBodyFieldForUpdate(body, "role", data.Role, stateData.Role)
	openaiapi.AddNullableStringBodyFieldForUpdate(body, "technical_level", data.TechnicalLevel, stateData.TechnicalLevel)
	openaiapi.AddNullableStringBodyFieldForUpdate(body, "developer_persona", data.DeveloperPersona, stateData.DeveloperPersona)
	responseData, err := r.client.Request(ctx, "POST", "/organization/users/{user_id}", pathParams, queryParams, body)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.UserID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"email"}, &data.Email, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"role"}, &data.Role, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"added_at"}, &data.AddedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_default"}, &data.IsDefault, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"created"}, &data.Created, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_service_account"}, &data.IsServiceAccount, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_scale_tier_authorized_purchaser"}, &data.IsScaleTierAuthorizedPurchaser, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_scim_managed"}, &data.IsScimManaged, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"api_key_last_used_at"}, &data.APIKeyLastUsedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"technical_level"}, &data.TechnicalLevel, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"developer_persona"}, &data.DeveloperPersona, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OrganizationUserResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data OrganizationUserResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"user_id": data.UserID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := r.client.Request(ctx, "DELETE", "/organization/users/{user_id}", pathParams, queryParams, nil)
	if err != nil {
		if openaiapi.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	_ = responseData
	resp.State.RemoveResource(ctx)
}

func (r *OrganizationUserResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, "/")
	if len(parts) != 1 {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("Expected import ID format %q.", "{user_id}"))
		return
	}
	if err := openaiapi.ValidatePathParameter("user_id", parts[0]); err != nil {
		resp.Diagnostics.AddError("Invalid import ID", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("user_id"), parts[0])...)
}
