// Code generated by generate-terraform-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/openai/openai-go/v3/option"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

const testAdminAPIKey = "sk-admin-synthetic-test-secret"

func configureProviderWithBaseURL(t *testing.T, baseURL string, explicit bool) provider.ConfigureResponse {
	t.Helper()

	ctx := context.Background()
	configuredProvider := &OpenAIProvider{version: "test"}
	var schemaResponse provider.SchemaResponse
	configuredProvider.Schema(ctx, provider.SchemaRequest{}, &schemaResponse)

	attributeTypes := make(map[string]tftypes.Type, len(schemaResponse.Schema.Attributes))
	attributeValues := make(map[string]tftypes.Value, len(schemaResponse.Schema.Attributes))
	for name := range schemaResponse.Schema.Attributes {
		attributeTypes[name] = tftypes.String
		attributeValues[name] = tftypes.NewValue(tftypes.String, nil)
	}
	attributeValues["admin_api_key"] = tftypes.NewValue(tftypes.String, testAdminAPIKey)
	if explicit {
		attributeValues["base_url"] = tftypes.NewValue(tftypes.String, baseURL)
	}

	request := provider.ConfigureRequest{
		Config: tfsdk.Config{
			Raw: tftypes.NewValue(tftypes.Object{
				AttributeTypes: attributeTypes,
			}, attributeValues),
			Schema: schemaResponse.Schema,
		},
	}
	var response provider.ConfigureResponse
	configuredProvider.Configure(ctx, request, &response)
	return response
}

func TestProviderConfigureAPIBaseURL(t *testing.T) {
	tests := []struct {
		name     string
		baseURL  string
		explicit bool
		wantErr  bool
	}{
		{name: "default OpenAI HTTPS origin"},
		{name: "approved custom HTTPS origin", baseURL: "https://proxy.example.com/v1", explicit: true},
		{name: "approved custom HTTPS origin with port", baseURL: "https://proxy.example.com:8443/v1", explicit: true},
		{name: "localhost HTTP test server", baseURL: "http://localhost:8080/v1", explicit: true},
		{name: "IPv4 loopback HTTP test server", baseURL: "http://127.0.0.1:8080/v1", explicit: true},
		{name: "alternate IPv4 loopback HTTP test server", baseURL: "http://127.0.0.42:8080/v1", explicit: true},
		{name: "IPv6 loopback HTTP test server", baseURL: "http://[::1]:8080/v1", explicit: true},
		{name: "remote plaintext HTTP origin", baseURL: "http://example.com/v1", explicit: true, wantErr: true},
		{name: "remote plaintext IPv4 origin", baseURL: "http://192.0.2.1/v1", explicit: true, wantErr: true},
		{name: "localhost lookalike origin", baseURL: "http://localhost.example.com/v1", explicit: true, wantErr: true},
		{name: "relative URL", baseURL: "/v1", explicit: true, wantErr: true},
		{name: "malformed URL", baseURL: "https://%zz.example.com/v1", explicit: true, wantErr: true},
		{name: "malformed multi-colon authority", baseURL: "https://example.com:443:444/v1", explicit: true, wantErr: true},
		{name: "missing URL host", baseURL: "https:///v1", explicit: true, wantErr: true},
		{name: "empty URL hostname", baseURL: "https://:443/v1", explicit: true, wantErr: true},
		{name: "zero HTTPS port", baseURL: "https://proxy.example.com:0/v1", explicit: true, wantErr: true},
		{name: "out of range HTTPS port", baseURL: "https://proxy.example.com:65536/v1", explicit: true, wantErr: true},
		{name: "out of range loopback HTTP port", baseURL: "http://localhost:99999/v1", explicit: true, wantErr: true},
		{name: "lowest valid HTTPS port", baseURL: "https://proxy.example.com:1/v1", explicit: true},
		{name: "highest valid HTTPS port", baseURL: "https://proxy.example.com:65535/v1", explicit: true},
		{name: "unsupported URL scheme", baseURL: "ftp://example.com/v1", explicit: true, wantErr: true},
		{name: "embedded userinfo", baseURL: "https://user:password@api.openai.com/v1", explicit: true, wantErr: true},
		{name: "empty URL", baseURL: "  ", explicit: true, wantErr: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			response := configureProviderWithBaseURL(t, test.baseURL, test.explicit)
			if gotErr := response.Diagnostics.HasError(); gotErr != test.wantErr {
				t.Fatalf("Configure() error = %t, want %t: %v", gotErr, test.wantErr, response.Diagnostics)
			}
			if test.wantErr {
				if response.ResourceData != nil || response.DataSourceData != nil {
					t.Fatal("rejected endpoint received an authenticated API client")
				}
				return
			}
			if response.ResourceData == nil || response.DataSourceData == nil {
				t.Fatal("approved endpoint did not receive an authenticated API client")
			}
		})
	}
}

func TestCredentialAudienceHTTPClientNormalizesRedirectOrigins(t *testing.T) {
	tests := []struct {
		name       string
		baseURL    string
		redirectTo string
		wantErr    bool
	}{
		{name: "HTTPS explicit default port redirects to implicit", baseURL: "https://proxy.example.com:443/v1", redirectTo: "https://proxy.example.com/next"},
		{name: "HTTPS implicit default port redirects to explicit", baseURL: "https://proxy.example.com/v1", redirectTo: "https://proxy.example.com:443/next"},
		{name: "HTTP explicit default port redirects to implicit", baseURL: "http://localhost:80/v1", redirectTo: "http://localhost/next"},
		{name: "HTTP implicit default port redirects to explicit", baseURL: "http://localhost/v1", redirectTo: "http://localhost:80/next"},
		{name: "hostname case is equivalent", baseURL: "https://Proxy.Example.COM:443/v1", redirectTo: "https://proxy.example.com/next"},
		{name: "Unicode hostname redirects to equivalent punycode", baseURL: "https://bücher.example/v1", redirectTo: "https://xn--bcher-kva.example/next"},
		{name: "punycode hostname redirects to equivalent Unicode", baseURL: "https://xn--bcher-kva.example/v1", redirectTo: "https://bücher.example/next"},
		{name: "expanded IPv6 redirects to compressed equivalent", baseURL: "https://[2001:0db8:0000:0000:0000:0000:0000:0001]/v1", redirectTo: "https://[2001:db8::1]/next"},
		{name: "compressed IPv6 redirects to expanded equivalent", baseURL: "https://[2001:db8::1]/v1", redirectTo: "https://[2001:0db8:0:0:0:0:0:1]/next"},
		{name: "expanded IPv6 loopback redirects to compressed", baseURL: "http://[0:0:0:0:0:0:0:1]:80/v1", redirectTo: "http://[::1]/next"},
		{name: "equivalent scoped IPv6 addresses preserve zone", baseURL: "https://[fe80:0:0:0:0:0:0:1%25en0]/v1", redirectTo: "https://[fe80::1%25en0]/next"},
		{name: "distinct Unicode hostname is rejected", baseURL: "https://bücher.example/v1", redirectTo: "https://xn--bcher-kva.other/next", wantErr: true},
		{name: "distinct IPv6 address is rejected", baseURL: "https://[2001:db8::1]/v1", redirectTo: "https://[2001:db8::2]/next", wantErr: true},
		{name: "distinct IPv6 zone is rejected", baseURL: "https://[fe80::1%25en0]/v1", redirectTo: "https://[fe80::1%25en1]/next", wantErr: true},
		{name: "equivalent Unicode hostname with different port is rejected", baseURL: "https://bücher.example:443/v1", redirectTo: "https://xn--bcher-kva.example:444/next", wantErr: true},
		{name: "different explicit port is rejected", baseURL: "https://proxy.example.com:443/v1", redirectTo: "https://proxy.example.com:444/next", wantErr: true},
		{name: "different scheme is rejected", baseURL: "https://localhost/v1", redirectTo: "http://localhost/next", wantErr: true},
		{name: "different hostname is rejected", baseURL: "https://proxy.example.com/v1", redirectTo: "https://other.example.com/next", wantErr: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			endpoint, err := validateAPIBaseURL(test.baseURL)
			if err != nil {
				t.Fatalf("base URL validation failed: %v", err)
			}
			redirect, err := http.NewRequest(http.MethodGet, test.redirectTo, nil)
			if err != nil {
				t.Fatalf("redirect request creation failed: %v", err)
			}
			client := newCredentialAudienceHTTPClient(endpoint)
			if gotErr := client.CheckRedirect(redirect, []*http.Request{{URL: endpoint}}); (gotErr != nil) != test.wantErr {
				t.Fatalf("CheckRedirect() error = %v, want error %t", gotErr, test.wantErr)
			}
		})
	}
}

func TestCredentialAudienceHTTPClientPreservesResponseHeaderTimeout(t *testing.T) {
	endpoint, err := validateAPIBaseURL("https://api.openai.com/v1")
	if err != nil {
		t.Fatalf("default endpoint validation failed: %v", err)
	}
	client := newCredentialAudienceHTTPClient(endpoint)
	transport, ok := client.Transport.(*http.Transport)
	if !ok {
		t.Fatalf("HTTP transport has unexpected type %T", client.Transport)
	}
	if got := transport.ResponseHeaderTimeout; got != 10*time.Minute {
		t.Fatalf("response header timeout = %s, want %s", got, 10*time.Minute)
	}
}

func TestProviderRejectedEndpointNeverReceivesAdminCredentials(t *testing.T) {
	var receivedRequests atomic.Int32
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		receivedRequests.Add(1)
		writer.WriteHeader(http.StatusOK)
	}))
	t.Cleanup(server.Close)

	rejectedURL := strings.Replace(server.URL, "127.0.0.1", "0.0.0.0", 1)
	response := configureProviderWithBaseURL(t, rejectedURL, true)
	if !response.Diagnostics.HasError() {
		t.Fatal("remote plaintext endpoint was unexpectedly accepted")
	}
	if response.ResourceData != nil || response.DataSourceData != nil {
		t.Fatal("rejected endpoint received an authenticated API client")
	}
	if got := receivedRequests.Load(); got != 0 {
		t.Fatalf("rejected endpoint received %d requests", got)
	}
}

func TestProviderRedirectNeverSendsAdminCredentialsToAnotherOrigin(t *testing.T) {
	const rawRedirectCredentials = "example-user:example-password@"
	const rawRedirectQuery = "?X-Amz-Signature=example-signature&token=example-token#example-fragment"
	var redirectedRequests atomic.Int32
	unapprovedServer := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		redirectedRequests.Add(1)
		writer.WriteHeader(http.StatusOK)
	}))
	t.Cleanup(unapprovedServer.Close)

	var approvedRequests atomic.Int32
	var approvedAuthorization atomic.Value
	approvedServer := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		approvedRequests.Add(1)
		approvedAuthorization.Store(request.Header.Get("Authorization"))
		redirectURL := strings.Replace(unapprovedServer.URL, "://", "://"+rawRedirectCredentials, 1) + "/capture" + rawRedirectQuery
		http.Redirect(writer, request, redirectURL, http.StatusTemporaryRedirect)
	}))
	t.Cleanup(approvedServer.Close)

	response := configureProviderWithBaseURL(t, approvedServer.URL, true)
	if response.Diagnostics.HasError() {
		t.Fatalf("approved origin failed configuration: %v", response.Diagnostics)
	}
	client, ok := response.ResourceData.(*openaiapi.APIClient)
	if !ok {
		t.Fatalf("provider client has unexpected type %T", response.ResourceData)
	}

	_, err := client.Request(
		context.Background(), http.MethodGet, "/organization/projects", nil, nil, nil,
	)
	if err == nil || !strings.Contains(err.Error(), "redirect crosses the configured OpenAI API origin") {
		t.Fatalf("cross-origin redirect error = %v", err)
	}
	if strings.Contains(err.Error(), "http: read on closed response body") {
		t.Fatalf("cross-origin redirect error was replaced while buffering: %v", err)
	}
	for _, secret := range []string{
		"example-user",
		"example-password",
		"X-Amz-Signature",
		"example-signature",
		"example-token",
		"example-fragment",
	} {
		if strings.Contains(err.Error(), secret) {
			t.Fatalf("cross-origin redirect error exposed %q: %v", secret, err)
		}
	}
	if !strings.Contains(err.Error(), unapprovedServer.URL+"/capture") {
		t.Fatalf("cross-origin redirect error lost sanitized destination: %v", err)
	}
	if got := approvedRequests.Load(); got != 1 {
		t.Fatalf("approved redirect origin received %d requests, want 1", got)
	}
	if got := approvedAuthorization.Load(); got != "Bearer "+testAdminAPIKey {
		t.Fatalf("approved origin authorization = %v", got)
	}
	if got := redirectedRequests.Load(); got != 0 {
		t.Fatalf("unapproved redirect origin received %d authenticated requests", got)
	}
}

func TestProviderSameOriginRedirectPreservesAdminCredentials(t *testing.T) {
	var receivedAuthorization atomic.Value
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		if request.URL.Path == "/organization/projects" {
			http.Redirect(writer, request, "/approved", http.StatusTemporaryRedirect)
			return
		}
		receivedAuthorization.Store(request.Header.Get("Authorization"))
		writer.Header().Set("Content-Type", "application/json")
		_, _ = fmt.Fprint(writer, "{}")
	}))
	t.Cleanup(server.Close)

	response := configureProviderWithBaseURL(t, server.URL, true)
	if response.Diagnostics.HasError() {
		t.Fatalf("approved origin failed configuration: %v", response.Diagnostics)
	}
	client, ok := response.ResourceData.(*openaiapi.APIClient)
	if !ok {
		t.Fatalf("provider client has unexpected type %T", response.ResourceData)
	}
	if err := client.Client.Get(context.Background(), "/organization/projects", nil, nil, option.WithMaxRetries(0)); err != nil {
		t.Fatalf("same-origin redirect failed: %v", err)
	}
	if got := receivedAuthorization.Load(); got != "Bearer "+testAdminAPIKey {
		t.Fatalf("same-origin redirect authorization = %v", got)
	}
}
