// Code generated by generate-terraform-provider. DO NOT EDIT.

package provider

import (
	"context"
	"os"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openai "github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
	resourcecertificate "github.com/openai/terraform-provider-openai/internal/provider/resources/certificate"
	resourcegroup "github.com/openai/terraform-provider-openai/internal/provider/resources/group"
	resourcegrouprole "github.com/openai/terraform-provider-openai/internal/provider/resources/group_role"
	resourcegroupuser "github.com/openai/terraform-provider-openai/internal/provider/resources/group_user"
	resourceinvite "github.com/openai/terraform-provider-openai/internal/provider/resources/invite"
	resourcemcptunnel "github.com/openai/terraform-provider-openai/internal/provider/resources/mcp_tunnel"
	resourceorganizationdataretention "github.com/openai/terraform-provider-openai/internal/provider/resources/organization_data_retention"
	resourceorganizationspendalert "github.com/openai/terraform-provider-openai/internal/provider/resources/organization_spend_alert"
	resourceorganizationspendlimit "github.com/openai/terraform-provider-openai/internal/provider/resources/organization_spend_limit"
	resourceorganizationuser "github.com/openai/terraform-provider-openai/internal/provider/resources/organization_user"
	resourceproject "github.com/openai/terraform-provider-openai/internal/provider/resources/project"
	resourceprojectcertificates "github.com/openai/terraform-provider-openai/internal/provider/resources/project_certificates"
	resourceprojectdataretention "github.com/openai/terraform-provider-openai/internal/provider/resources/project_data_retention"
	resourceprojectgroup "github.com/openai/terraform-provider-openai/internal/provider/resources/project_group"
	resourceprojectgrouprole "github.com/openai/terraform-provider-openai/internal/provider/resources/project_group_role"
	resourceprojecthostedtoolpermissions "github.com/openai/terraform-provider-openai/internal/provider/resources/project_hosted_tool_permissions"
	resourceprojectmodelpermissions "github.com/openai/terraform-provider-openai/internal/provider/resources/project_model_permissions"
	resourceprojectratelimit "github.com/openai/terraform-provider-openai/internal/provider/resources/project_rate_limit"
	resourceprojectrole "github.com/openai/terraform-provider-openai/internal/provider/resources/project_role"
	resourceprojectserviceaccount "github.com/openai/terraform-provider-openai/internal/provider/resources/project_service_account"
	resourceprojectspendalert "github.com/openai/terraform-provider-openai/internal/provider/resources/project_spend_alert"
	resourceprojectspendlimit "github.com/openai/terraform-provider-openai/internal/provider/resources/project_spend_limit"
	resourceprojectuser "github.com/openai/terraform-provider-openai/internal/provider/resources/project_user"
	resourceprojectuserrole "github.com/openai/terraform-provider-openai/internal/provider/resources/project_user_role"
	resourcerole "github.com/openai/terraform-provider-openai/internal/provider/resources/role"
	resourceuserrole "github.com/openai/terraform-provider-openai/internal/provider/resources/user_role"
	resourcewebhookendpoint "github.com/openai/terraform-provider-openai/internal/provider/resources/webhook_endpoint"
)

var _ provider.Provider = &OpenAIProvider{}

type OpenAIProvider struct {
	version string
}

type OpenAIProviderModel struct {
	AdminAPIKey  types.String `tfsdk:"admin_api_key"`
	APIKey       types.String `tfsdk:"api_key"`
	BaseURL      types.String `tfsdk:"base_url"`
	Organization types.String `tfsdk:"organization"`
	Project      types.String `tfsdk:"project"`
}

func (p *OpenAIProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "openai"
	resp.Version = p.version
}

func (p *OpenAIProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Terraform provider for OpenAI API Platform administration and beta project webhook APIs.",
		Attributes: map[string]schema.Attribute{
			"admin_api_key": schema.StringAttribute{
				MarkdownDescription: "Admin API key used for organization administration requests.",
				Required:            false,
				Optional:            true,
				Sensitive:           true,
			},
			"api_key": schema.StringAttribute{
				MarkdownDescription: "Project API key used for project-scoped requests such as webhook management.",
				Required:            false,
				Optional:            true,
				Sensitive:           true,
			},
			"base_url": schema.StringAttribute{
				MarkdownDescription: "Base URL used for OpenAI API requests.",
				Required:            false,
				Optional:            true,
				Sensitive:           false,
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "Organization identifier to send with requests.",
				Required:            false,
				Optional:            true,
				Sensitive:           false,
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project identifier to send with requests.",
				Required:            false,
				Optional:            true,
				Sensitive:           false,
			},
		},
	}
}

func (p *OpenAIProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data OpenAIProviderModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	clientConfig := &openaiapi.APIClient{BaseURL: "https://api.openai.com/v1", ProviderVersion: p.version}
	if data.AdminAPIKey.IsUnknown() {
		resp.Diagnostics.AddError("Unknown OpenAI credential", "The admin_api_key provider attribute must be known during provider configuration; omit it to use OPENAI_ADMIN_KEY.")
		return
	}
	if !data.AdminAPIKey.IsNull() {
		clientConfig.AdminAPIKey = data.AdminAPIKey.ValueString()
	} else if value, ok := os.LookupEnv("OPENAI_ADMIN_KEY"); ok {
		clientConfig.AdminAPIKey = value
	}

	credentialAPIKeyFromEnvironment := false
	if data.APIKey.IsUnknown() {
		resp.Diagnostics.AddError("Unknown OpenAI credential", "The api_key provider attribute must be known during provider configuration; omit it to use OPENAI_API_KEY.")
		return
	}
	if !data.APIKey.IsNull() {
		clientConfig.APIKey = data.APIKey.ValueString()
	} else if value, ok := os.LookupEnv("OPENAI_API_KEY"); ok {
		clientConfig.APIKey = value
		credentialAPIKeyFromEnvironment = strings.TrimSpace(value) != ""
	}

	if !data.BaseURL.IsNull() && !data.BaseURL.IsUnknown() {
		clientConfig.BaseURL = data.BaseURL.ValueString()
	}

	if !data.Organization.IsNull() && !data.Organization.IsUnknown() {
		clientConfig.Organization = data.Organization.ValueString()
	} else if value, ok := os.LookupEnv("OPENAI_ORG_ID"); ok {
		clientConfig.Organization = value
	}

	if !data.Project.IsNull() && !data.Project.IsUnknown() {
		clientConfig.Project = data.Project.ValueString()
	} else if value, ok := os.LookupEnv("OPENAI_PROJECT_ID"); ok {
		clientConfig.Project = value
	}

	clientConfig.BaseURL = strings.TrimSpace(clientConfig.BaseURL)
	apiEndpoint, err := validateAPIBaseURL(clientConfig.BaseURL)
	if err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API base URL", err.Error())
		return
	}
	if credentialAPIKeyFromEnvironment && !isDefaultOpenAIAPIOrigin(apiEndpoint) {
		clientConfig.APIKey = ""
		if strings.TrimSpace(clientConfig.AdminAPIKey) == "" {
			resp.Diagnostics.AddError("Ambient OpenAI credential requires default origin", "OPENAI_API_KEY is only used with the default OpenAI API origin. Set the api_key provider attribute explicitly to authorize this credential audience for a custom base_url.")
			return
		}
		resp.Diagnostics.AddWarning("Ignored ambient OpenAI credential", "OPENAI_API_KEY is only used with the default OpenAI API origin. Set the api_key provider attribute explicitly to authorize this credential audience for a custom base_url.")
	}
	if strings.TrimSpace(clientConfig.AdminAPIKey) == "" && strings.TrimSpace(clientConfig.APIKey) == "" {
		resp.Diagnostics.AddError("Missing OpenAI API key", "Set admin_api_key, OPENAI_ADMIN_KEY, api_key, OPENAI_API_KEY.")
		return
	}
	newAPIClient := func(apiKey string) *openaiapi.APIClient {
		options := []option.RequestOption{
			option.WithBaseURL(clientConfig.BaseURL),
			option.WithHTTPClient(newCredentialAudienceHTTPClient(apiEndpoint)),
			option.WithAPIKey(apiKey),
		}
		if strings.TrimSpace(clientConfig.Organization) != "" {
			options = append(options, option.WithOrganization(clientConfig.Organization))
		}
		if strings.TrimSpace(clientConfig.Project) != "" {
			options = append(options, option.WithProject(clientConfig.Project))
		}
		return &openaiapi.APIClient{
			BaseURL:         clientConfig.BaseURL,
			Organization:    clientConfig.Organization,
			Project:         clientConfig.Project,
			ProviderVersion: p.version,
			Client:          openai.NewClient(options...),
		}
	}
	providerData := openaiapi.NewProviderData()
	if apiKey := strings.TrimSpace(clientConfig.AdminAPIKey); apiKey != "" {
		providerData.SetClient("admin", newAPIClient(apiKey))
	}
	if apiKey := strings.TrimSpace(clientConfig.APIKey); apiKey != "" {
		providerData.SetClient("project", newAPIClient(apiKey))
	}
	resp.DataSourceData = providerData
	resp.ResourceData = providerData
}

func (p *OpenAIProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		resourcewebhookendpoint.NewWebhookEndpointResource,
		resourcemcptunnel.NewMcpTunnelResource,
		resourceinvite.NewInviteResource,
		resourceorganizationuser.NewOrganizationUserResource,
		resourceuserrole.NewUserRoleResource,
		resourcegroup.NewGroupResource,
		resourcegroupuser.NewGroupUserResource,
		resourcegrouprole.NewGroupRoleResource,
		resourcerole.NewRoleResource,
		resourceprojectrole.NewProjectRoleResource,
		resourceproject.NewProjectResource,
		resourceprojectspendalert.NewProjectSpendAlertResource,
		resourceorganizationspendalert.NewOrganizationSpendAlertResource,
		resourceprojectratelimit.NewProjectRateLimitResource,
		resourceprojectuser.NewProjectUserResource,
		resourceprojectuserrole.NewProjectUserRoleResource,
		resourceprojectgrouprole.NewProjectGroupRoleResource,
		resourceprojectgroup.NewProjectGroupResource,
		resourceprojectserviceaccount.NewProjectServiceAccountResource,
		resourcecertificate.NewCertificateResource,
		resourceorganizationdataretention.NewOrganizationDataRetentionResource,
		resourceorganizationspendlimit.NewOrganizationSpendLimitResource,
		resourceprojectmodelpermissions.NewProjectModelPermissionsResource,
		resourceprojecthostedtoolpermissions.NewProjectHostedToolPermissionsResource,
		resourceprojectdataretention.NewProjectDataRetentionResource,
		resourceprojectspendlimit.NewProjectSpendLimitResource,
	}
}

func (p *OpenAIProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		resourcewebhookendpoint.NewWebhookEndpointDataSource,
		resourcewebhookendpoint.NewWebhookEndpointsDataSource,
		resourcewebhookendpoint.NewWebhookEventTypesDataSource,
		resourcemcptunnel.NewMcpTunnelDataSource,
		resourceinvite.NewInviteDataSource,
		resourceinvite.NewInvitesDataSource,
		resourceorganizationuser.NewOrganizationUserDataSource,
		resourceorganizationuser.NewOrganizationUsersDataSource,
		resourceuserrole.NewUserRoleDataSource,
		resourceuserrole.NewUserRolesDataSource,
		resourcegroup.NewGroupDataSource,
		resourcegroup.NewGroupsDataSource,
		resourcegroupuser.NewGroupUserDataSource,
		resourcegroupuser.NewGroupUsersDataSource,
		resourcegrouprole.NewGroupRoleDataSource,
		resourcegrouprole.NewGroupRolesDataSource,
		resourcerole.NewRoleDataSource,
		resourcerole.NewRolesDataSource,
		resourceprojectrole.NewProjectRoleDataSource,
		resourceprojectrole.NewProjectRolesDataSource,
		resourceproject.NewProjectDataSource,
		resourcecertificate.NewCertificateDataSource,
		resourcecertificate.NewCertificatesDataSource,
		resourceorganizationdataretention.NewOrganizationDataRetentionDataSource,
		resourceorganizationspendlimit.NewOrganizationSpendLimitDataSource,
		resourceprojectmodelpermissions.NewProjectModelPermissionsDataSource,
		resourceprojecthostedtoolpermissions.NewProjectHostedToolPermissionsDataSource,
		resourceprojectdataretention.NewProjectDataRetentionDataSource,
		resourceprojectspendlimit.NewProjectSpendLimitDataSource,
		resourceprojectcertificates.NewProjectCertificatesDataSource,
		resourceorganizationspendalert.NewOrganizationSpendAlertsDataSource,
		resourceprojectspendalert.NewProjectSpendAlertDataSource,
		resourceprojectspendalert.NewProjectSpendAlertsDataSource,
		resourceprojectratelimit.NewProjectRateLimitDataSource,
		resourceprojectratelimit.NewProjectRateLimitsDataSource,
		resourceprojectuser.NewProjectUserDataSource,
		resourceproject.NewProjectsDataSource,
		resourceprojectuser.NewProjectUsersDataSource,
		resourceprojectuserrole.NewProjectUserRoleDataSource,
		resourceprojectuserrole.NewProjectUserRolesDataSource,
		resourceprojectgrouprole.NewProjectGroupRoleDataSource,
		resourceprojectgrouprole.NewProjectGroupRolesDataSource,
		resourceprojectgroup.NewProjectGroupDataSource,
		resourceprojectgroup.NewProjectGroupsDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &OpenAIProvider{
			version: version,
		}
	}
}
