// Code generated by generate-terraform-provider. DO NOT EDIT.

package provider

import (
	"context"
	"os"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openai "github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
	resourcecertificate "github.com/openai/terraform-provider-openai/internal/provider/resources/certificate"
	resourcegroup "github.com/openai/terraform-provider-openai/internal/provider/resources/group"
	resourcegrouprole "github.com/openai/terraform-provider-openai/internal/provider/resources/group_role"
	resourcegroupuser "github.com/openai/terraform-provider-openai/internal/provider/resources/group_user"
	resourceinvite "github.com/openai/terraform-provider-openai/internal/provider/resources/invite"
	resourceorganizationdataretention "github.com/openai/terraform-provider-openai/internal/provider/resources/organization_data_retention"
	resourceorganizationspendalert "github.com/openai/terraform-provider-openai/internal/provider/resources/organization_spend_alert"
	resourceorganizationuser "github.com/openai/terraform-provider-openai/internal/provider/resources/organization_user"
	resourceproject "github.com/openai/terraform-provider-openai/internal/provider/resources/project"
	resourceprojectcertificates "github.com/openai/terraform-provider-openai/internal/provider/resources/project_certificates"
	resourceprojectdataretention "github.com/openai/terraform-provider-openai/internal/provider/resources/project_data_retention"
	resourceprojectgroup "github.com/openai/terraform-provider-openai/internal/provider/resources/project_group"
	resourceprojectgrouprole "github.com/openai/terraform-provider-openai/internal/provider/resources/project_group_role"
	resourceprojecthostedtoolpermissions "github.com/openai/terraform-provider-openai/internal/provider/resources/project_hosted_tool_permissions"
	resourceprojectmodelpermissions "github.com/openai/terraform-provider-openai/internal/provider/resources/project_model_permissions"
	resourceprojectratelimit "github.com/openai/terraform-provider-openai/internal/provider/resources/project_rate_limit"
	resourceprojectratelimits "github.com/openai/terraform-provider-openai/internal/provider/resources/project_rate_limits"
	resourceprojectrole "github.com/openai/terraform-provider-openai/internal/provider/resources/project_role"
	resourceprojectserviceaccount "github.com/openai/terraform-provider-openai/internal/provider/resources/project_service_account"
	resourceprojectspendalert "github.com/openai/terraform-provider-openai/internal/provider/resources/project_spend_alert"
	resourceprojectuser "github.com/openai/terraform-provider-openai/internal/provider/resources/project_user"
	resourceprojectuserrole "github.com/openai/terraform-provider-openai/internal/provider/resources/project_user_role"
	resourcerole "github.com/openai/terraform-provider-openai/internal/provider/resources/role"
	resourceuserrole "github.com/openai/terraform-provider-openai/internal/provider/resources/user_role"
)

var _ provider.Provider = &OpenAIProvider{}

type OpenAIProvider struct {
	version string
}

type OpenAIProviderModel struct {
	AdminAPIKey  types.String `tfsdk:"admin_api_key"`
	BaseURL      types.String `tfsdk:"base_url"`
	Organization types.String `tfsdk:"organization"`
	Project      types.String `tfsdk:"project"`
}

func (p *OpenAIProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "openai"
	resp.Version = p.version
}

func (p *OpenAIProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Terraform provider for OpenAI administration APIs, specific to the API Platform.",
		Attributes: map[string]schema.Attribute{
			"admin_api_key": schema.StringAttribute{
				MarkdownDescription: "Admin API key used for organization administration requests.",
				Required:            false,
				Optional:            true,
				Sensitive:           true,
			},
			"base_url": schema.StringAttribute{
				MarkdownDescription: "Base URL used for OpenAI API requests.",
				Required:            false,
				Optional:            true,
				Sensitive:           false,
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "Organization identifier to send with requests.",
				Required:            false,
				Optional:            true,
				Sensitive:           false,
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project identifier to send with requests.",
				Required:            false,
				Optional:            true,
				Sensitive:           false,
			},
		},
	}
}

func (p *OpenAIProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data OpenAIProviderModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := &openaiapi.APIClient{BaseURL: "https://api.openai.com/v1", ProviderVersion: p.version}
	if !data.AdminAPIKey.IsNull() && !data.AdminAPIKey.IsUnknown() {
		client.AdminAPIKey = data.AdminAPIKey.ValueString()
	} else if value, ok := os.LookupEnv("OPENAI_ADMIN_KEY"); ok {
		client.AdminAPIKey = value
	}

	if !data.BaseURL.IsNull() && !data.BaseURL.IsUnknown() {
		client.BaseURL = data.BaseURL.ValueString()
	}

	if !data.Organization.IsNull() && !data.Organization.IsUnknown() {
		client.Organization = data.Organization.ValueString()
	} else if value, ok := os.LookupEnv("OPENAI_ORG_ID"); ok {
		client.Organization = value
	}

	if !data.Project.IsNull() && !data.Project.IsUnknown() {
		client.Project = data.Project.ValueString()
	} else if value, ok := os.LookupEnv("OPENAI_PROJECT_ID"); ok {
		client.Project = value
	}

	if client.BaseURL = strings.TrimSpace(client.BaseURL); client.BaseURL == "" {
		resp.Diagnostics.AddError("Invalid OpenAI API base URL", "base_url must not be empty.")
		return
	}
	if strings.TrimSpace(client.AdminAPIKey) == "" {
		resp.Diagnostics.AddError("Missing OpenAI API key", "Set admin_api_key, OPENAI_ADMIN_KEY.")
		return
	}
	options := []option.RequestOption{option.WithBaseURL(client.BaseURL)}
	apiKey := strings.TrimSpace(client.AdminAPIKey)
	if apiKey != "" {
		options = append(options, option.WithAPIKey(apiKey))
	}
	if strings.TrimSpace(client.Organization) != "" {
		options = append(options, option.WithOrganization(client.Organization))
	}
	if strings.TrimSpace(client.Project) != "" {
		options = append(options, option.WithProject(client.Project))
	}
	client.Client = openai.NewClient(options...)
	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *OpenAIProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		resourceinvite.NewInviteResource,
		resourceorganizationuser.NewOrganizationUserResource,
		resourceuserrole.NewUserRoleResource,
		resourcegroup.NewGroupResource,
		resourcegroupuser.NewGroupUserResource,
		resourcegrouprole.NewGroupRoleResource,
		resourcerole.NewRoleResource,
		resourceprojectrole.NewProjectRoleResource,
		resourceproject.NewProjectResource,
		resourceprojectspendalert.NewProjectSpendAlertResource,
		resourceorganizationspendalert.NewOrganizationSpendAlertResource,
		resourceprojectratelimit.NewProjectRateLimitResource,
		resourceprojectratelimits.NewProjectRateLimitsResource,
		resourceprojectuser.NewProjectUserResource,
		resourceprojectuserrole.NewProjectUserRoleResource,
		resourceprojectgrouprole.NewProjectGroupRoleResource,
		resourceprojectgroup.NewProjectGroupResource,
		resourceprojectserviceaccount.NewProjectServiceAccountResource,
		resourcecertificate.NewCertificateResource,
		resourceorganizationdataretention.NewOrganizationDataRetentionResource,
		resourceprojectmodelpermissions.NewProjectModelPermissionsResource,
		resourceprojecthostedtoolpermissions.NewProjectHostedToolPermissionsResource,
		resourceprojectdataretention.NewProjectDataRetentionResource,
	}
}

func (p *OpenAIProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		resourceinvite.NewInviteDataSource,
		resourceinvite.NewInvitesDataSource,
		resourceorganizationuser.NewOrganizationUserDataSource,
		resourceorganizationuser.NewOrganizationUsersDataSource,
		resourceuserrole.NewUserRoleDataSource,
		resourceuserrole.NewUserRolesDataSource,
		resourcegroup.NewGroupDataSource,
		resourcegroup.NewGroupsDataSource,
		resourcegroupuser.NewGroupUserDataSource,
		resourcegroupuser.NewGroupUsersDataSource,
		resourcegrouprole.NewGroupRoleDataSource,
		resourcegrouprole.NewGroupRolesDataSource,
		resourcerole.NewRoleDataSource,
		resourcerole.NewRolesDataSource,
		resourceprojectrole.NewProjectRoleDataSource,
		resourceprojectrole.NewProjectRolesDataSource,
		resourceproject.NewProjectDataSource,
		resourcecertificate.NewCertificateDataSource,
		resourcecertificate.NewCertificatesDataSource,
		resourceorganizationdataretention.NewOrganizationDataRetentionDataSource,
		resourceprojectmodelpermissions.NewProjectModelPermissionsDataSource,
		resourceprojecthostedtoolpermissions.NewProjectHostedToolPermissionsDataSource,
		resourceprojectdataretention.NewProjectDataRetentionDataSource,
		resourceprojectcertificates.NewProjectCertificatesDataSource,
		resourceorganizationspendalert.NewOrganizationSpendAlertsDataSource,
		resourceprojectspendalert.NewProjectSpendAlertDataSource,
		resourceprojectspendalert.NewProjectSpendAlertsDataSource,
		resourceprojectratelimit.NewProjectRateLimitDataSource,
		resourceprojectratelimit.NewProjectRateLimitsDataSource,
		resourceprojectuser.NewProjectUserDataSource,
		resourceproject.NewProjectsDataSource,
		resourceprojectuser.NewProjectUsersDataSource,
		resourceprojectuserrole.NewProjectUserRoleDataSource,
		resourceprojectuserrole.NewProjectUserRolesDataSource,
		resourceprojectgrouprole.NewProjectGroupRoleDataSource,
		resourceprojectgrouprole.NewProjectGroupRolesDataSource,
		resourceprojectgroup.NewProjectGroupDataSource,
		resourceprojectgroup.NewProjectGroupsDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &OpenAIProvider{
			version: version,
		}
	}
}
