// Code generated by generate-terraform-provider. DO NOT EDIT.

package projectcertificates

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ datasource.DataSource = &ProjectCertificatesDataSource{}
var _ datasource.DataSourceWithConfigure = &ProjectCertificatesDataSource{}

type ProjectCertificatesDataSource struct {
	client *openaiapi.APIClient
}

type ProjectCertificatesDataSourceModel struct {
	ProjectID    types.String `tfsdk:"project_id"`
	ID           types.String `tfsdk:"id"`
	ResponseJSON types.String `tfsdk:"response_json"`
	Certificates types.List   `tfsdk:"certificates"`
}

type ProjectCertificatesDataSourceItemModel struct {
	ID        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	CreatedAt types.Int64  `tfsdk:"created_at"`
	ValidAt   types.Int64  `tfsdk:"valid_at"`
	ExpiresAt types.Int64  `tfsdk:"expires_at"`
	Active    types.Bool   `tfsdk:"active"`
}

func NewProjectCertificatesDataSource() datasource.DataSource {
	return &ProjectCertificatesDataSource{}
}

func (d *ProjectCertificatesDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_project_certificates"
}

func (d *ProjectCertificatesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "List project certificates.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "project id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Synthetic data source identifier.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},

			"certificates": schema.ListNestedAttribute{
				MarkdownDescription: "Project certificates returned by the API.",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "id",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "name",
							Computed:            true,
						},
						"created_at": schema.Int64Attribute{
							MarkdownDescription: "created at",
							Computed:            true,
						},
						"valid_at": schema.Int64Attribute{
							MarkdownDescription: "valid at",
							Computed:            true,
						},
						"expires_at": schema.Int64Attribute{
							MarkdownDescription: "expires at",
							Computed:            true,
						},
						"active": schema.BoolAttribute{
							MarkdownDescription: "active",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *ProjectCertificatesDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *ProjectCertificatesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectCertificatesDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"project_id": data.ProjectID.ValueString(),
	}
	queryParams := map[string]string{
		"limit": "100",
	}
	responseData, err := d.client.PaginatedRequest(ctx, "GET", "/organization/projects/{project_id}/certificates", pathParams, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	data.ID = types.StringValue(fmt.Sprintf("openai_project_certificates/%s", data.ProjectID.ValueString()))

	resultItems, err := openaiapi.ResponseObjectList(responseData, "data", true)
	if err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	items := []ProjectCertificatesDataSourceItemModel{}
	for _, itemData := range resultItems {
		item := ProjectCertificatesDataSourceItemModel{}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"id"}, &item.ID, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"name"}, &item.Name, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"created_at"}, &item.CreatedAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"certificate_details.valid_at"}, &item.ValidAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"certificate_details.expires_at"}, &item.ExpiresAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyBoolResponseField(itemData, []string{"active"}, &item.Active, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		items = append(items, item)
	}
	itemsValue, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: map[string]attr.Type{
		"id":         types.StringType,
		"name":       types.StringType,
		"created_at": types.Int64Type,
		"valid_at":   types.Int64Type,
		"expires_at": types.Int64Type,
		"active":     types.BoolType,
	}}, items)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	data.Certificates = itemsValue
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
