// Code generated by generate-terraform-provider. DO NOT EDIT.

package project

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ datasource.DataSource = &ProjectsDataSource{}
var _ datasource.DataSourceWithConfigure = &ProjectsDataSource{}

type ProjectsDataSource struct {
	client *openaiapi.APIClient
}

type ProjectsDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	ResponseJSON types.String `tfsdk:"response_json"`
	Projects     types.List   `tfsdk:"projects"`
}

type ProjectsDataSourceItemModel struct {
	ID            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	ExternalKeyID types.String `tfsdk:"external_key_id"`
	CreatedAt     types.Int64  `tfsdk:"created_at"`
	ArchivedAt    types.Int64  `tfsdk:"archived_at"`
	Status        types.String `tfsdk:"status"`
}

func NewProjectsDataSource() datasource.DataSource {
	return &ProjectsDataSource{}
}

func (d *ProjectsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_projects"
}

func (d *ProjectsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "List organization projects.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Synthetic data source identifier.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},

			"projects": schema.ListNestedAttribute{
				MarkdownDescription: "Projects returned by the API.",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "id",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "name",
							Computed:            true,
						},
						"external_key_id": schema.StringAttribute{
							MarkdownDescription: "external key id",
							Computed:            true,
						},
						"created_at": schema.Int64Attribute{
							MarkdownDescription: "created at",
							Computed:            true,
						},
						"archived_at": schema.Int64Attribute{
							MarkdownDescription: "archived at",
							Computed:            true,
						},
						"status": schema.StringAttribute{
							MarkdownDescription: "status",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *ProjectsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *ProjectsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectsDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{}
	queryParams := map[string]string{
		"include_archived": "false",
		"limit":            "100",
	}
	responseData, err := d.client.PaginatedRequest(ctx, "GET", "/organization/projects", pathParams, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	data.ID = types.StringValue("openai_projects")

	resultItems, err := openaiapi.ResponseObjectList(responseData, "data", true)
	if err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	items := []ProjectsDataSourceItemModel{}
	for _, itemData := range resultItems {
		item := ProjectsDataSourceItemModel{}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"id"}, &item.ID, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"name"}, &item.Name, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"external_key_id"}, &item.ExternalKeyID, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"created_at"}, &item.CreatedAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"archived_at"}, &item.ArchivedAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"status"}, &item.Status, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		items = append(items, item)
	}
	itemsValue, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: map[string]attr.Type{
		"id":              types.StringType,
		"name":            types.StringType,
		"external_key_id": types.StringType,
		"created_at":      types.Int64Type,
		"archived_at":     types.Int64Type,
		"status":          types.StringType,
	}}, items)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	data.Projects = itemsValue
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
