// Code generated by generate-terraform-provider. DO NOT EDIT.

package project_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccProjectBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "test" {
  name = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-openai-project-{suffix}"),
	)
}

func testAccProjectBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "test" {
  name = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-openai-project-updated-{suffix}"),
	)
}

func testAccProjectNullableFieldsConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "test" {
  name = %q
  geography = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-openai-project-nullable-{suffix}"),
		acctest.FixtureValue(t, "project_geography"),
	)
}

func testAccProjectNullableFieldsConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_project" "test" {
  name = %q
  geography = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-openai-project-nullable-updated-{suffix}"),
		acctest.FixtureValue(t, "project_geography_updated"),
	)
}

func TestAccProject_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccProjectBasicConfig1(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("openai_project.test", "name", acctest.TemplateValue(t, "tf-acc-openai-project-{suffix}")),
				),
			},
			{
				Config: testAccProjectBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("openai_project.test", "name", acctest.TemplateValue(t, "tf-acc-openai-project-updated-{suffix}")),
				),
			},
			{
				ResourceName:      "openai_project.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccProject_NullableFields(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccProjectNullableFieldsConfig1(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("openai_project.test", "name", acctest.TemplateValue(t, "tf-acc-openai-project-nullable-{suffix}")),
					resource.TestCheckResourceAttr("openai_project.test", "geography", acctest.FixtureValue(t, "project_geography")),
				),
			},
			{
				Config: testAccProjectNullableFieldsConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("openai_project.test", "name", acctest.TemplateValue(t, "tf-acc-openai-project-nullable-updated-{suffix}")),
					resource.TestCheckResourceAttr("openai_project.test", "geography", acctest.FixtureValue(t, "project_geography_updated")),
				),
			},
		},
	})
}
