// Code generated by generate-terraform-provider. DO NOT EDIT.

package group

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"
)

var _ datasource.DataSource = &GroupsDataSource{}
var _ datasource.DataSourceWithConfigure = &GroupsDataSource{}

type GroupsDataSource struct {
	client *openaiapi.APIClient
}

type GroupsDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	ResponseJSON types.String `tfsdk:"response_json"`
	Groups       types.List   `tfsdk:"groups"`
}

type GroupsDataSourceItemModel struct {
	ID            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	CreatedAt     types.Int64  `tfsdk:"created_at"`
	IsScimManaged types.Bool   `tfsdk:"is_scim_managed"`
	GroupType     types.String `tfsdk:"group_type"`
}

func NewGroupsDataSource() datasource.DataSource {
	return &GroupsDataSource{}
}

func (d *GroupsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_groups"
}

func (d *GroupsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "List organization groups.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Synthetic data source identifier.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},

			"groups": schema.ListNestedAttribute{
				MarkdownDescription: "Groups returned by the API.",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "id",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "name",
							Computed:            true,
						},
						"created_at": schema.Int64Attribute{
							MarkdownDescription: "created at",
							Computed:            true,
						},
						"is_scim_managed": schema.BoolAttribute{
							MarkdownDescription: "is scim managed",
							Computed:            true,
						},
						"group_type": schema.StringAttribute{
							MarkdownDescription: "group type",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *GroupsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *GroupsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data GroupsDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{}
	queryParams := map[string]string{
		"limit": "100",
	}
	responseData, err := d.client.PaginatedRequest(ctx, "GET", "/organization/groups", pathParams, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	data.ID = types.StringValue("openai_groups")

	resultItems, err := openaiapi.ResponseObjectList(responseData, "data", true)
	if err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	items := []GroupsDataSourceItemModel{}
	for _, itemData := range resultItems {
		item := GroupsDataSourceItemModel{}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"id"}, &item.ID, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"name"}, &item.Name, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyInt64ResponseField(itemData, []string{"created_at"}, &item.CreatedAt, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyBoolResponseField(itemData, []string{"is_scim_managed"}, &item.IsScimManaged, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		if err := openaiapi.ApplyStringResponseField(itemData, []string{"group_type"}, &item.GroupType, false); err != nil {
			resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
			return
		}
		items = append(items, item)
	}
	itemsValue, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: map[string]attr.Type{
		"id":              types.StringType,
		"name":            types.StringType,
		"created_at":      types.Int64Type,
		"is_scim_managed": types.BoolType,
		"group_type":      types.StringType,
	}}, items)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	data.Groups = itemsValue
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
