// Code generated by generate-terraform-provider. DO NOT EDIT.

package group_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	acctest "github.com/openai/terraform-provider-openai/internal/provider/acctest"
)

func testAccDataSourceGroupBasicConfig1(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_group" "source" {
  name = %q
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-group-{suffix}"),
	)
}

func testAccDataSourceGroupBasicConfig2(t *testing.T) string {
	t.Helper()
	return fmt.Sprintf(
		`provider "openai" {}

resource "openai_group" "source" {
  name = %q
}

data "openai_group" "lookup" {
  group_id = openai_group.source.group_id
}
`,
		acctest.TemplateValue(t, "tf-acc-ds-openai-group-{suffix}"),
	)
}

func TestAccDataSourceGroup_Basic(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheck(t, []string{"OPENAI_ADMIN_KEY"})
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceGroupBasicConfig1(t),
			},
			{
				Config: testAccDataSourceGroupBasicConfig2(t),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("data.openai_group.lookup", "group_id", "openai_group.source", "group_id"),
					resource.TestCheckResourceAttrPair("data.openai_group.lookup", "name", "openai_group.source", "name"),
				),
			},
		},
	})
}
