// Code generated by generate-terraform-provider. DO NOT EDIT.

package group

import (
	"context"
	"fmt"

	openaiapi "github.com/openai/terraform-provider-openai/internal/provider/openaiapi"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &GroupDataSource{}
var _ datasource.DataSourceWithConfigure = &GroupDataSource{}

type GroupDataSource struct {
	client *openaiapi.APIClient
}

type GroupDataSourceModel struct {
	GroupID       types.String `tfsdk:"group_id"`
	ID            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	CreatedAt     types.Int64  `tfsdk:"created_at"`
	IsScimManaged types.Bool   `tfsdk:"is_scim_managed"`
	GroupType     types.String `tfsdk:"group_type"`
	ResponseJSON  types.String `tfsdk:"response_json"`
}

func NewGroupDataSource() datasource.DataSource {
	return &GroupDataSource{}
}

func (d *GroupDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "openai_group"
}

func (d *GroupDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Look up an organization group by ID.",
		Attributes: map[string]schema.Attribute{
			"group_id": schema.StringAttribute{
				MarkdownDescription: "group id",
				Required:            true,
				Optional:            false,
				Computed:            false,
				Sensitive:           false,
				Validators: []validator.String{
					openaiapi.StringIsValidPathParameter(),
					openaiapi.StringLengthAtLeast(1),
				},
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "id",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "name",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"created_at": schema.Int64Attribute{
				MarkdownDescription: "created at",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"is_scim_managed": schema.BoolAttribute{
				MarkdownDescription: "is scim managed",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"group_type": schema.StringAttribute{
				MarkdownDescription: "group type",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
			"response_json": schema.StringAttribute{
				MarkdownDescription: "Raw JSON response returned by the OpenAI API.",
				Required:            false,
				Optional:            false,
				Computed:            true,
				Sensitive:           false,
			},
		},
	}
}

func (d *GroupDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*openaiapi.APIClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *openaiapi.APIClient, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *GroupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data GroupDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if d.client == nil {
		resp.Diagnostics.AddError("Missing OpenAI API client", "The provider was not configured before this operation ran.")
		return
	}
	pathParams := map[string]string{
		"group_id": data.GroupID.ValueString(),
	}
	queryParams := map[string]string{}
	responseData, err := d.client.Request(ctx, "GET", "/organization/groups/{group_id}", pathParams, queryParams, nil)
	if err != nil {
		resp.Diagnostics.AddError("OpenAI API request failed", err.Error())
		return
	}
	data.ID = types.StringValue(fmt.Sprintf("openai_group/%s", data.GroupID.ValueString()))
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"id"}, &data.ID, true); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"name"}, &data.Name, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyInt64ResponseField(responseData, []string{"created_at"}, &data.CreatedAt, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyBoolResponseField(responseData, []string{"is_scim_managed"}, &data.IsScimManaged, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	if err := openaiapi.ApplyStringResponseField(responseData, []string{"group_type"}, &data.GroupType, false); err != nil {
		resp.Diagnostics.AddError("Invalid OpenAI API response", err.Error())
		return
	}
	data.ResponseJSON = openaiapi.ResponseJSONValue(responseData)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
